MIOAUTHSESS ; Shared local auth session lifecycle
	QUIT
	;
ISSUE(CONF,APP,USER,DISPLAY,ROLES,TOKEN,ERR)
	NEW SID,NOW,MAXAGE,CLAIMS,APPKEY,TOT,DAY,SEC
	KILL ERR SET TOKEN=""
	SET ERR("routine")="MIOAUTHSESS"
	SET APPKEY=$$APPKEY($GET(APP))
	IF APPKEY="" SET ERR("error")="app_missing" QUIT 0
	IF $GET(USER)="" SET ERR("error")="principal_missing" QUIT 0
	SET NOW=$$NOW^MIOJWT(),MAXAGE=$$MAXAGE(.CONF,APPKEY)
	IF MAXAGE<1 SET MAXAGE=604800
	SET SID="auth-"_$$UUID^MIOUTIL()
	SET CLAIMS("sub")=$GET(USER)
	SET CLAIMS("preferred_username")=$GET(USER)
	SET CLAIMS("name")=$SELECT($GET(DISPLAY)'="":$GET(DISPLAY),1:$GET(USER))
	SET CLAIMS("roles")=$GET(ROLES)
	SET CLAIMS("sid")=SID
	SET CLAIMS("iss")=$$ISSUER(APPKEY)
	SET CLAIMS("aud")=APPKEY
	SET CLAIMS("iat")=NOW
	SET CLAIMS("exp")=NOW+MAXAGE
	IF '$$MAKEHS256^MIOJWT(.CONF,.CLAIMS,.TOKEN,.ERR) QUIT 0
	SET TOT=(+$PIECE($HOROLOG,",",1)*86400)+$PIECE($HOROLOG,",",2)+MAXAGE
	SET DAY=TOT\86400,SEC=TOT#86400
	SET ^MIO("AUTH","SESSION",APPKEY,SID,"principal")=$GET(USER)
	SET ^MIO("AUTH","SESSION",APPKEY,SID,"userName")=$GET(CLAIMS("name"))
	SET ^MIO("AUTH","SESSION",APPKEY,SID,"roles")=$GET(ROLES)
	SET ^MIO("AUTH","SESSION",APPKEY,SID,"tokenIssuedAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("AUTH","SESSION",APPKEY,SID,"createdAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("AUTH","SESSION",APPKEY,SID,"expiresDay")=DAY
	SET ^MIO("AUTH","SESSION",APPKEY,SID,"expiresSec")=SEC
	SET ^MIO("AUTH","SESSION","BYUSER",APPKEY,$GET(USER),SID)=1
	QUIT 1
	;
LOAD(CONF,APP,REQ,CTX,ERR)
	NEW TOKEN,CLAIMS,SID,APPKEY,USER
	KILL ERR
	SET ERR("routine")="MIOAUTHSESS"
	SET APPKEY=$$APPKEY($GET(APP))
	IF APPKEY="" SET ERR("error")="login_required" QUIT 0
	SET TOKEN=$$TOKEN(.CONF,APPKEY,.REQ)
	IF TOKEN="" SET ERR("error")="login_required" QUIT 0
	IF '$$VERIFYHS256^MIOJWT(.CONF,TOKEN,.CLAIMS,.ERR) DO  QUIT 0
	. SET ERR("routine")="MIOAUTHSESS"
	. SET ERR("error")="login_required"
	SET SID=$GET(CLAIMS("sid")),USER=$GET(CLAIMS("sub"))
	IF SID=""!(USER="") SET ERR("error")="login_required" QUIT 0
	IF $GET(CLAIMS("iss"))'=$$ISSUER(APPKEY) SET ERR("error")="login_required" QUIT 0
	IF $GET(CLAIMS("aud"))'="",$GET(CLAIMS("aud"))'=APPKEY SET ERR("error")="login_required" QUIT 0
	IF '$DATA(^MIO("AUTH","SESSION",APPKEY,SID)) SET ERR("error")="login_required" QUIT 0
	IF $GET(^MIO("AUTH","SESSION",APPKEY,SID,"principal"))'=USER SET ERR("error")="login_required" QUIT 0
	IF $$EXPIRED(APPKEY,SID) DO  QUIT 0
	. DO REVOKESID(APPKEY,SID)
	. SET ERR("error")="login_required"
	IF $GET(^MIO("AUTH","SESSION",APPKEY,SID,"roles"))'="" SET CLAIMS("roles")=$GET(^MIO("AUTH","SESSION",APPKEY,SID,"roles"))
	IF $GET(^MIO("AUTH","SESSION",APPKEY,SID,"userName"))'="" SET CLAIMS("name")=$GET(^MIO("AUTH","SESSION",APPKEY,SID,"userName"))
	KILL CTX("auth")
	DO APPLY^MIOAUTHJWT(.CONF,.CTX,.CLAIMS)
	SET CTX("auth","sessionId")=SID
	SET CTX(APPKEY,"authToken")=TOKEN
	SET ^MIO("AUTH","SESSION",APPKEY,SID,"lastSeenAt")=$$NOWISO^MIOUTIL()
	QUIT 1
	;
REVOKE(CONF,APP,REQ,CTX)
	NEW TOKEN,CLAIMS,APPKEY,SID,ERR
	SET APPKEY=$$APPKEY($GET(APP))
	IF APPKEY="" QUIT:$Q 1
	IF APPKEY="" QUIT
	SET TOKEN=$GET(CTX(APPKEY,"authToken"))
	IF TOKEN="" SET TOKEN=$$TOKEN(.CONF,APPKEY,.REQ)
	IF TOKEN'="",$$VERIFYHS256^MIOJWT(.CONF,TOKEN,.CLAIMS,.ERR) DO
	. SET SID=$GET(CLAIMS("sid"))
	. IF SID'="" DO REVOKESID(APPKEY,SID)
	QUIT:$Q 1
	QUIT
	;
SYNCROLES(APP,USER,ROLES)
	NEW APPKEY,SID
	SET APPKEY=$$APPKEY($GET(APP))
	IF APPKEY="" QUIT
	SET SID=""
	FOR  SET SID=$ORDER(^MIO("AUTH","SESSION","BYUSER",APPKEY,$GET(USER),SID)) QUIT:SID=""  DO
	. IF $DATA(^MIO("AUTH","SESSION",APPKEY,SID))#2 DO
	. . SET ^MIO("AUTH","SESSION",APPKEY,SID,"roles")=$GET(ROLES)
	. . SET ^MIO("AUTH","SESSION",APPKEY,SID,"updatedAt")=$$NOWISO^MIOUTIL()
	QUIT
	;
COOKIEHDR(CONF,APP,TOKEN,CLEAR)
	NEW NAME,MAXAGE,OUT
	SET NAME=$$COOKIENAME(.CONF,$GET(APP))
	SET MAXAGE=$$MAXAGE(.CONF,$GET(APP))
	IF +$GET(CLEAR)=1 QUIT NAME_"=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax"
	SET OUT=NAME_"="_$GET(TOKEN)_"; Path=/; Max-Age="_MAXAGE_"; HttpOnly; SameSite=Lax"
	QUIT OUT
	;
TOKEN(CONF,APP,REQ)
	NEW NAME,HN,TOKEN
	SET NAME=$$COOKIENAME(.CONF,$GET(APP))
	SET TOKEN=$$COOKIE^MIOAUTHCTX(.REQ,NAME)
	IF TOKEN'="" QUIT TOKEN
	SET HN=$$HDRNAME(.CONF,$GET(APP))
	SET TOKEN=$GET(REQ("hdr",HN))
	IF TOKEN'="" QUIT TOKEN
	QUIT $GET(REQ("hdr",$$UPCASE(HN)))
	;
COOKIENAME(CONF,APP)
	NEW APPKEY,NAME
	SET APPKEY=$$APPKEY($GET(APP))
	SET NAME=$GET(CONF("auth","jwt","cookieName"))
	IF NAME'="" QUIT NAME
	IF APPKEY="miomos" SET NAME=$GET(CONF("miomos","localAuth","tokenCookie")) IF NAME'="" QUIT NAME
	SET NAME=$GET(CONF("auth","session",APPKEY,"cookieName"))
	IF NAME'="" QUIT NAME
	QUIT APPKEY_"_auth"
	;
HDRNAME(CONF,APP)
	NEW APPKEY,NAME
	SET APPKEY=$$APPKEY($GET(APP))
	SET NAME=$GET(CONF("auth","session",APPKEY,"headerName"))
	IF NAME'="" QUIT $$LOW(NAME)
	QUIT "x-"_APPKEY_"-auth"
	;
MAXAGE(CONF,APP)
	NEW APPKEY,X
	SET APPKEY=$$APPKEY($GET(APP))
	SET X=+$GET(CONF("auth","session",APPKEY,"maxAgeSeconds"))
	IF X>0 QUIT X
	IF APPKEY="miomos" QUIT +$GET(CONF("miomos","localAuth","tokenMaxAgeSeconds"),604800)
	QUIT 604800
	;
EXPIRED(APP,SID)
	NEW DAY,SEC,NOWD,NOWS
	SET DAY=+$GET(^MIO("AUTH","SESSION",$GET(APP),$GET(SID),"expiresDay"))
	SET SEC=+$GET(^MIO("AUTH","SESSION",$GET(APP),$GET(SID),"expiresSec"))
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	IF (DAY=0),(SEC=0) QUIT 0
	QUIT $SELECT($$AGESEC(DAY,SEC,NOWD,NOWS)>0:1,1:0)
	;
REVOKESID(APP,SID)
	NEW USER
	SET USER=$GET(^MIO("AUTH","SESSION",$GET(APP),$GET(SID),"principal"))
	IF USER'="" KILL ^MIO("AUTH","SESSION","BYUSER",$GET(APP),USER,$GET(SID))
	KILL ^MIO("AUTH","SESSION",$GET(APP),$GET(SID))
	QUIT
	;
ISSUER(APP)
	QUIT $$APPKEY($GET(APP))_"-local-auth"
	;
APPKEY(APP)
	QUIT $$LOW^MIOUTIL($$TRIM^MIOUTIL($GET(APP)))
	;
UPCASE(X)
	NEW Y
	SET Y=$GET(X)
	QUIT $TRANSLATE(Y,"abcdefghijklmnopqrstuvwxyz","ABCDEFGHIJKLMNOPQRSTUVWXYZ")
	;
LOW(X)
	NEW Y
	SET Y=$GET(X)
	QUIT $TRANSLATE(Y,"ABCDEFGHIJKLMNOPQRSTUVWXYZ","abcdefghijklmnopqrstuvwxyz")
	;
AGESEC(D1,S1,D2,S2)
	IF (+$GET(D1)=0),(+$GET(S1)=0) QUIT 999999999
	QUIT (((+$GET(D2)-+$GET(D1))*86400)+(+$GET(S2)-+$GET(S1)))
	;
