MIOIDET ; MIOIDE test runner
	D START Q
	;
START(FAIL)
	N LOCAL,TOP
	S TOP='$D(FAIL),LOCAL=0
	D RUNIF("MIOIDET001",.LOCAL)
	D RUNIF("MIOIDET002",.LOCAL)
	D RUNIF("MIOIDET003",.LOCAL)
	D RUNIF("MIOIDET004",.LOCAL)
	D RUNIF("MIOIDET005",.LOCAL)
	D RUNIF("MIOIDET006",.LOCAL)
	D RUNIF("MIOIDET007",.LOCAL)
	D RUNIF("MIOIDET008",.LOCAL)
	D RUNIF("MIOIDET009",.LOCAL)
	D RUNIF("MIOIDET010",.LOCAL)
	I TOP D  Q
	. I 'LOCAL W !,"OK - MIOIDET"
	I LOCAL S FAIL=1
	Q
	;
RUNIF(RTN,FAIL)
	N X
	I $T(@("START^"_RTN))="" Q
	S X="D START^"_RTN_"(.FAIL)"
	X X
	Q
	;
