MIOIDET ; MIOIDE test runner
	D START Q
	;
START(FAIL)
	N LOCAL,TOP
	S TOP='$D(FAIL),LOCAL=0
	D START^MIOIDET001(.LOCAL)
	D START^MIOIDET002(.LOCAL)
	D START^MIOIDET003(.LOCAL)
	D START^MIOIDET004(.LOCAL)
	I TOP D  Q
	. I 'LOCAL W !,"OK - MIOIDET"
	I LOCAL S FAIL=1
	Q
	;