MIOIDEDBGS ; MIOIDE debugger session store
	Q
	;
ROOT()
	Q $NA(^MIO("MIOIDE","DBG"))
	;
SROOT(SID)
	Q $$ROOT()_",""SESSION"","""_$G(SID)_""""
	;
RESET()
	K ^MIO("MIOIDE","DBG")
	Q
	;
EXISTS(SID)
	Q $D(^MIO("MIOIDE","DBG","SESSION",$G(SID)))>0
	;
INIT(SID,CLIENT,RTN,ENTRY,MAXLINE)
	K ^MIO("MIOIDE","DBG","SESSION",SID)
	S ^MIO("MIOIDE","DBG","SESSION",SID,"sid")=SID
	S ^MIO("MIOIDE","DBG","SESSION",SID,"client")=$G(CLIENT)
	S ^MIO("MIOIDE","DBG","SESSION",SID,"routine")=$G(RTN)
	S ^MIO("MIOIDE","DBG","SESSION",SID,"entry")=$G(ENTRY)
	S ^MIO("MIOIDE","DBG","SESSION",SID,"line")=1
	S ^MIO("MIOIDE","DBG","SESSION",SID,"maxline")=+$G(MAXLINE,1)
	S ^MIO("MIOIDE","DBG","SESSION",SID,"status")="paused"
	S ^MIO("MIOIDE","DBG","SESSION",SID,"reason")="started"
	S ^MIO("MIOIDE","DBG","SESSION",SID,"seq")=0
	S ^MIO("MIOIDE","DBG","SESSION",SID,"createdTs")=$H
	S ^MIO("MIOIDE","DBG","SESSION",SID,"updatedTs")=$H
	Q
	;
SET(SID,KEY,VAL)
	S ^MIO("MIOIDE","DBG","SESSION",SID,KEY)=VAL
	I KEY'="updatedTs" S ^MIO("MIOIDE","DBG","SESSION",SID,"updatedTs")=$H
	Q
	;
GET(SID,KEY)
	Q $G(^MIO("MIOIDE","DBG","SESSION",SID,KEY))
	;
NEXTSEQ(SID)
	N X
	S X=+$G(^MIO("MIOIDE","DBG","SESSION",SID,"seq"))+1
	S ^MIO("MIOIDE","DBG","SESSION",SID,"seq")=X
	S ^MIO("MIOIDE","DBG","SESSION",SID,"updatedTs")=$H
	Q X
	;
STOREEVT(SID,SEQ,TYPE,JSON,CONF)
	N KEEP,ROOT,I,FIRST
	S KEEP=+$G(CONF("mioide","debug","eventRetain"),64)
	S ^MIO("MIOIDE","DBG","SESSION",SID,"EVENT",SEQ,"type")=$G(TYPE)
	S ^MIO("MIOIDE","DBG","SESSION",SID,"EVENT",SEQ,"json")=$G(JSON)
	S ^MIO("MIOIDE","DBG","SESSION",SID,"EVENT",SEQ,"ts")=$H
	S ROOT=$NA(^MIO("MIOIDE","DBG","SESSION",SID,"EVENT"))
	F  Q:$$EVCOUNT(SID)'>KEEP  D
	. S FIRST=$O(^MIO("MIOIDE","DBG","SESSION",SID,"EVENT",0))
	. Q:'FIRST
	. K ^MIO("MIOIDE","DBG","SESSION",SID,"EVENT",FIRST)
	Q
	;
EVCOUNT(SID)
	N I,C S I=0,C=0
	F  S I=$O(^MIO("MIOIDE","DBG","SESSION",SID,"EVENT",I)) Q:'I  S C=C+1
	Q C
	;
SETBP(SID,RTN,LINE,VAL)
	I +$G(VAL) S ^MIO("MIOIDE","DBG","SESSION",SID,"BP",RTN,+LINE)=1 Q
	K ^MIO("MIOIDE","DBG","SESSION",SID,"BP",RTN,+LINE)
	Q
	;
HASBP(SID,RTN,LINE)
	Q +$G(^MIO("MIOIDE","DBG","SESSION",SID,"BP",$G(RTN),+$G(LINE)))
	;
BPARY(SID,OUT)
	N RTN,LINE,IDX
	K OUT S IDX=0,RTN=""
	F  S RTN=$O(^MIO("MIOIDE","DBG","SESSION",SID,"BP",RTN)) Q:RTN=""  D
	. S LINE=0 F  S LINE=$O(^MIO("MIOIDE","DBG","SESSION",SID,"BP",RTN,LINE)) Q:'LINE  D
	. . S IDX=IDX+1
	. . S OUT(IDX,"routine")=RTN
	. . S OUT(IDX,"line")=LINE
	. . S OUT(IDX,"enabled")=1
	Q
	;
ADDWATCH(SID,EXPR)
	N IDX,FOUND
	S EXPR=$G(EXPR)
	S FOUND=$$WATCHIDX(SID,EXPR)
	I FOUND Q FOUND
	S IDX=+$O(^MIO("MIOIDE","DBG","SESSION",SID,"WATCH",""),-1)+1
	S ^MIO("MIOIDE","DBG","SESSION",SID,"WATCH",IDX)=EXPR
	Q IDX
	;
DELWATCH(SID,EXPR)
	N IDX
	S IDX=$$WATCHIDX(SID,$G(EXPR))
	I IDX K ^MIO("MIOIDE","DBG","SESSION",SID,"WATCH",IDX)
	Q IDX
	;
WATCHIDX(SID,EXPR)
	N IDX
	S IDX=0
	F  S IDX=$O(^MIO("MIOIDE","DBG","SESSION",SID,"WATCH",IDX)) Q:'IDX  I $G(^MIO("MIOIDE","DBG","SESSION",SID,"WATCH",IDX))=$G(EXPR) Q
	Q IDX
	;
WATCHARY(SID,OUT)
	N IDX,OIDX,EXPR
	K OUT S IDX=0,OIDX=0
	F  S IDX=$O(^MIO("MIOIDE","DBG","SESSION",SID,"WATCH",IDX)) Q:'IDX  D
	. S EXPR=$G(^MIO("MIOIDE","DBG","SESSION",SID,"WATCH",IDX))
	. I EXPR="" Q
	. S OIDX=OIDX+1
	. S OUT(OIDX,"expr")=EXPR
	. S OUT(OIDX,"idx")=IDX
	Q
	;
DROP(SID)
	K ^MIO("MIOIDE","DBG","SESSION",$G(SID))
	Q
	;
	;