MIOMOSTPIPE ; MIOMOS YottaDB PIPE-backed terminal bridge
	QUIT
	;
OPEN(STATE,CONF,TERMID,OUT,ERR)
	NEW DEVN,ERRN,CMD,SH,IO,USEIND,OPENOK,TRY,CMDS,DETAIL,USEDCMD,OPENTMO,READTMO,USEDERR
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF $GET(TERMID)="" SET TERMID=$GET(^MIO("MIOMOS","PIPE","BYSESSION",$GET(STATE("sessionId"))))
	IF TERMID="" SET TERMID="pipe-"_$$UUID^MIOUTIL()
	IF $DATA(^MIO("MIOMOS","PIPE","SESSION",TERMID,"device")) DO  QUIT 1
	. SET OUT("ok")=1,OUT("opened")=0,OUT("terminalId")=TERMID
	. DO PROFILE(.STATE,.OUT)
	. DO SNAPSHOT(.STATE,TERMID,.OUT)
	SET DEVN=$$DEV(TERMID)
	SET ERRN=$$ERRDEV(TERMID)
	SET SH=$$SHELL(.CONF)
	SET USEIND=+$GET(CONF("miomos","terminal","pipe","independent"),0)
	SET OPENTMO=+$GET(CONF("miomos","terminal","pipe","openTimeout"),1) IF OPENTMO<1 SET OPENTMO=1
	SET READTMO=+$GET(CONF("miomos","terminal","pipe","readTimeout"),1) IF READTMO<1 SET READTMO=1
	DO CMDCANDS(.CONF,.CMDS)
	SET IO=$IO,OPENOK=0,DETAIL="",USEDCMD="",USEDERR=0
	SET TRY=0
	FOR  SET TRY=$ORDER(CMDS(TRY)) QUIT:'TRY  QUIT:OPENOK  DO
	. SET CMD=$GET(CMDS(TRY)) QUIT:CMD=""
	. ; Prefer a simpler no-STDERR open first for better portability.
	. SET OPENOK=$$TRYOPEN(DEVN,ERRN,CMD,SH,USEIND,0,OPENTMO,.DETAIL)
	. IF OPENOK SET USEDCMD=CMD,USEDERR=0 QUIT
	. ; Then try with a dedicated STDERR pipe if supported.
	. SET OPENOK=$$TRYOPEN(DEVN,ERRN,CMD,SH,USEIND,1,OPENTMO,.DETAIL)
	. IF OPENOK SET USEDCMD=CMD,USEDERR=1
	USE IO
	IF 'OPENOK DO  QUIT 0
	. SET ERR("error")="pipe_open_failed"
	. IF DETAIL="" SET DETAIL="no pipe command could be opened"
	. SET ERR("detail")=DETAIL
	SET ^MIO("MIOMOS","PIPE","BYSESSION",$GET(STATE("sessionId")))=TERMID
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"device")=DEVN
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"errdev")=$SELECT(USEDERR:ERRN,1:"")
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"stderrEnabled")=USEDERR
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"command")=USEDCMD
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"shell")=SH
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"principal")=$GET(STATE("principal"))
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"sessionId")=$GET(STATE("sessionId"))
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"createdAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"lastAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"readTimeout")=READTMO
	SET OUT("terminalId")=TERMID
	DO PROFILE(.STATE,.OUT)
	SET OUT("ok")=1,OUT("opened")=1,OUT("terminalId")=TERMID,OUT("transport")="pipe"
	DO POLL(.STATE,TERMID,.OUT,.ERR)
	QUIT 1
	;
ATTACH(STATE,TERMID,OUT,ERR)
	NEW CONF
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF $GET(TERMID)="" SET TERMID=$GET(^MIO("MIOMOS","PIPE","BYSESSION",$GET(STATE("sessionId"))))
	IF TERMID="" QUIT $$OPEN(.STATE,.CONF,TERMID,.OUT,.ERR)
	IF '$$OWNED(.STATE,TERMID,.ERR) QUIT 0
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"lastAt")=$$NOWISO^MIOUTIL()
	SET OUT("terminalId")=TERMID
	DO PROFILE(.STATE,.OUT)
	SET OUT("ok")=1,OUT("attached")=1,OUT("terminalId")=TERMID,OUT("transport")="pipe"
	DO SNAPSHOT(.STATE,TERMID,.OUT)
	QUIT 1
	;
INPUT(STATE,TERMID,LINE,OUT,ERR)
	NEW IO,DEVN
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF '$$OWNED(.STATE,TERMID,.ERR) QUIT 0
	SET DEVN=$GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"device"))
	IF DEVN="" SET ERR("error")="pipe_not_open" QUIT 0
	SET IO=$IO
	USE DEVN WRITE $GET(LINE),! USE IO
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"lastAt")=$$NOWISO^MIOUTIL()
	SET OUT("ok")=1,OUT("terminalId")=TERMID
	DO READIO(TERMID,.OUT)
	QUIT 1
	;
POLL(STATE,TERMID,OUT,ERR)
	KILL ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF '$$OWNED(.STATE,TERMID,.ERR) QUIT 0
	SET OUT("ok")=1,OUT("terminalId")=TERMID
	DO READIO(TERMID,.OUT)
	QUIT 1
	;
RESIZE(STATE,TERMID,COLS,ROWS,OUT,ERR)
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF '$$OWNED(.STATE,TERMID,.ERR) QUIT 0
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"cols")=+$GET(COLS)
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"rows")=+$GET(ROWS)
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"lastAt")=$$NOWISO^MIOUTIL()
	SET OUT("ok")=1,OUT("terminalId")=TERMID,OUT("cols")=+$GET(COLS),OUT("rows")=+$GET(ROWS)
	QUIT 1
	;
CLOSE(STATE,TERMID,OUT,ERR)
	NEW IO,DEVN,ERRN
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF '$$OWNED(.STATE,TERMID,.ERR) QUIT 0
	SET DEVN=$GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"device"))
	SET ERRN=$GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"errdev"))
	SET IO=$IO
	IF ERRN'="" CLOSE ERRN
	IF DEVN'="" CLOSE DEVN
	USE IO
	SET OUT("ok")=1,OUT("closed")=1,OUT("terminalId")=TERMID
	KILL ^MIO("MIOMOS","PIPE","SESSION",TERMID)
	IF $GET(^MIO("MIOMOS","PIPE","BYSESSION",$GET(STATE("sessionId"))))=TERMID KILL ^MIO("MIOMOS","PIPE","BYSESSION",$GET(STATE("sessionId")))
	QUIT 1
	;
SNAPSHOT(STATE,TERMID,OUT)
	DO READIO(TERMID,.OUT)
	SET OUT("transport")="pipe"
	DO PROFILE(.STATE,.OUT)
	QUIT
	;
READIO(TERMID,OUT)
	NEW IO,DEVN,ERRN,LINE,N,TMO,USEERR,$ETRAP,$ESTACK
	SET N=+$GET(OUT("writeCount"))
	SET DEVN=$GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"device"))
	SET ERRN=$GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"errdev"))
	SET USEERR=+$GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"stderrEnabled"),0)
	SET TMO=+$GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"readTimeout"),1) IF TMO<1 SET TMO=1
	SET IO=$IO
	SET $ETRAP="DO READERR^MIOMOSTPIPE(.OUT,.N,IO)"
	IF DEVN'="" DO
	. USE DEVN
	. FOR  READ LINE:TMO QUIT:'$TEST  DO
	. . SET N=N+1,OUT("write",N)=LINE_$CHAR(13,10)
	. USE IO
	IF USEERR,ERRN'="" DO
	. USE ERRN
	. FOR  READ LINE:TMO QUIT:'$TEST  DO
	. . SET N=N+1,OUT("write",N)=LINE_$CHAR(13,10)
	. USE IO
	SET $ETRAP=""
	SET OUT("writeCount")=N
	QUIT
	;
READERR(OUT,N,IO)
	USE IO
	SET OUT("readError")=$ZSTATUS
	SET OUT("writeCount")=+$GET(N)
	SET $ECODE=""
	QUIT
	;
PROFILE(STATE,OUT)
	MERGE OUT("profile")=STATE("terminal")
	SET OUT("profile","transport")="pipe"
	SET OUT("profile","command")=$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(OUT("terminalId")),"command"))
	SET OUT("profile","readTimeout")=$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(OUT("terminalId")),"readTimeout"),1)
	QUIT
	;
OWNED(STATE,TERMID,ERR)
	IF $GET(TERMID)="" SET ERR("error")="terminal_not_found" QUIT 0
	IF '$DATA(^MIO("MIOMOS","PIPE","SESSION",TERMID,"principal")) SET ERR("error")="terminal_not_found" QUIT 0
	IF $GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"principal"))'=$GET(STATE("principal")) SET ERR("error")="terminal_forbidden" QUIT 0
	QUIT 1
	;
DEV(TERMID)
	QUIT "miomospipe-"_$GET(TERMID)
	;
ERRDEV(TERMID)
	QUIT "miomospipeerr-"_$GET(TERMID)
	;
SHELL(CONF)
	NEW X
	SET X=$$TRIM^MIOUTIL($GET(CONF("miomos","terminal","pipe","shell")))
	IF X'="" QUIT X
	QUIT "/bin/sh"
	;
CMDCANDS(CONF,ARR)
	NEW X,D
	KILL ARR
	SET X=$$TRIM^MIOUTIL($GET(CONF("miomos","terminal","pipe","command")))
	DO ADDCMD(.ARR,X)
	SET D=$$TRIM^MIOUTIL($ZTRNLNM("ydb_dist"))
	IF D'="" DO
	. DO ADDCMD(.ARR,D_"/yottadb -direct")
	. DO ADDCMD(.ARR,D_"/yottadb")
	DO ADDCMD(.ARR,"yottadb -direct")
	DO ADDCMD(.ARR,"yottadb")
	DO ADDCMD(.ARR,"ydb")
	QUIT
	;
ADDCMD(ARR,VAL)
	NEW I,N,FOUND
	SET VAL=$$TRIM^MIOUTIL($GET(VAL))
	IF VAL="" QUIT
	SET FOUND=0,I=0
	FOR  SET I=$ORDER(ARR(I)) QUIT:'I  DO  QUIT:FOUND
	. IF $GET(ARR(I))=VAL SET FOUND=1
	IF FOUND QUIT
	SET N=+$ORDER(ARR(""),-1)+1
	SET ARR(N)=VAL
	QUIT
	;
TRYOPEN(DEVN,ERRN,CMD,SH,USEIND,USEERR,OPENTMO,DETAIL)
	NEW IO,OK,$ETRAP,$ESTACK
	SET IO=$IO,DETAIL="",OK=0
	SET $ETRAP="DO OPENERR^MIOMOSTPIPE(.DETAIL,.OK,IO)"
	IF +$GET(USEERR) DO
	. IF +$GET(USEIND) OPEN DEVN:(command=CMD:shell=SH:stderr=ERRN:independent:parse:stream):OPENTMO:"PIPE"
	. ELSE  OPEN DEVN:(command=CMD:shell=SH:stderr=ERRN:parse:stream):OPENTMO:"PIPE"
	ELSE  DO
	. IF +$GET(USEIND) OPEN DEVN:(command=CMD:shell=SH:independent:parse:stream):OPENTMO:"PIPE"
	. ELSE  OPEN DEVN:(command=CMD:shell=SH:parse:stream):OPENTMO:"PIPE"
	USE IO
	SET $ETRAP=""
	IF '$TEST DO  QUIT 0
	. IF DETAIL="" SET DETAIL="command="_CMD_"; shell="_SH_"; timeout="_OPENTMO
	SET OK=1
	QUIT 1
	;
OPENERR(DETAIL,OK,IO)
	USE IO
	SET DETAIL=$ZSTATUS
	SET OK=0
	SET $ECODE=""
	QUIT
