MIOMOSAUTH ; MIOMOS auth/session helpers
	QUIT
	;
PRINCIPAL(CTX)
	NEW SUB,KID
	SET SUB=$GET(CTX("auth","claims","sub"))
	IF SUB'="" QUIT SUB
	SET KID=$GET(CTX("auth","key_id"))
	IF KID'="" QUIT "apikey-"_KID
	IF +$GET(CTX("auth","ok"))=1 QUIT "authenticated"
	QUIT ""
	;
USERNAME(CTX)
	NEW X
	SET X=$GET(CTX("auth","claims","preferred_username")) IF X'="" QUIT X
	SET X=$GET(CTX("auth","claims","name")) IF X'="" QUIT X
	SET X=$GET(CTX("auth","claims","sub")) IF X'="" QUIT X
	SET X=$GET(CTX("auth","key_id")) IF X'="" QUIT "API key "_X
	QUIT "Authenticated user"
	;
ROLECSV(CTX)
	NEW OUT,R
	SET OUT=""
	SET R=""
	FOR  SET R=$ORDER(CTX("auth","roles",R)) QUIT:R=""  DO
	. IF OUT'="" SET OUT=OUT_"," 
	. SET OUT=OUT_R
	IF OUT'="" QUIT OUT
	SET OUT=$GET(CTX("auth","claims","roles"))
	QUIT OUT
	;
HASROLE(CTX,ROLE)
	NEW CSV,I,X,FOUND
	IF $GET(ROLE)="" QUIT 0
	IF +$DATA(CTX("auth","roles",ROLE)) QUIT 1
	SET CSV=$$ROLECSV(.CTX)
	SET FOUND=0
	FOR I=1:1:$LENGTH(CSV,",") DO  QUIT:FOUND
	. SET X=$$TRIM($PIECE(CSV,",",I))
	. IF X=ROLE SET FOUND=1
	QUIT FOUND
	;
ROLEARY(CTX,OUT)
	NEW CSV,I,X,N
	KILL OUT
	SET CSV=$$ROLECSV(.CTX)
	SET N=0
	FOR I=1:1:$LENGTH(CSV,",") DO
	. SET X=$$TRIM($PIECE(CSV,",",I))
	. IF X="" QUIT
	. SET N=N+1,OUT(N)=X
	QUIT
	;
LOCALEN(CONF)
	QUIT +$GET(CONF("miomos","localAuth","enabled"),0)
	;
ALLOWSIGNUP(CONF)
	QUIT +$GET(CONF("miomos","localAuth","allowSignup"),1)
	;
INVITEONLY(CONF)
	QUIT +$GET(CONF("miomos","localAuth","inviteOnly"),0)
	;
COOKIE(REQ,NAME)
	NEW RAW,I,PAIR,K,V
	SET RAW=$GET(REQ("hdr","cookie"))
	IF RAW="" SET RAW=$GET(REQ("hdr","Cookie"))
	IF RAW="" QUIT ""
	FOR I=1:1:$LENGTH(RAW,";") DO  QUIT:$GET(V)'=""
	. SET PAIR=$$TRIM($PIECE(RAW,";",I))
	. SET K=$$TRIM($PIECE(PAIR,"=",1))
	. IF K'=$GET(NAME) QUIT
	. SET V=$PIECE(PAIR,"=",2,999)
	QUIT $GET(V)
	;
LOADLOCAL(CONF,REQ,CTX,ERR)
	NEW TOKEN,USER,DISPLAY,ROLES,NOWD,NOWS,DAY,SEC,MAXAGE
	KILL ERR
	SET ERR("routine")="MIOMOSAUTH"
	SET TOKEN=$$COOKIE(.REQ,$GET(CONF("miomos","localAuth","tokenCookie"),"miomos_auth"))
	IF TOKEN="" SET TOKEN=$GET(REQ("hdr","x-miomos-auth"))
	IF TOKEN="" SET ERR("error")="login_required" QUIT 0
	SET USER=$GET(^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"principal"))
	IF USER="" SET ERR("error")="login_required" QUIT 0
	SET DAY=+$GET(^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"createdDay"))
	SET SEC=+$GET(^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"createdSec"))
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	SET MAXAGE=+$GET(CONF("miomos","localAuth","tokenMaxAgeSeconds"),604800)
	IF $$AGESEC(DAY,SEC,NOWD,NOWS)>MAXAGE DO  QUIT 0
	. KILL ^MIO("MIOMOS","AUTH","TOKEN",TOKEN)
	. SET ERR("error")="login_required"
	IF '$$USEROK(.CONF,USER,.ERR) QUIT 0
	SET DISPLAY=$GET(^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"userName"))
	SET ROLES=$GET(^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"roles"))
	IF DISPLAY="" SET DISPLAY=USER
	KILL CTX("auth")
	SET CTX("auth","ok")=1
	SET CTX("auth","claims","sub")=USER
	SET CTX("auth","claims","name")=DISPLAY
	SET CTX("auth","claims","roles")=ROLES
	DO SETROLES(.CTX,ROLES)
	SET CTX("miomos","authToken")=TOKEN
	SET ^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"lastSeenAt")=$$NOWISO^MIOUTIL()
	QUIT 1
	;
SIGNUP(CONF,USERNAME,PASSWORD,DISPLAY,ROLES,TOKEN,ERR,INVITE)
	NEW USER,SALT,HASH,NOWD,NOWS,INVROLE
	KILL ERR SET TOKEN=""
	SET ERR("routine")="MIOMOSAUTH"
	IF '$$ALLOWSIGNUP(.CONF) SET ERR("error")="signup_disabled" QUIT 0
	SET USER=$$CANON(USERNAME)
	IF '$$VALIDUSER(USER) SET ERR("error")="invalid_username" QUIT 0
	IF $LENGTH($GET(PASSWORD))<8 SET ERR("error")="password_too_short" QUIT 0
	IF $DATA(^MIO("MIOMOS","USER",USER)) SET ERR("error")="user_exists" QUIT 0
	IF $$INVITEONLY(.CONF) DO
	. IF '$$USEINVITE(.CONF,$GET(INVITE),USER,.INVROLE,.ERR) QUIT
	. IF INVROLE'="" SET ROLES=INVROLE
	IF $$INVITEONLY(.CONF),$GET(ERR("error"))'="" QUIT 0
	IF $GET(DISPLAY)="" SET DISPLAY=USER
	IF $GET(ROLES)="" SET ROLES="operator"
	SET SALT=$$UUID^MIOUTIL()
	SET HASH=$$PW(SALT,PASSWORD)
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	SET ^MIO("MIOMOS","USER",USER,"principal")=USER
	SET ^MIO("MIOMOS","USER",USER,"userName")=DISPLAY
	SET ^MIO("MIOMOS","USER",USER,"roles")=ROLES
	SET ^MIO("MIOMOS","USER",USER,"salt")=SALT
	SET ^MIO("MIOMOS","USER",USER,"hash")=HASH
	SET ^MIO("MIOMOS","USER",USER,"enabled")=1
	SET ^MIO("MIOMOS","USER",USER,"failedCount")=0
	SET ^MIO("MIOMOS","USER",USER,"createdAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","USER",USER,"createdDay")=NOWD
	SET ^MIO("MIOMOS","USER",USER,"createdSec")=NOWS
	QUIT $$ISSUETOKEN(.CONF,USER,.TOKEN,.ERR)
	;
SIGNIN(CONF,USERNAME,PASSWORD,TOKEN,ERR)
	NEW USER,SALT,HASH
	KILL ERR SET TOKEN=""
	SET ERR("routine")="MIOMOSAUTH"
	SET USER=$$CANON(USERNAME)
	IF USER="" SET ERR("error")="username_missing" QUIT 0
	IF '$$USEROK(.CONF,USER,.ERR) QUIT 0
	SET SALT=$GET(^MIO("MIOMOS","USER",USER,"salt"))
	SET HASH=$GET(^MIO("MIOMOS","USER",USER,"hash"))
	IF SALT=""!(HASH="") SET ERR("error")="invalid_credentials" QUIT 0
	IF $$PW(SALT,$GET(PASSWORD))'=HASH DO  QUIT 0
	. DO FAILLOGIN(.CONF,USER)
	. SET ERR("error")=$SELECT($$ISLOCKED(USER):"locked_account",1:"invalid_credentials")
	DO CLEARRISK(USER)
	QUIT $$ISSUETOKEN(.CONF,USER,.TOKEN,.ERR)
	;
SIGNOUT(CONF,REQ,CTX)
	NEW TOKEN
	SET TOKEN=$GET(CTX("miomos","authToken"))
	IF TOKEN="" SET TOKEN=$$COOKIE(.REQ,$GET(CONF("miomos","localAuth","tokenCookie"),"miomos_auth"))
	IF TOKEN'="" KILL ^MIO("MIOMOS","AUTH","TOKEN",TOKEN)
	QUIT 1
	;
ISSUETOKEN(CONF,USER,TOKEN,ERR)
	NEW NOWD,NOWS,DISPLAY,ROLES
	KILL ERR SET TOKEN=""
	SET ERR("routine")="MIOMOSAUTH"
	IF '$DATA(^MIO("MIOMOS","USER",USER)) SET ERR("error")="user_not_found" QUIT 0
	IF '$$USEROK(.CONF,USER,.ERR) QUIT 0
	SET TOKEN="miomos-tk-"_$$UUID^MIOUTIL()
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	SET DISPLAY=$GET(^MIO("MIOMOS","USER",USER,"userName"))
	SET ROLES=$GET(^MIO("MIOMOS","USER",USER,"roles"))
	SET ^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"principal")=USER
	SET ^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"userName")=DISPLAY
	SET ^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"roles")=ROLES
	SET ^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"createdAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"createdDay")=NOWD
	SET ^MIO("MIOMOS","AUTH","TOKEN",TOKEN,"createdSec")=NOWS
	QUIT 1
	;
USEROK(CONF,USER,ERR)
	KILL ERR
	SET ERR("routine")="MIOMOSAUTH"
	IF '$DATA(^MIO("MIOMOS","USER",USER)) SET ERR("error")="invalid_credentials" QUIT 0
	IF +$GET(^MIO("MIOMOS","USER",USER,"enabled"),1)'=1 SET ERR("error")="account_disabled" QUIT 0
	IF $$ISLOCKED(USER) SET ERR("error")="locked_account" QUIT 0
	QUIT 1
	;
ISLOCKED(USER)
	NEW NOWD,NOWS,DAY,SEC
	SET DAY=+$GET(^MIO("MIOMOS","USER",USER,"lockedUntilDay"))
	SET SEC=+$GET(^MIO("MIOMOS","USER",USER,"lockedUntilSec"))
	IF DAY=0 QUIT 0
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	IF $$AGESEC(NOWD,NOWS,DAY,SEC)>0 QUIT 1
	KILL ^MIO("MIOMOS","USER",USER,"lockedUntilDay")
	KILL ^MIO("MIOMOS","USER",USER,"lockedUntilSec")
	QUIT 0
	;
FAILLOGIN(CONF,USER)
	NEW FAILS,THRESH,MINS,TOT,DAY,SEC
	SET FAILS=+$GET(^MIO("MIOMOS","USER",USER,"failedCount"))+1
	SET ^MIO("MIOMOS","USER",USER,"failedCount")=FAILS
	SET ^MIO("MIOMOS","USER",USER,"lastFailedAt")=$$NOWISO^MIOUTIL()
	SET THRESH=+$GET(CONF("miomos","localAuth","lockThreshold"),5)
	IF THRESH<1 SET THRESH=5
	IF FAILS<THRESH QUIT
	SET MINS=+$GET(CONF("miomos","localAuth","lockMinutes"),15)
	IF MINS<1 SET MINS=15
	SET TOT=(+$PIECE($HOROLOG,",",1)*86400)+$PIECE($HOROLOG,",",2)+(MINS*60)
	SET DAY=TOT\86400,SEC=TOT#86400
	SET ^MIO("MIOMOS","USER",USER,"lockedUntilDay")=DAY
	SET ^MIO("MIOMOS","USER",USER,"lockedUntilSec")=SEC
	QUIT
	;
CLEARRISK(USER)
	SET ^MIO("MIOMOS","USER",USER,"failedCount")=0
	KILL ^MIO("MIOMOS","USER",USER,"lockedUntilDay")
	KILL ^MIO("MIOMOS","USER",USER,"lockedUntilSec")
	QUIT
	;
DISABLE(USER)
	SET USER=$$CANON(USER) IF USER="" QUIT 0
	IF '$DATA(^MIO("MIOMOS","USER",USER)) QUIT 0
	SET ^MIO("MIOMOS","USER",USER,"enabled")=0
	SET ^MIO("MIOMOS","USER",USER,"disabledAt")=$$NOWISO^MIOUTIL()
	QUIT 1
	;
ENABLE(USER)
	SET USER=$$CANON(USER) IF USER="" QUIT 0
	IF '$DATA(^MIO("MIOMOS","USER",USER)) QUIT 0
	SET ^MIO("MIOMOS","USER",USER,"enabled")=1
	KILL ^MIO("MIOMOS","USER",USER,"disabledAt")
	QUIT 1
	;
LOCK(CONF,USER,MINUTES)
	NEW TOT,DAY,SEC
	SET USER=$$CANON(USER) IF USER="" QUIT 0
	IF '$DATA(^MIO("MIOMOS","USER",USER)) QUIT 0
	SET MINUTES=+$GET(MINUTES) IF MINUTES<1 SET MINUTES=+$GET(CONF("miomos","localAuth","lockMinutes"),15)
	SET TOT=(+$PIECE($HOROLOG,",",1)*86400)+$PIECE($HOROLOG,",",2)+(MINUTES*60)
	SET DAY=TOT\86400,SEC=TOT#86400
	SET ^MIO("MIOMOS","USER",USER,"lockedUntilDay")=DAY
	SET ^MIO("MIOMOS","USER",USER,"lockedUntilSec")=SEC
	QUIT 1
	;
UNLOCK(USER)
	SET USER=$$CANON(USER) IF USER="" QUIT 0
	IF '$DATA(^MIO("MIOMOS","USER",USER)) QUIT 0
	DO CLEARRISK(USER)
	QUIT 1
	;
USERROLES(USER,CSV)
	SET USER=$$CANON(USER) IF USER="" QUIT 0
	IF '$DATA(^MIO("MIOMOS","USER",USER)) QUIT 0
	IF $GET(CSV)="" SET CSV="operator"
	SET ^MIO("MIOMOS","USER",USER,"roles")=CSV
	QUIT 1
	;
REQUESTRESET(CONF,ACTOR,USER,TOKEN,ERR)
	NEW EXPIRES,DAY,SEC
	KILL ERR SET TOKEN=""
	SET ERR("routine")="MIOMOSAUTH"
	SET USER=$$CANON(USER)
	IF USER="" SET ERR("error")="username_missing" QUIT 0
	IF '$DATA(^MIO("MIOMOS","USER",USER)) SET ERR("error")="user_not_found" QUIT 0
	SET TOKEN="miomos-rst-"_$$UUID^MIOUTIL()
	SET EXPIRES=(+$PIECE($HOROLOG,",",1)*86400)+$PIECE($HOROLOG,",",2)+$GET(CONF("miomos","localAuth","resetTokenSeconds"),3600)
	SET DAY=EXPIRES\86400,SEC=EXPIRES#86400
	SET ^MIO("MIOMOS","AUTH","RESET",TOKEN,"principal")=USER
	SET ^MIO("MIOMOS","AUTH","RESET",TOKEN,"createdAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","AUTH","RESET",TOKEN,"createdBy")=$GET(ACTOR)
	SET ^MIO("MIOMOS","AUTH","RESET",TOKEN,"expiresDay")=DAY
	SET ^MIO("MIOMOS","AUTH","RESET",TOKEN,"expiresSec")=SEC
	QUIT 1
	;
APPLYRESET(CONF,TOKEN,NEWPASS,ERR)
	NEW USER,DAY,SEC,NOWD,NOWS
	KILL ERR
	SET ERR("routine")="MIOMOSAUTH"
	IF $LENGTH($GET(NEWPASS))<8 SET ERR("error")="password_too_short" QUIT 0
	SET USER=$GET(^MIO("MIOMOS","AUTH","RESET",TOKEN,"principal"))
	IF USER="" SET ERR("error")="reset_invalid" QUIT 0
	IF $GET(^MIO("MIOMOS","AUTH","RESET",TOKEN,"usedAt"))'="" SET ERR("error")="reset_used" QUIT 0
	SET DAY=+$GET(^MIO("MIOMOS","AUTH","RESET",TOKEN,"expiresDay"))
	SET SEC=+$GET(^MIO("MIOMOS","AUTH","RESET",TOKEN,"expiresSec"))
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	IF $$AGESEC(DAY,SEC,NOWD,NOWS)>0 SET ERR("error")="reset_expired" QUIT 0
	DO SETPW(USER,NEWPASS)
	DO CLEARRISK(USER)
	SET ^MIO("MIOMOS","AUTH","RESET",TOKEN,"usedAt")=$$NOWISO^MIOUTIL()
	QUIT 1
	;
SETPW(USER,PASSWORD)
	NEW SALT,HASH
	SET USER=$$CANON(USER) IF USER="" QUIT
	IF '$DATA(^MIO("MIOMOS","USER",USER)) QUIT
	SET SALT=$$UUID^MIOUTIL()
	SET HASH=$$PW(SALT,PASSWORD)
	SET ^MIO("MIOMOS","USER",USER,"salt")=SALT
	SET ^MIO("MIOMOS","USER",USER,"hash")=HASH
	SET ^MIO("MIOMOS","USER",USER,"passwordChangedAt")=$$NOWISO^MIOUTIL()
	QUIT
	;
CREATEINVITE(CONF,ACTOR,ROLES,LABEL,TOKEN,ERR)
	NEW DAYS,TOT,DAY,SEC
	KILL ERR SET TOKEN=""
	SET ERR("routine")="MIOMOSAUTH"
	SET TOKEN="miomos-inv-"_$$UUID^MIOUTIL()
	IF $GET(ROLES)="" SET ROLES="operator"
	SET DAYS=+$GET(CONF("miomos","localAuth","inviteTokenDays"),7)
	IF DAYS<1 SET DAYS=7
	SET TOT=(+$PIECE($HOROLOG,",",1)*86400)+$PIECE($HOROLOG,",",2)+(DAYS*86400)
	SET DAY=TOT\86400,SEC=TOT#86400
	SET ^MIO("MIOMOS","AUTH","INVITE",TOKEN,"roles")=ROLES
	SET ^MIO("MIOMOS","AUTH","INVITE",TOKEN,"label")=$GET(LABEL)
	SET ^MIO("MIOMOS","AUTH","INVITE",TOKEN,"createdBy")=$GET(ACTOR)
	SET ^MIO("MIOMOS","AUTH","INVITE",TOKEN,"createdAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","AUTH","INVITE",TOKEN,"expiresDay")=DAY
	SET ^MIO("MIOMOS","AUTH","INVITE",TOKEN,"expiresSec")=SEC
	QUIT 1
	;
USEINVITE(CONF,TOKEN,USER,ROLES,ERR)
	NEW DAY,SEC,NOWD,NOWS
	KILL ERR SET ROLES=""
	SET ERR("routine")="MIOMOSAUTH"
	IF $GET(TOKEN)="" SET ERR("error")="invite_required" QUIT 0
	IF $GET(^MIO("MIOMOS","AUTH","INVITE",TOKEN,"usedBy"))'="" SET ERR("error")="invite_used" QUIT 0
	SET ROLES=$GET(^MIO("MIOMOS","AUTH","INVITE",TOKEN,"roles"))
	IF ROLES="" SET ERR("error")="invite_invalid" QUIT 0
	SET DAY=+$GET(^MIO("MIOMOS","AUTH","INVITE",TOKEN,"expiresDay"))
	SET SEC=+$GET(^MIO("MIOMOS","AUTH","INVITE",TOKEN,"expiresSec"))
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	IF $$AGESEC(DAY,SEC,NOWD,NOWS)>0 SET ERR("error")="invite_expired" QUIT 0
	SET ^MIO("MIOMOS","AUTH","INVITE",TOKEN,"usedBy")=$GET(USER)
	SET ^MIO("MIOMOS","AUTH","INVITE",TOKEN,"usedAt")=$$NOWISO^MIOUTIL()
	QUIT 1
	;

SETROLES(CTX,CSV)
	NEW I,X
	FOR I=1:1:$LENGTH($GET(CSV),",") DO
	. SET X=$$TRIM($PIECE(CSV,",",I))
	. IF X'="" SET CTX("auth","roles",X)=1
	QUIT
	;
VALIDUSER(USER)
	NEW I,C,OK
	IF $LENGTH($GET(USER))<3 QUIT 0
	IF $LENGTH($GET(USER))>64 QUIT 0
	SET OK=1
	FOR I=1:1:$LENGTH(USER) DO  QUIT:'OK
	. SET C=$EXTRACT(USER,I)
	. IF (C?1AN)!(C="_")!(C="-")!(C=".") QUIT
	. SET OK=0
	QUIT OK
	;
CANON(USER)
	QUIT $$LOW($$TRIM($GET(USER)))
	;
PW(SALT,PASSWORD)
	QUIT $$SHA256^MIOSHA256($GET(SALT)_":"_$GET(PASSWORD))
	;
AGESEC(D1,S1,D2,S2)
	IF (+$GET(D1)=0),(+$GET(S1)=0) QUIT 999999999
	QUIT (((+$GET(D2)-+$GET(D1))*86400)+(+$GET(S2)-+$GET(S1)))
	;
TRIM(X)
	QUIT $$TRIM^MIOUTIL($GET(X))
	;
LOW(S)
	NEW I,C,OUT
	SET OUT=""
	FOR I=1:1:$LENGTH($GET(S)) DO
	. SET C=$ASCII($EXTRACT(S,I))
	. IF C>64,C<91 SET C=C+32
	. SET OUT=OUT_$CHAR(C)
	QUIT OUT
	;
