MIOMOSOBS ; MIOMOS access/error logging helpers
	QUIT
	;
ACCESS(NAME,CTX,STATE)
	IF '+$GET(STATE("logAccessEnabled"),1) QUIT
	DO PUT("ACCESS",$GET(NAME),"",.CTX,.STATE,"")
	QUIT
	;
ERROR(NAME,CODE,CTX,STATE,DETAIL)
	DO PUT("ERROR",$GET(NAME),$GET(CODE),.CTX,.STATE,$GET(DETAIL))
	QUIT
	;
PUT(TYPE,NAME,CODE,CTX,STATE,DETAIL)
	NEW ID,MAX,NOWD,NOWS,CORR
	SET MAX=+$GET(STATE("logMaxEntries"),500) IF MAX<50 SET MAX=50
	SET ID=$INCREMENT(^MIO("MIOMOS","LOG",TYPE,"SEQ"))
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	SET CORR=$$CORRID(.CTX,.STATE)
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"ts")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"day")=NOWD
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"sec")=NOWS
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"event")=$GET(NAME)
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"code")=$GET(CODE)
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"detail")=$$DETAIL($GET(DETAIL))
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"requestId")=$GET(CTX("request_id"))
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"correlationId")=CORR
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"principal")=$GET(STATE("principal"))
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"sessionId")=$GET(STATE("sessionId"))
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"route")=$GET(CTX("route"))
	SET ^MIO("MIOMOS","LOG",TYPE,ID,"profile")=$GET(STATE("profile"))
	SET ^MIO("MIOMOS","LOG",TYPE,"LAST")=ID
	DO TRIM(TYPE,MAX)
	QUIT
	;
DETAIL(X)
	SET X=$GET(X)
	IF $LENGTH(X)>240 SET X=$EXTRACT(X,1,240)
	QUIT X
	;
CORRID(CTX,STATE)
	NEW X
	SET X=$GET(CTX("request_id")) IF X'="" QUIT X
	SET X=$GET(CTX("miomos","sessionId")) IF X'="" QUIT X
	SET X=$GET(STATE("sessionId")) IF X'="" QUIT X
	QUIT "miomos-corr-unknown"
	;
TRIM(TYPE,MAX)
	NEW LAST,CUT,ID
	SET LAST=+$GET(^MIO("MIOMOS","LOG",TYPE,"LAST"))
	SET CUT=LAST-MAX
	IF CUT<1 QUIT
	FOR ID=1:1:CUT KILL ^MIO("MIOMOS","LOG",TYPE,ID)
	QUIT
	;
TAIL(TYPE,LIMIT,OUT)
	NEW LAST,ID,N
	KILL OUT
	SET TYPE=$$TYPE($GET(TYPE))
	SET LIMIT=+$GET(LIMIT,8) IF LIMIT<1 SET LIMIT=8
	SET LAST=+$GET(^MIO("MIOMOS","LOG",TYPE,"LAST"))
	SET N=0
	FOR ID=LAST:-1:1 QUIT:N'<LIMIT  DO
	. IF '$DATA(^MIO("MIOMOS","LOG",TYPE,ID)) QUIT
	. SET N=N+1
	. DO MERGE1(TYPE,ID,$NAME(OUT(N)))
	QUIT
	;
MERGE1(TYPE,ID,ROOT)
	SET @ROOT@("id")=ID
	SET @ROOT@("ts")=$GET(^MIO("MIOMOS","LOG",TYPE,ID,"ts"))
	SET @ROOT@("event")=$GET(^MIO("MIOMOS","LOG",TYPE,ID,"event"))
	SET @ROOT@("code")=$GET(^MIO("MIOMOS","LOG",TYPE,ID,"code"))
	SET @ROOT@("detail")=$GET(^MIO("MIOMOS","LOG",TYPE,ID,"detail"))
	SET @ROOT@("principal")=$GET(^MIO("MIOMOS","LOG",TYPE,ID,"principal"))
	SET @ROOT@("sessionId")=$GET(^MIO("MIOMOS","LOG",TYPE,ID,"sessionId"))
	SET @ROOT@("route")=$GET(^MIO("MIOMOS","LOG",TYPE,ID,"route"))
	SET @ROOT@("correlationId")=$GET(^MIO("MIOMOS","LOG",TYPE,ID,"correlationId"))
	QUIT
	;
COUNTS(OUT)
	KILL OUT
	SET OUT("access")=$$ACTIVECOUNT("ACCESS")
	SET OUT("error")=$$ACTIVECOUNT("ERROR")
	SET OUT("audit")=0
	IF $TEXT(COUNT^MIOMOSAUD)'="" SET OUT("audit")=$$COUNT^MIOMOSAUD()
	QUIT
	;
ACTIVECOUNT(TYPE)
	NEW ID,N
	SET TYPE=$$TYPE($GET(TYPE))
	SET (ID,N)=0
	FOR  SET ID=$ORDER(^MIO("MIOMOS","LOG",TYPE,ID)) QUIT:ID=""  DO
	. IF +ID'>0 QUIT
	. SET N=N+1
	QUIT N
	;
LASTID(TYPE)
	QUIT +$GET(^MIO("MIOMOS","LOG",$$TYPE($GET(TYPE)),"LAST"))
	;
EXPORT(TYPE,LIMIT,OUT)
	NEW LAST,ID,N
	KILL OUT
	SET TYPE=$$TYPE($GET(TYPE))
	SET LIMIT=+$GET(LIMIT,250) IF LIMIT<1 SET LIMIT=250
	SET LAST=+$GET(^MIO("MIOMOS","LOG",TYPE,"LAST"))
	SET N=0
	FOR ID=LAST:-1:1 QUIT:N'<LIMIT  DO
	. IF '$DATA(^MIO("MIOMOS","LOG",TYPE,ID)) QUIT
	. SET N=N+1
	. DO MERGE1(TYPE,ID,$NAME(OUT(N)))
	DO REVERSE(.OUT)
	QUIT
	;
REVERSE(OUT)
	NEW TMP,N,M
	MERGE TMP=OUT
	KILL OUT
	SET N=0,M=""
	FOR  SET M=$ORDER(TMP(M),-1) QUIT:M=""  DO
	. SET N=N+1
	. MERGE OUT(N)=TMP(M)
	QUIT
	;
SUMMARY(STATE,CONF,OUT)
	NEW CNT,A,E,AT,DT,ALIM,ELIM,DLIM
	KILL OUT
	DO COUNTS(.CNT)
	MERGE OUT("counts")=CNT
	SET ALIM=+$GET(CONF("miomos","log","access","retainDays"),30)
	SET ELIM=+$GET(CONF("miomos","log","error","retainDays"),90)
	SET DLIM=+$GET(CONF("miomos","audit","retainDays"),180)
	SET OUT("retention","accessDays")=ALIM
	SET OUT("retention","errorDays")=ELIM
	SET OUT("retention","auditDays")=DLIM
	SET OUT("retention","maxEntries")=+$GET(CONF("miomos","log","maxEntries"),500)
	SET OUT("retention","exportLimit")=+$GET(CONF("miomos","log","exportLimit"),250)
	SET OUT("correlationMode")="request_id_or_session_id"
	DO TAIL("ACCESS",1,.A) IF $DATA(A(1)) MERGE OUT("lastAccess")=A(1)
	DO TAIL("ERROR",1,.E) IF $DATA(E(1)) MERGE OUT("lastError")=E(1)
	IF $TEXT(TAIL^MIOMOSAUD)'="" DO
	. DO TAIL^MIOMOSAUD(1,.AT)
	. IF $DATA(AT(1)) MERGE OUT("lastAudit")=AT(1)
	SET OUT("profile")=$GET(STATE("profile"))
	SET OUT("sessionId")=$GET(STATE("sessionId"))
	QUIT
	;
PRUNE(TYPE,KEEP,DAYS,OUT)
	NEW NOWD,NOWS,ID,REMOVED,ACTIVE,ROOTDAY,ROOTSEC,EXPIRE
	KILL OUT
	SET TYPE=$$TYPE($GET(TYPE))
	SET KEEP=+$GET(KEEP) IF KEEP<0 SET KEEP=0
	SET DAYS=+$GET(DAYS) IF DAYS<0 SET DAYS=0
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	SET ACTIVE=$$ACTIVECOUNT(TYPE),REMOVED=0
	SET ID=0
	FOR  SET ID=$ORDER(^MIO("MIOMOS","LOG",TYPE,ID)) QUIT:ID=""  DO
	. IF +ID'>0 QUIT
	. SET ROOTDAY=+$GET(^MIO("MIOMOS","LOG",TYPE,ID,"day"))
	. SET ROOTSEC=+$GET(^MIO("MIOMOS","LOG",TYPE,ID,"sec"))
	. SET EXPIRE=0
	. IF DAYS>0,ROOTDAY>0 DO
	. . IF $$AGESEC(ROOTDAY,ROOTSEC,NOWD,NOWS)>(DAYS*86400) SET EXPIRE=1
	. IF 'EXPIRE,ACTIVE'>KEEP QUIT
	. KILL ^MIO("MIOMOS","LOG",TYPE,ID)
	. SET REMOVED=REMOVED+1,ACTIVE=ACTIVE-1
	SET OUT("type")=TYPE
	SET OUT("removed")=REMOVED
	SET OUT("remaining")=ACTIVE
	QUIT
	;
AGESEC(D1,S1,D2,S2)
	IF (+$GET(D1)=0),(+$GET(S1)=0) QUIT 0
	QUIT (((+$GET(D2)-+$GET(D1))*86400)+(+$GET(S2)-+$GET(S1)))
	;
TYPE(TYPE)
	SET TYPE=$ZCONVERT($GET(TYPE),"U")
	IF (TYPE'="ACCESS"),(TYPE'="ERROR") SET TYPE="ACCESS"
	QUIT TYPE
	;
