MIOMOSTPIPE ; MIOMOS websocket-owned YottaDB PIPE terminal
	QUIT
	;
OPEN(STATE,CONF,TERMID,OUT,ERR)
	NEW SID
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	DO LOADTERM^MIOMOSTERM(.STATE,.CONF)
	DO PURGESTALE(.CONF)
	SET SID=$GET(STATE("sessionId"))
	IF SID="" SET ERR("error")="session_missing" QUIT 0
	SET TERMID=$$TERMID($GET(TERMID),SID)
	IF $$SESSIONOK(TERMID,.STATE) DO  QUIT 1
	. DO TOUCH(TERMID,.STATE,"","")
	. DO PROFILE(.STATE,TERMID,.OUT)
	. SET OUT("ok")=1,OUT("opened")=0,OUT("terminalId")=TERMID,OUT("transport")="pipe"
	. DO PAUSE(TERMID)
	. DO DRAIN(TERMID,.OUT,.ERR)
	IF $DATA(^MIO("MIOMOS","PIPE","SESSION",TERMID)) DO CLOSEMETA(TERMID)
	IF '$$OPENP(.CONF,TERMID,.STATE,.ERR) QUIT 0
	DO TOUCH(TERMID,.STATE,"","")
	DO PROFILE(.STATE,TERMID,.OUT)
	SET OUT("ok")=1,OUT("opened")=1,OUT("terminalId")=TERMID,OUT("transport")="pipe"
	DO PAUSE(TERMID)
	DO DRAIN(TERMID,.OUT,.ERR)
	QUIT 1
	;
ATTACH(STATE,TERMID,OUT,ERR)
	NEW CONF
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	DO LOADTERM^MIOMOSTERM(.STATE,.CONF)
	QUIT $$OPEN(.STATE,.CONF,$GET(TERMID),.OUT,.ERR)
	;
INPUT(STATE,TERMID,DATA,OUT,ERR)
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF '$$SESSIONOK($GET(TERMID),.STATE) SET ERR("error")="terminal_not_ready" QUIT 0
	IF '$$WRITEP($GET(TERMID),$GET(DATA),.ERR) QUIT 0
	DO TOUCH($GET(TERMID),.STATE,"","")
	DO PROFILE(.STATE,$GET(TERMID),.OUT)
	SET OUT("ok")=1,OUT("terminalId")=$GET(TERMID),OUT("transport")="pipe"
	DO PAUSE($GET(TERMID))
	DO DRAIN($GET(TERMID),.OUT,.ERR)
	QUIT 1
	;
POLL(STATE,TERMID,OUT,ERR)
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF '$$SESSIONOK($GET(TERMID),.STATE) SET ERR("error")="terminal_not_ready" QUIT 0
	DO TOUCH($GET(TERMID),.STATE,"","")
	DO PROFILE(.STATE,$GET(TERMID),.OUT)
	SET OUT("ok")=1,OUT("terminalId")=$GET(TERMID),OUT("transport")="pipe"
	DO DRAIN($GET(TERMID),.OUT,.ERR)
	QUIT 1
	;
RESIZE(STATE,TERMID,COLS,ROWS,OUT,ERR)
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF '$$SESSIONOK($GET(TERMID),.STATE) SET ERR("error")="terminal_not_ready" QUIT 0
	DO TOUCH($GET(TERMID),.STATE,+$GET(COLS),+$GET(ROWS))
	DO PROFILE(.STATE,$GET(TERMID),.OUT)
	SET OUT("ok")=1,OUT("terminalId")=$GET(TERMID),OUT("transport")="pipe"
	SET OUT("cols")=+$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"cols"))
	SET OUT("rows")=+$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"rows"))
	QUIT 1
	;
CLOSE(STATE,TERMID,OUT,ERR)
	NEW DEV
	KILL OUT,ERR
	SET ERR("routine")="MIOMOSTPIPE"
	IF '$$ACCESSOK($GET(TERMID),.STATE) SET ERR("error")="terminal_not_found" QUIT 0
	SET DEV=$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"device"))
	IF +$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"job"))=$JOB,DEV'="" DO
	. USE $PRINCIPAL
	. CLOSE DEV
	DO CLOSEMETA($GET(TERMID))
	SET OUT("ok")=1,OUT("closed")=1,OUT("terminalId")=$GET(TERMID),OUT("transport")="pipe"
	QUIT 1
	;
OPENP(CONF,TERMID,STATE,ERR)
	NEW DEV,CMD,SH,COLS,ROWS
	KILL ERR
	SET ERR("routine")="MIOMOSTPIPE"
	SET DEV=$$DEVNAME($GET(TERMID))
	SET CMD=$$CMD(.CONF)
	SET SH=$$SHELL(.CONF)
	SET COLS=$$COLS(+$GET(STATE("terminal","cols")))
	SET ROWS=$$ROWS(+$GET(STATE("terminal","rows")))
	IF SH'="" DO
	. OPEN DEV:(COMMAND=CMD:SHELL=SH)::"PIPE"
	ELSE  DO
	. OPEN DEV:(COMMAND=CMD)::"PIPE"
	IF '$TEST DO  QUIT 0
	. SET ERR("error")="pipe_open_failed"
	. SET ERR("detail")=CMD
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"open")=1
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"device")=DEV
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"principal")=$GET(STATE("principal"))
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"userName")=$GET(STATE("userName"))
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"sessionId")=$GET(STATE("sessionId"))
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"job")=$JOB
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"command")=CMD
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"shell")=SH
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"cols")=COLS
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"rows")=ROWS
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"transport")="pipe"
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"readLimit")=$$READLIM(.CONF)
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"readPolls")=$$READPOLLS(.CONF)
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"drainPause")=$$DRAINPAUSE(.CONF)
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"openedAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","PIPE","BYSESSION",$GET(STATE("sessionId")))=TERMID
	QUIT 1
	;
WRITEP(TERMID,DATA,ERR)
	NEW DEV,$ETRAP,$ESTACK,FAIL
	KILL ERR
	SET ERR("routine")="MIOMOSTPIPE"
	SET DEV=$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"device"))
	IF DEV="" SET ERR("error")="device_missing" QUIT 0
	SET FAIL=0
	SET $ETRAP="DO WTRAP^MIOMOSTPIPE(.FAIL,.ERR) QUIT"
	USE DEV WRITE $GET(DATA)
	USE $PRINCIPAL
	SET $ETRAP=""
	IF FAIL QUIT 0
	QUIT 1
	;
DRAIN(TERMID,OUT,ERR)
	NEW DEV,TXT,LIMIT,SPINS,I,CH,$ETRAP,$ESTACK,FAIL
	KILL ERR
	SET ERR("routine")="MIOMOSTPIPE"
	SET DEV=$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"device"))
	IF DEV="" QUIT
	SET LIMIT=+$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"readLimit"),16384)
	SET SPINS=+$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"readPolls"),8)
	IF LIMIT<1 SET LIMIT=16384
	IF SPINS<1 SET SPINS=1
	SET TXT="",FAIL=0
	SET $ETRAP="DO RTRAP^MIOMOSTPIPE(.FAIL,.ERR) QUIT"
	USE DEV
	FOR I=1:1:SPINS QUIT:$LENGTH(TXT)'<LIMIT  DO  QUIT:'$TEST
	. READ *CH:0
	. QUIT:'$TEST
	. SET TXT=TXT_$CHAR(CH)
	. FOR  READ *CH:0 QUIT:'$TEST  QUIT:$LENGTH(TXT)'<LIMIT  SET TXT=TXT_$CHAR(CH)
	USE $PRINCIPAL
	SET $ETRAP=""
	IF FAIL QUIT
	IF TXT'="" SET OUT("write",1)=TXT,OUT("writeCount")=1
	ELSE  SET OUT("writeCount")=0
	QUIT
	;
PURGESTALE(CONF)
	NEW TERMID,IDLE,LASTH
	SET IDLE=$$IDLE(.CONF)
	SET TERMID=""
	FOR  SET TERMID=$ORDER(^MIO("MIOMOS","PIPE","SESSION",TERMID)) QUIT:TERMID=""  DO
	. SET LASTH=$GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"lastSeenHorolog"))
	. IF LASTH="" SET LASTH=$HOROLOG
	. IF $$AGESECS(LASTH)'>IDLE QUIT
	. DO CLOSEMETA(TERMID)
	QUIT
	;
SESSIONOK(TERMID,STATE)
	IF '$$ACCESSOK($GET(TERMID),.STATE) QUIT 0
	IF '$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"open")) QUIT 0
	IF $GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"device"))="" QUIT 0
	IF +$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"job"))'=$JOB QUIT 0
	QUIT 1
	;
ACCESSOK(TERMID,STATE)
	IF $GET(TERMID)="" QUIT 0
	IF '$DATA(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"principal")) QUIT 0
	IF $GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"principal"))'=$GET(STATE("principal")) QUIT 0
	QUIT 1
	;
TOUCH(TERMID,STATE,COLS,ROWS)
	QUIT:$GET(TERMID)=""
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"lastSeenAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"lastSeenHorolog")=$HOROLOG
	IF $GET(STATE("principal"))'="" SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"principal")=$GET(STATE("principal"))
	IF $GET(STATE("userName"))'="" SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"userName")=$GET(STATE("userName"))
	IF $GET(STATE("sessionId"))'="" DO
	. SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"sessionId")=$GET(STATE("sessionId"))
	. SET ^MIO("MIOMOS","PIPE","BYSESSION",$GET(STATE("sessionId")))=TERMID
	IF +$GET(COLS)>0 SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"cols")=$$COLS(+$GET(COLS))
	IF +$GET(ROWS)>0 SET ^MIO("MIOMOS","PIPE","SESSION",TERMID,"rows")=$$ROWS(+$GET(ROWS))
	QUIT
	;
PROFILE(STATE,TERMID,OUT)
	MERGE OUT("profile")=STATE("terminal")
	SET OUT("profile","transport")="pipe"
	SET OUT("profile","command")=$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"command"))
	SET OUT("profile","shell")=$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"shell"))
	SET OUT("profile","cols")=+$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"cols"),+$GET(STATE("terminal","cols")))
	SET OUT("profile","rows")=+$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"rows"),+$GET(STATE("terminal","rows")))
	QUIT
	;
PAUSE(TERMID)
	NEW SECS
	SET SECS=+$GET(^MIO("MIOMOS","PIPE","SESSION",$GET(TERMID),"drainPause"),.04)
	IF SECS'>0 SET SECS=.04
	H SECS
	QUIT
	;
CLOSEMETA(TERMID)
	NEW SID
	QUIT:$GET(TERMID)=""
	SET SID=$GET(^MIO("MIOMOS","PIPE","SESSION",TERMID,"sessionId"))
	KILL ^MIO("MIOMOS","PIPE","SESSION",TERMID)
	IF SID'="",($GET(^MIO("MIOMOS","PIPE","BYSESSION",SID))=TERMID) KILL ^MIO("MIOMOS","PIPE","BYSESSION",SID)
	QUIT
	;
WTRAP(FAIL,ERR)
	USE $PRINCIPAL
	SET FAIL=1
	SET ERR("error")="pipe_write_failed"
	SET ERR("detail")=$ZSTATUS
	SET $ECODE=""
	QUIT
	;
RTRAP(FAIL,ERR)
	USE $PRINCIPAL
	SET FAIL=1
	SET ERR("error")="pipe_read_failed"
	SET ERR("detail")=$ZSTATUS
	SET $ECODE=""
	QUIT
	;
TERMID(VAL,SID)
	NEW X
	SET X=$$TRIM^MIOUTIL($GET(VAL))
	IF X'="" QUIT X
	SET X=$GET(^MIO("MIOMOS","PIPE","BYSESSION",$GET(SID)))
	IF X'="" QUIT X
	QUIT "pipe-"_$$UUID^MIOUTIL()
	;
DEVNAME(TERMID)
	QUIT "|MIOMOS-PIPE-"_$JOB_"-"_$GET(TERMID)
	;
CMD(CONF)
	NEW X,D
	SET X=$$TRIM^MIOUTIL($GET(CONF("miomos","terminal","pipe","command")))
	IF X'="" QUIT X
	SET D=$$TRIM^MIOUTIL($ZTRNLNM("ydb_dist"))
	IF D'="" QUIT D_"/yottadb -direct"
	QUIT "yottadb -direct"
	;
SHELL(CONF)
	NEW X
	SET X=$$TRIM^MIOUTIL($GET(CONF("miomos","terminal","pipe","shell")))
	QUIT X
	;
READLIM(CONF)
	NEW N
	SET N=+$GET(CONF("miomos","terminal","pipe","readLimit"),16384)
	IF N<1024 SET N=16384
	QUIT N
	;
READPOLLS(CONF)
	NEW N
	SET N=+$GET(CONF("miomos","terminal","pipe","readPolls"),8)
	IF N<1 SET N=8
	QUIT N
	;
DRAINPAUSE(CONF)
	NEW N
	SET N=+$GET(CONF("miomos","terminal","pipe","drainPause"),.04)
	IF N'>0 SET N=.04
	QUIT N
	;
IDLE(CONF)
	NEW N
	SET N=+$GET(CONF("miomos","terminal","pipe","sessionIdleSeconds"),900)
	IF N<60 SET N=900
	QUIT N
	;
COLS(N)
	IF N<80 QUIT 80
	IF N>220 QUIT 220
	QUIT N
	;
ROWS(N)
	IF N<20 QUIT 20
	IF N>60 QUIT 60
	QUIT N
	;
AGESECS(H)
	QUIT $$HSECS($HOROLOG)-$$HSECS($GET(H))
	;
HSECS(H)
	NEW D,S
	SET D=+$PIECE($GET(H),",",1)
	SET S=+$PIECE($GET(H),",",2)
	QUIT (D*86400)+S
	;
