MIOMIDERT ; MIOIDE routine and execution helpers
	QUIT
	;
LIST(CONF,OUT,ERR)
	NEW %ZR,NAME,I,PAT
	KILL OUT,ERR,%ZR
	SET ERR("routine")="MIOMIDERT"
	SET PAT=$GET(CONF("miomide","routinePattern"),"*")
	DO SILENT^%RSEL(PAT,"CALL")
	SET NAME="",I=0
	FOR  SET NAME=$ORDER(%ZR(NAME)) QUIT:NAME=""  DO
	. SET I=I+1
	. SET OUT(I,"name")=NAME
	. SET OUT(I,"type")="routine"
	. SET OUT(I,"path")=$$PATH(.CONF,NAME)
	SET OUT("count")=I
	QUIT 1
	;
LOAD(CONF,NAME,OUT,ERR)
	NEW PATH,LINES
	KILL OUT,ERR
	SET ERR("routine")="MIOMIDERT"
	IF '$$VALIDRTN(NAME,.ERR) QUIT 0
	SET PATH=$$PATH(.CONF,NAME)
	IF '$$READFILE^MIOUTIL(PATH,.LINES,.ERR) SET ERR("error")="load_failed",ERR("detail")=$GET(ERR("error")) QUIT 0
	SET OUT("ok")=1
	SET OUT("name")=NAME
	SET OUT("path")=PATH
	SET OUT("lineCount")=$$LINECOUNT(.LINES)
	SET OUT("byteCount")=$$BYTECOUNT(.LINES)
	SET OUT("checksum")=$$CHECKSUM(.LINES)
	MERGE OUT("sourceLines")=LINES
	QUIT 1
	;
SAVEARR(CONF,NAME,LINES,OUT,ERR)
	NEW PATH,I,NEXT,LINE
	KILL OUT,ERR
	SET ERR("routine")="MIOMIDERT"
	IF '$$VALIDRTN(NAME,.ERR) QUIT 0
	SET PATH=$$PATH(.CONF,NAME)
	OPEN PATH:(newversion:stream:nowrap):2 ELSE  DO  QUIT 0
	. SET ERR("error")="open_failed"
	. SET ERR("detail")=PATH
	USE PATH
	SET I=""
	FOR  SET I=$ORDER(LINES(I)) QUIT:I=""  DO
	. SET LINE=$$STRIPCR($GET(LINES(I)))
	. WRITE LINE
	. SET NEXT=$ORDER(LINES(I))
	. IF NEXT'="" WRITE !
	CLOSE PATH
	USE $PRINCIPAL
	SET OUT("ok")=1
	SET OUT("name")=NAME
	SET OUT("savedAt")=$$NOWISO^MIOUTIL()
	SET OUT("path")=PATH
	SET OUT("lineCount")=$$LINECOUNT(.LINES)
	SET OUT("byteCount")=$$BYTECOUNT(.LINES)
	SET OUT("checksum")=$$CHECKSUM(.LINES)
	QUIT 1
	;
COMPILE(CONF,NAME,OUT,ERR)
	NEW $ETRAP,$ESTACK,STATUS,FAIL
	KILL OUT,ERR
	SET ERR("routine")="MIOMIDERT"
	IF '$$VALIDRTN(NAME,.ERR) QUIT 0
	SET STATUS="",FAIL=0
	SET $ETRAP="SET FAIL=1,STATUS=$ZSTATUS SET $ECODE="""" QUIT"
	VIEW "LINK":"RECURSIVE"
	XECUTE "ZLINK "_NAME
	SET $ETRAP=""
	IF FAIL DO  QUIT 0
	. SET ERR("error")="compile_failed"
	. SET ERR("detail")=STATUS
	. DO STATUSPROB(STATUS,.OUT)
	SET OUT("ok")=1
	SET OUT("name")=NAME
	SET OUT("compiledAt")=$$NOWISO^MIOUTIL()
	SET OUT("status")="compiled"
	SET OUT("problemCount")=0
	QUIT 1
	;
RUN(CONF,NAME,OUT,ERR)
	NEW CMD,DEV,LINE,I
	KILL OUT,ERR
	SET ERR("routine")="MIOMIDERT"
	IF '$$VALIDRTN(NAME,.ERR) QUIT 0
	SET CMD=$GET(CONF("miomide","run","command"),"ydb -run")_" "_NAME
	SET DEV="|MIOIDE-RUN-"_$JOB
	OPEN DEV:(COMMAND=CMD:READONLY)::"PIPE" ELSE  DO  QUIT 0
	. SET ERR("error")="pipe_open_failed"
	USE DEV
	SET I=0
	FOR  READ LINE QUIT:$ZEOF  DO
	. SET I=I+1
	. SET OUT("lines",I)=LINE
	CLOSE DEV
	USE $PRINCIPAL
	SET OUT("ok")=1
	SET OUT("name")=NAME
	SET OUT("lineCount")=I
	SET OUT("status")="finished"
	SET OUT("output")=$$LINESJOIN(.OUT)
	QUIT 1
	;
SEARCH(CONF,TERM,OUT,ERR)
	NEW LIST,NAME,I,LIMIT,COUNT,LINES,LN,TERMLOW,LINE,LOADERR
	KILL OUT,ERR
	SET ERR("routine")="MIOMIDERT"
	SET TERM=$GET(TERM)
	IF TERM="" SET ERR("error")="term_missing" QUIT 0
	SET LIMIT=+$GET(CONF("miomide","search","limit"),50) IF LIMIT<1 SET LIMIT=50
	SET TERMLOW=$$LC^MIOUTIL(TERM)
	IF '$$LIST(.CONF,.LIST,.ERR) QUIT 0
	SET COUNT=0
	FOR I=1:1:+$GET(LIST("count")) QUIT:COUNT'<LIMIT  DO
	. SET NAME=$GET(LIST(I,"name")) QUIT:NAME=""
	. KILL LINES,LOADERR
	. IF '$$READFILE^MIOUTIL($$PATH(.CONF,NAME),.LINES,.LOADERR) QUIT
	. SET LN=0
	. FOR  SET LN=$ORDER(LINES(LN)) QUIT:LN=""  QUIT:COUNT'<LIMIT  DO
	. . SET LINE=$GET(LINES(LN))
	. . IF $$LC^MIOUTIL(LINE)'[TERMLOW QUIT
	. . SET COUNT=COUNT+1
	. . SET OUT(COUNT,"routine")=NAME
	. . SET OUT(COUNT,"line")=+LN
	. . SET OUT(COUNT,"preview")=$EXTRACT(LINE,1,240)
	SET OUT("count")=COUNT
	SET OUT("term")=TERM
	QUIT 1
	;
GLOBALS(CONF,ROOT,MAX,OUT,ERR)
	NEW NODE,CNT,VAL
	KILL OUT,ERR
	SET ERR("routine")="MIOMIDERT"
	SET ROOT=$GET(ROOT)
	IF ROOT="" SET ROOT="^MIO"
	IF $EXTRACT(ROOT,1)'="^" SET ERR("error")="invalid_global_root" QUIT 0
	SET MAX=+$GET(MAX) IF MAX<1 SET MAX=+$GET(CONF("miomide","globals","limit"),100)
	SET NODE=ROOT,CNT=0
	IF $DATA(@NODE)#2 DO
	. SET CNT=CNT+1
	. SET OUT(CNT,"node")=NODE
	. SET OUT(CNT,"value")=$EXTRACT($GET(@NODE),1,240)
	FOR  SET NODE=$QUERY(@NODE) QUIT:NODE=""  QUIT:$EXTRACT(NODE,1,$LENGTH(ROOT))'=ROOT  QUIT:CNT'<MAX  DO
	. SET CNT=CNT+1
	. SET VAL=$GET(@NODE)
	. SET OUT(CNT,"node")=NODE
	. SET OUT(CNT,"value")=$EXTRACT(VAL,1,240)
	SET OUT("count")=CNT
	SET OUT("root")=ROOT
	QUIT 1
	;
DEBUGSNAP(CONF,NAME,OUT,ERR)
	KILL OUT,ERR
	SET ERR("routine")="MIOMIDERT"
	SET OUT("ok")=1
	SET OUT("name")=$GET(NAME)
	SET OUT("status")="planned"
	SET OUT("message")="Debugger transport and breakpoint engine are scaffolded for a later ROI."
	QUIT 1
	;
PATH(CONF,NAME)
	QUIT $GET(CONF("miomide","routineDir"),"routines")_"/"_$$FILEBASE(NAME)_".m"
	;
FILEBASE(NAME)
	NEW BASE
	SET BASE=$GET(NAME)
	IF $EXTRACT(BASE,1)="%" SET $EXTRACT(BASE,1)="_"
	QUIT BASE
	;
VALIDRTN(NAME,ERR)
	NEW I,C
	IF $GET(NAME)="" SET ERR("error")="routine_missing" QUIT 0
	IF $EXTRACT(NAME,1)'?1A,($EXTRACT(NAME,1)'="%") SET ERR("error")="routine_invalid" QUIT 0
	FOR I=2:1:$LENGTH(NAME) DO  QUIT:$GET(ERR("error"))'=""
	. SET C=$EXTRACT(NAME,I)
	. IF '(C?1AN) SET ERR("error")="routine_invalid"
	IF $GET(ERR("error"))'="" QUIT 0
	QUIT 1
	;
STATUSPROB(STATUS,OUT)
	NEW LOC,CODE,DETAIL,RTN,LINE
	SET LOC=$PIECE($GET(STATUS),",",2)
	SET CODE=$PIECE($GET(STATUS),",",3)
	SET DETAIL=$PIECE($GET(STATUS),",",4,99)
	SET RTN=$$STATUSRTN(LOC)
	SET LINE=$$STATUSLINE(LOC)
	SET OUT("ok")=0
	SET OUT("status")="compile_failed"
	SET OUT("problemCount")=1
	SET OUT("summary")="Compile failed"
	SET OUT("problems",1,"severity")="error"
	SET OUT("problems",1,"code")=CODE
	SET OUT("problems",1,"message")=$SELECT(DETAIL'="":DETAIL,1:CODE)
	SET OUT("problems",1,"detail")=$GET(STATUS)
	IF RTN'="" SET OUT("problems",1,"routine")=RTN
	IF LINE'="" SET OUT("problems",1,"line")=LINE
	QUIT
	;
STATUSRTN(LOC)
	QUIT $PIECE($GET(LOC),"^",2)
	;
STATUSLINE(LOC)
	NEW PART
	SET PART=$PIECE($PIECE($GET(LOC),"^",1),"+",2)
	IF PART'?1.N QUIT ""
	QUIT +PART
	;
LINECOUNT(LINES)
	NEW I,CNT
	SET I="",CNT=0
	FOR  SET I=$ORDER(LINES(I)) QUIT:I=""  SET CNT=CNT+1
	QUIT CNT
	;
BYTECOUNT(LINES)
	NEW I,CNT,NEXT
	SET I="",CNT=0
	FOR  SET I=$ORDER(LINES(I)) QUIT:I=""  DO
	. SET CNT=CNT+$LENGTH($GET(LINES(I)))
	. SET NEXT=$ORDER(LINES(I))
	. IF NEXT'="" SET CNT=CNT+1
	QUIT CNT
	;
CHECKSUM(LINES)
	NEW I,J,SUM,LINE
	SET I="",SUM=0
	FOR  SET I=$ORDER(LINES(I)) QUIT:I=""  DO
	. SET LINE=$GET(LINES(I))
	. FOR J=1:1:$LENGTH(LINE) SET SUM=((SUM*33)+$ASCII(LINE,J))#2147483647
	. SET SUM=((SUM*33)+10)#2147483647
	QUIT $$DEC2HEX^MIOUTIL(SUM,8)
	;
STRIPCR(X)
	IF $EXTRACT($GET(X),$LENGTH($GET(X)))=$CHAR(13) QUIT $EXTRACT(X,1,$LENGTH(X)-1)
	QUIT $GET(X)
	;
LINESJOIN(OUT)
	NEW I,TXT
	SET I="",TXT=""
	FOR  SET I=$ORDER(OUT("lines",I)) QUIT:I=""  DO
	. IF TXT'="" SET TXT=TXT_$CHAR(10)
	. SET TXT=TXT_$GET(OUT("lines",I))
	QUIT TXT
	;
JOIN(ROOT,SUB)
	NEW I,TXT
	SET I="",TXT=""
	FOR  SET I=$ORDER(@ROOT@(SUB,I)) QUIT:I=""  DO
	. IF TXT'="" SET TXT=TXT_$CHAR(10)
	. SET TXT=TXT_$GET(@ROOT@(SUB,I))
	QUIT TXT
