MIOMIDETM ; MIOIDE terminal websocket bridge
	QUIT
	;
MESSAGE(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,TREE,EVT,SID,INFO
	SET CTX("ws","keep_open")=1
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO SENDTEXT^MIOWS(.DEV,$$ERRJSON("login_required",$GET(ERR("error"))))
	DO PURGESTALE(.CONF)
	SET EVT=$$EVENT($GET(CTX("payload")),.TREE)
	IF EVT="" DO  QUIT
	. DO SENDTEXT^MIOWS(.DEV,$$ERRJSON("unsupported_event",""))
	IF EVT="hello"!(EVT="init") DO  QUIT
	. SET SID=$$HELLOSES(.CONF,.STATE,.TREE,.INFO,.ERR)
	. IF SID="" DO SENDTEXT^MIOWS(.DEV,$$ERRJSON($GET(ERR("error"),"session_open_failed"),$GET(ERR("detail")))) QUIT
	. H +$GET(CONF("miomide","terminal","drainPause"),.04)
	. DO DRAIN(.CONF,SID,.INFO,.ERR)
	. DO SENDTEXT^MIOWS(.DEV,$$READY(.CONF,SID,.STATE,.TREE,.INFO))
	IF EVT="input" DO  QUIT
	. SET SID=$$SESSION(.STATE,.TREE)
	. IF SID="" DO SENDTEXT^MIOWS(.DEV,$$ERRJSON("session_missing","input")) QUIT
	. IF '$$SESSIONOK(SID,.STATE) DO  QUIT
	. . SET SID=$$HELLOSES(.CONF,.STATE,.TREE,.INFO,.ERR)
	. . IF SID="" DO SENDTEXT^MIOWS(.DEV,$$ERRJSON($GET(ERR("error"),"session_open_failed"),$GET(ERR("detail")))) QUIT
	. DO TOUCH(SID,.STATE,.TREE)
	. IF '$$WRITEP(SID,$GET(TREE("data")),.ERR) DO SENDTEXT^MIOWS(.DEV,$$ERRJSON($GET(ERR("error"),"write_failed"),$GET(ERR("detail")))) QUIT
	. H +$GET(CONF("miomide","terminal","drainPause"),.04)
	. DO DRAIN(.CONF,SID,.INFO,.ERR)
	. DO SENDTEXT^MIOWS(.DEV,$$DATA(SID,.INFO))
	IF EVT="resize" DO  QUIT
	. SET SID=$$SESSION(.STATE,.TREE)
	. IF SID="" DO SENDTEXT^MIOWS(.DEV,$$ERRJSON("session_missing","resize")) QUIT
	. DO TOUCH(SID,.STATE,.TREE)
	. DO SENDTEXT^MIOWS(.DEV,$$ACK("resize",SID,$GET(^MIO("MIOMIDE","TERM","SID",SID,"cols"))_"x"_$GET(^MIO("MIOMIDE","TERM","SID",SID,"rows"))))
	IF EVT="ping"!(EVT="drain") DO  QUIT
	. SET SID=$$SESSION(.STATE,.TREE)
	. IF SID'="" DO  QUIT
	. . DO TOUCH(SID,.STATE,.TREE)
	. . DO DRAIN(.CONF,SID,.INFO,.ERR)
	. . IF $GET(INFO("data"))'="" DO SENDTEXT^MIOWS(.DEV,$$DATA(SID,.INFO))
	. . DO SENDTEXT^MIOWS(.DEV,$$PONG(SID))
	. DO SENDTEXT^MIOWS(.DEV,$$PONG(""))
	IF EVT="close"!(EVT="terminate") DO  QUIT
	. SET SID=$$SESSION(.STATE,.TREE)
	. IF SID'="" DO CLOSESID(SID)
	. DO SENDTEXT^MIOWS(.DEV,$$CLOSED(SID))
	DO SENDTEXT^MIOWS(.DEV,$$ERRJSON("unsupported_event",EVT))
	QUIT
	;
EVENT(PAY,TREE)
	NEW ERR,EVT
	KILL TREE
	SET EVT=""
	IF $GET(PAY)="" QUIT EVT
	IF $EXTRACT(PAY,1)="{" DO  QUIT $GET(TREE("event"))
	. IF '$$DECODE^MIOJSON($GET(PAY),.TREE,.ERR) QUIT
	IF PAY="hello" QUIT "hello"
	IF PAY="ping" QUIT "ping"
	QUIT EVT
	;
HELLOSES(CONF,STATE,TREE,INFO,ERR)
	NEW SID,CLIENTID,REUSED
	KILL INFO,ERR
	SET ERR("routine")="MIOMIDETM"
	SET CLIENTID=$$CLIENTID(.TREE,.STATE)
	IF CLIENTID="" SET ERR("error")="client_id_missing" QUIT ""
	SET TREE("clientId")=CLIENTID
	SET SID=$$SESSION(.STATE,.TREE)
	SET REUSED=0
	IF SID'="",$$SESSIONOK(SID,.STATE) SET REUSED=1
	IF SID'="",'REUSED DO CLOSEMETA(SID)
	IF SID="" SET SID=$$NEWSID(.STATE,CLIENTID)
	IF '$$OPENP(.CONF,SID,.STATE,.TREE,.ERR) QUIT ""
	DO TOUCH(SID,.STATE,.TREE)
	SET INFO("reused")=REUSED
	SET INFO("sessionId")=SID
	SET INFO("clientId")=CLIENTID
	QUIT SID
	;
SESSION(STATE,TREE)
	NEW SID,CLIENTID
	SET SID=$GET(TREE("sessionId"))
	IF SID="" SET SID=$GET(TREE("sid"))
	IF SID'="" QUIT SID
	SET CLIENTID=$$CLIENTID(.TREE,.STATE)
	IF CLIENTID="" QUIT ""
	QUIT $$LOOKUPSID($GET(STATE("principal")),CLIENTID)
	;
CLIENTID(TREE,STATE)
	NEW CLIENTID
	SET CLIENTID=$GET(TREE("clientId"))
	IF CLIENTID'="" QUIT CLIENTID
	SET CLIENTID=$GET(TREE("terminalClientId"))
	IF CLIENTID'="" QUIT CLIENTID
	QUIT "term-"_$$SAFE($GET(STATE("principal")))
	;
NEWSID(STATE,CLIENTID)
	QUIT $$SAFE($GET(STATE("principal")))_"-"_$$SAFE(CLIENTID)
	;
LOOKUPSID(PRINCIPAL,CLIENTID)
	QUIT $GET(^MIO("MIOMIDE","TERM","CLIENT",$GET(PRINCIPAL),$GET(CLIENTID)))
	;
SESSIONOK(SID,STATE)
	NEW PRINCIPAL
	SET PRINCIPAL=$GET(^MIO("MIOMIDE","TERM","SID",SID,"principal"))
	IF $GET(SID)="" QUIT 0
	IF PRINCIPAL="" QUIT 0
	IF PRINCIPAL'=$GET(STATE("principal")) QUIT 0
	IF '$GET(^MIO("MIOMIDE","TERM","SID",SID,"open")) QUIT 0
	IF $GET(^MIO("MIOMIDE","TERM","SID",SID,"device"))="" QUIT 0
	IF +$GET(^MIO("MIOMIDE","TERM","SID",SID,"job"))'=$JOB QUIT 0
	QUIT 1
	;
OPENP(CONF,SID,STATE,TREE,ERR)
	NEW DEV,CMD,COLS,ROWS
	KILL ERR
	SET ERR("routine")="MIOMIDETM"
	IF $$SESSIONOK(SID,.STATE) QUIT 1
	SET DEV=$$DEVNAME(SID)
	SET CMD=$GET(CONF("miomide","terminal","command"),"ydb -direct")
	SET COLS=$$TERMNUM($GET(TREE("cols")),+$GET(CONF("miomide","terminal","cols"),132))
	SET ROWS=$$TERMNUM($GET(TREE("rows")),+$GET(CONF("miomide","terminal","rows"),32))
	OPEN DEV:(COMMAND=CMD)::"PIPE" ELSE  DO  QUIT 0
	. SET ERR("error")="open_failed"
	. SET ERR("detail")=CMD
	SET ^MIO("MIOMIDE","TERM","SID",SID,"open")=1
	SET ^MIO("MIOMIDE","TERM","SID",SID,"device")=DEV
	SET ^MIO("MIOMIDE","TERM","SID",SID,"principal")=$GET(STATE("principal"))
	SET ^MIO("MIOMIDE","TERM","SID",SID,"userName")=$GET(STATE("userName"))
	SET ^MIO("MIOMIDE","TERM","SID",SID,"clientId")=$$CLIENTID(.TREE,.STATE)
	SET ^MIO("MIOMIDE","TERM","SID",SID,"job")=$JOB
	SET ^MIO("MIOMIDE","TERM","SID",SID,"command")=CMD
	SET ^MIO("MIOMIDE","TERM","SID",SID,"cols")=COLS
	SET ^MIO("MIOMIDE","TERM","SID",SID,"rows")=ROWS
	SET ^MIO("MIOMIDE","TERM","SID",SID,"openedAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMIDE","TERM","CLIENT",$GET(STATE("principal")),$$CLIENTID(.TREE,.STATE))=SID
	QUIT 1
	;
DEVNAME(SID)
	QUIT "|MIOIDE-TERM-"_$JOB_"-"_($R(9999)+1)
	;
TOUCH(SID,STATE,TREE)
	NEW CLIENTID
	QUIT:$GET(SID)=""
	SET CLIENTID=$$CLIENTID(.TREE,.STATE)
	SET ^MIO("MIOMIDE","TERM","SID",SID,"lastSeenAt")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMIDE","TERM","SID",SID,"lastSeenHorolog")=$HOROLOG
	IF CLIENTID'="" SET ^MIO("MIOMIDE","TERM","SID",SID,"clientId")=CLIENTID
	IF $GET(STATE("principal"))'="" SET ^MIO("MIOMIDE","TERM","SID",SID,"principal")=$GET(STATE("principal"))
	IF $GET(STATE("userName"))'="" SET ^MIO("MIOMIDE","TERM","SID",SID,"userName")=$GET(STATE("userName"))
	IF CLIENTID'="" SET ^MIO("MIOMIDE","TERM","CLIENT",$GET(STATE("principal")),CLIENTID)=SID
	IF +$GET(TREE("cols"))>0 SET ^MIO("MIOMIDE","TERM","SID",SID,"cols")=$$TERMNUM($GET(TREE("cols")),+$GET(^MIO("MIOMIDE","TERM","SID",SID,"cols"),132))
	IF +$GET(TREE("rows"))>0 SET ^MIO("MIOMIDE","TERM","SID",SID,"rows")=$$TERMNUM($GET(TREE("rows")),+$GET(^MIO("MIOMIDE","TERM","SID",SID,"rows"),32))
	QUIT
	;
TERMNUM(V,DEF)
	NEW N
	SET N=+$GET(V)
	IF N<1 SET N=+$GET(DEF)
	IF N<1 SET N=1
	QUIT N
	;
WRITEP(SID,DATA,ERR)
	NEW DEV,$ETRAP,$ESTACK,FAIL
	KILL ERR
	SET ERR("routine")="MIOMIDETM"
	SET DEV=$GET(^MIO("MIOMIDE","TERM","SID",SID,"device"))
	IF DEV="" SET ERR("error")="device_missing" QUIT 0
	SET FAIL=0
	SET $ETRAP="DO WTRAP^MIOMIDETM(.FAIL,.ERR) QUIT"
	USE DEV WRITE $GET(DATA)
	USE $PRINCIPAL
	SET $ETRAP=""
	IF FAIL QUIT 0
	QUIT 1
	;
DRAIN(CONF,SID,OUT,ERR)
	NEW DEV,TXT,LIMIT,SPINS,I,CH,$ETRAP,$ESTACK,FAIL
	KILL OUT,ERR
	SET ERR("routine")="MIOMIDETM"
	SET DEV=$GET(^MIO("MIOMIDE","TERM","SID",SID,"device"))
	IF DEV="" QUIT
	SET LIMIT=+$GET(CONF("miomide","terminal","readLimit"),8192)
	SET SPINS=+$GET(CONF("miomide","terminal","readPolls"),5)
	IF LIMIT<1 SET LIMIT=8192
	IF SPINS<1 SET SPINS=1
	SET TXT="",FAIL=0
	SET $ETRAP="DO RTRAP^MIOMIDETM(.FAIL,.ERR) QUIT"
	USE DEV
	FOR I=1:1:SPINS QUIT:$LENGTH(TXT)'<LIMIT  DO  QUIT:'$TEST
	. READ *CH:0
	. QUIT:'$TEST
	. SET TXT=TXT_$CHAR(CH)
	. FOR  READ *CH:0 QUIT:'$TEST  QUIT:$LENGTH(TXT)'<LIMIT  SET TXT=TXT_$CHAR(CH)
	USE $PRINCIPAL
	SET $ETRAP=""
	IF FAIL QUIT
	SET OUT("data")=TXT
	SET OUT("byteCount")=$LENGTH(TXT)
	SET OUT("cols")=+$GET(^MIO("MIOMIDE","TERM","SID",SID,"cols"))
	SET OUT("rows")=+$GET(^MIO("MIOMIDE","TERM","SID",SID,"rows"))
	SET OUT("openedAt")=$GET(^MIO("MIOMIDE","TERM","SID",SID,"openedAt"))
	SET OUT("lastSeenAt")=$GET(^MIO("MIOMIDE","TERM","SID",SID,"lastSeenAt"))
	QUIT
	;
PURGESTALE(CONF)
	NEW SID,IDLE,LASTH
	SET IDLE=+$GET(CONF("miomide","terminal","sessionIdleSeconds"),900)
	IF IDLE<1 SET IDLE=900
	SET SID=""
	FOR  SET SID=$ORDER(^MIO("MIOMIDE","TERM","SID",SID)) QUIT:SID=""  DO
	. SET LASTH=$GET(^MIO("MIOMIDE","TERM","SID",SID,"lastSeenHorolog"))
	. IF LASTH="" SET LASTH=$HOROLOG
	. IF $$AGESECS(LASTH)'>IDLE QUIT
	. DO CLOSEMETA(SID)
	QUIT
	;
AGESECS(H)
	QUIT $$HSECS($HOROLOG)-$$HSECS($GET(H))
	;
HSECS(H)
	NEW D,S
	SET D=+$PIECE($GET(H),",",1)
	SET S=+$PIECE($GET(H),",",2)
	QUIT (D*86400)+S
	;
CLOSESID(SID)
	NEW DEV,JOB,PRINCIPAL,CLIENTID
	QUIT:$GET(SID)=""
	SET DEV=$GET(^MIO("MIOMIDE","TERM","SID",SID,"device"))
	SET JOB=+$GET(^MIO("MIOMIDE","TERM","SID",SID,"job"))
	SET PRINCIPAL=$GET(^MIO("MIOMIDE","TERM","SID",SID,"principal"))
	SET CLIENTID=$GET(^MIO("MIOMIDE","TERM","SID",SID,"clientId"))
	IF DEV'="",JOB=$JOB DO
	. USE $PRINCIPAL
	. CLOSE DEV
	IF PRINCIPAL'="",CLIENTID'="",$GET(^MIO("MIOMIDE","TERM","CLIENT",PRINCIPAL,CLIENTID))=SID KILL ^MIO("MIOMIDE","TERM","CLIENT",PRINCIPAL,CLIENTID)
	KILL ^MIO("MIOMIDE","TERM","SID",SID)
	QUIT
	;
CLOSEMETA(SID)
	DO CLOSESID($GET(SID))
	QUIT
	;
READY(CONF,SID,STATE,TREE,INFO)
	NEW OBJ
	SET OBJ("ok")=1
	SET OBJ("event")="ready"
	SET OBJ("sessionId")=$GET(SID)
	SET OBJ("clientId")=$GET(^MIO("MIOMIDE","TERM","SID",SID,"clientId"))
	SET OBJ("userName")=$GET(STATE("userName"))
	SET OBJ("cols")=+$GET(^MIO("MIOMIDE","TERM","SID",SID,"cols"),+$GET(CONF("miomide","terminal","cols"),132))
	SET OBJ("rows")=+$GET(^MIO("MIOMIDE","TERM","SID",SID,"rows"),+$GET(CONF("miomide","terminal","rows"),32))
	SET OBJ("reused")=+$GET(INFO("reused"))
	SET OBJ("openedAt")=$GET(^MIO("MIOMIDE","TERM","SID",SID,"openedAt"))
	SET OBJ("lastSeenAt")=$GET(^MIO("MIOMIDE","TERM","SID",SID,"lastSeenAt"))
	SET OBJ("data")=$GET(INFO("data"),"YDB> ")
	QUIT $$EN^MIOJSON1(.OBJ)
	;
DATA(SID,INFO)
	NEW OBJ
	SET OBJ("ok")=1
	SET OBJ("event")="data"
	SET OBJ("sessionId")=$GET(SID)
	SET OBJ("data")=$GET(INFO("data"))
	SET OBJ("byteCount")=+$GET(INFO("byteCount"))
	QUIT $$EN^MIOJSON1(.OBJ)
	;
PONG(SID)
	NEW OBJ
	SET OBJ("ok")=1
	SET OBJ("event")="pong"
	SET OBJ("sessionId")=$GET(SID)
	SET OBJ("serverTime")=$$NOWISO^MIOUTIL()
	QUIT $$EN^MIOJSON1(.OBJ)
	;
ACK(EVT,SID,DETAIL)
	NEW OBJ
	SET OBJ("ok")=1
	SET OBJ("event")=$GET(EVT)
	SET OBJ("sessionId")=$GET(SID)
	SET OBJ("detail")=$GET(DETAIL)
	SET OBJ("serverTime")=$$NOWISO^MIOUTIL()
	QUIT $$EN^MIOJSON1(.OBJ)
	;
CLOSED(SID)
	NEW OBJ
	SET OBJ("ok")=1
	SET OBJ("event")="closed"
	SET OBJ("sessionId")=$GET(SID)
	SET OBJ("serverTime")=$$NOWISO^MIOUTIL()
	QUIT $$EN^MIOJSON1(.OBJ)
	;
ERRJSON(CODE,DETAIL)
	NEW OBJ
	SET OBJ("ok")=0
	SET OBJ("event")="error"
	SET OBJ("error")=$GET(CODE)
	SET OBJ("detail")=$GET(DETAIL)
	SET OBJ("routine")="MIOMIDETM"
	QUIT $$EN^MIOJSON1(.OBJ)
	;
SAFE(X)
	NEW Y,I,C
	SET Y=""
	FOR I=1:1:$LENGTH($GET(X)) DO
	. SET C=$EXTRACT(X,I)
	. IF C?1AN SET Y=Y_C QUIT
	. SET Y=Y_"-"
	IF Y="" SET Y="session"
	QUIT Y
	;
WTRAP(FAIL,ERR)
	SET FAIL=1
	SET ERR("routine")="MIOMIDETM"
	SET ERR("error")="write_failed"
	SET ERR("detail")=$ZSTATUS
	SET $ECODE=""
	USE $PRINCIPAL
	QUIT
	;
RTRAP(FAIL,ERR)
	SET FAIL=1
	SET ERR("routine")="MIOMIDETM"
	SET ERR("error")="read_failed"
	SET ERR("detail")=$ZSTATUS
	SET $ECODE=""
	USE $PRINCIPAL
	QUIT
