MIOMOSWS ; MIOMOS websocket handler
	QUIT
	;
MESSAGE(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,RESP,EVT,APPKEY,SID,OK,PAYLOAD,ROOM,TEXT,MSG
	SET CTX("ws","keep_open")=1
	SET PAYLOAD=$GET(CTX("payload"))
	SET EVT=$$EVENT(PAYLOAD)
	SET OK=$$ENSURE^MIOMOSST(.CONF,.REQ,.CTX,.STATE,.ERR)
	IF 'OK DO
	. SET SID=$GET(CTX("miomos","sessionId"))
	. IF SID="" SET SID=$$SESSIONID(PAYLOAD)
	. IF $$INJECTAUTH(.CONF,SID,.CTX,.ERR) SET OK=$$ENSURE^MIOMOSST(.CONF,.REQ,.CTX,.STATE,.ERR)
	IF 'OK DO  QUIT
	. SET RESP=$$ERRJSON("session_error",$GET(ERR("error")))
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	SET CTX("miomos","sessionId")=$GET(STATE("sessionId"))
	IF EVT="hello" DO  QUIT
	. DO EVENT^MIOMOSAUD("ws_hello",.CTX,.STATE)
	. DO ACCESS^MIOMOSOBS("ws_hello",.CTX,.STATE)
	. SET RESP=$$HELLO(.STATE)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	. DO SNAPSHOT^MIOMOSCHAT($GET(STATE("chatRoom")),+$GET(STATE("chatLimit"),20),.RESP)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="ping" DO  QUIT
	. SET RESP=$$PONG(.STATE)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="command.exec"!(EVT="command") DO  QUIT
	. NEW CMDERR,TREE,REQID,CMD
	. SET REQID=$$REQID(PAYLOAD)
	. IF '$$COMMANDJSON(.CONF,.REQ,.CTX,PAYLOAD,.RESP,.CMDERR) DO
	. . IF $GET(CMDERR("error"))'="session_error" DO
	. . . IF $$DECODEPAY(PAYLOAD,.TREE,.CMDERR) SET CMD=$GET(TREE("command"))
	. . . DO EVENTX^MIOMOSAUD("ws_command_error",.CTX,.STATE,CMD)
	. . . DO ACCESS^MIOMOSOBS("ws_command_error",.CTX,.STATE)
	. ELSE  DO
	. . NEW TREE2
	. . IF $$DECODEPAY(PAYLOAD,.TREE2,.CMDERR) SET CMD=$GET(TREE2("command"))
	. . DO EVENTX^MIOMOSAUD("ws_command_exec",.CTX,.STATE,CMD)
	. . DO ACCESS^MIOMOSOBS("ws_command_exec",.CTX,.STATE)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="auth.signout" DO  QUIT
	. NEW REQID,SIGNERR
	. SET REQID=$$REQID(PAYLOAD)
	. IF '$$SIGNOUTJSON(.CONF,.REQ,.CTX,PAYLOAD,.RESP,.SIGNERR) SET RESP=$$CMDERRJSON(REQID,"auth.signout",400,$GET(SIGNERR("error"),"signout_failed"),$GET(SIGNERR("detail")))
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="launcher.open" DO  QUIT
	. SET APPKEY=$$APPKEY(PAYLOAD)
	. IF APPKEY="" SET APPKEY="workspace"
	. DO EVENTX^MIOMOSAUD("ws_launcher_open",.CTX,.STATE,APPKEY)
	. DO ACCESS^MIOMOSOBS("ws_launcher_open",.CTX,.STATE)
	. SET RESP=$$ACK("launcher.open",APPKEY,.STATE)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="layout.sync" DO  QUIT
	. DO SAVELAYOUT^MIOMOSST($GET(STATE("sessionId")),PAYLOAD)
	. DO EVENT^MIOMOSAUD("ws_layout_sync",.CTX,.STATE)
	. SET RESP=$$ACK("layout.sync","layout",.STATE)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="chat.fetch" DO  QUIT
	. SET ROOM=$$ROOM(PAYLOAD,.STATE)
	. DO SNAPSHOT^MIOMOSCHAT(ROOM,+$GET(STATE("chatLimit"),20),.RESP)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="chat.send" DO  QUIT
	. IF '$$HAS^MIOMOSPERM(.STATE,"chat.use") DO  QUIT
	. . SET RESP=$$ERRJSON("forbidden","chat.use")
	. . DO SENDTEXT^MIOWS(.DEV,RESP)
	. SET ROOM=$$ROOM(PAYLOAD,.STATE)
	. SET TEXT=$$TEXT(PAYLOAD)
	. IF '$$SEND^MIOMOSCHAT(.STATE,ROOM,TEXT,.MSG,.ERR) DO  QUIT
	. . DO ERROR^MIOMOSOBS("chat_send_error",$GET(ERR("error")),.CTX,.STATE,$GET(ERR("error")))
	. . SET RESP=$$ERRJSON("chat_send_error",$GET(ERR("error")))
	. . DO SENDTEXT^MIOWS(.DEV,RESP)
	. DO EVENTX^MIOMOSAUD("chat_send",.CTX,.STATE,ROOM)
	. DO ACCESS^MIOMOSOBS("chat_send",.CTX,.STATE)
	. DO MESSAGE^MIOMOSCHAT(.MSG,.RESP)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	;
	;
	IF EVT="terminal.open"!(EVT="terminal.attach") DO  QUIT
	. IF '$$HAS^MIOMOSPERM(.STATE,"terminal.use") DO  QUIT
	. . SET RESP=$$ERRJSON("forbidden","terminal.use")
	. . DO SENDTEXT^MIOWS(.DEV,RESP)
	. NEW TREE,TERR,OUT,TERMID
	. DO PURGESTALE^MIOMOSTPIPE(.CONF)
	. IF $EXTRACT($GET(PAYLOAD),1)="{" SET OK=$$DECODE^MIOJSON(PAYLOAD,.TREE,.TERR)
	. SET TERMID=$GET(TREE("terminalId"))
	. IF '$$OPEN^MIOMOSTPIPE(.STATE,.CONF,TERMID,.OUT,.TERR) DO  QUIT
	. . SET RESP=$$ERRJSON("terminal_open_failed",$GET(TERR("error")))
	. . DO SENDTEXT^MIOWS(.DEV,RESP)
	. SET RESP=$$TERMEVT("terminal.open",.OUT)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="terminal.input" DO  QUIT
	. NEW TREE,TERR,OUT,TERMID,DATA
	. DO PURGESTALE^MIOMOSTPIPE(.CONF)
	. IF $EXTRACT($GET(PAYLOAD),1)="{" SET OK=$$DECODE^MIOJSON(PAYLOAD,.TREE,.TERR)
	. SET TERMID=$GET(TREE("terminalId")),DATA=$GET(TREE("data"))
	. IF DATA="",$DATA(TREE("line")) SET DATA=$GET(TREE("line"))_$CHAR(13)
	. IF '$$INPUT^MIOMOSTPIPE(.STATE,TERMID,DATA,.OUT,.TERR) DO  QUIT
	. . SET RESP=$$ERRJSON("terminal_input_failed",$GET(TERR("error")))
	. . DO SENDTEXT^MIOWS(.DEV,RESP)
	. SET RESP=$$TERMEVT("terminal.stdout",.OUT)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="terminal.resize" DO  QUIT
	. NEW TREE,TERR,OUT,TERMID,COLS,ROWS
	. DO PURGESTALE^MIOMOSTPIPE(.CONF)
	. IF $EXTRACT($GET(PAYLOAD),1)="{" SET OK=$$DECODE^MIOJSON(PAYLOAD,.TREE,.TERR)
	. SET TERMID=$GET(TREE("terminalId")),COLS=+$GET(TREE("cols")),ROWS=+$GET(TREE("rows"))
	. IF '$$RESIZE^MIOMOSTPIPE(.STATE,TERMID,COLS,ROWS,.OUT,.TERR) DO  QUIT
	. . SET RESP=$$ERRJSON("terminal_resize_failed",$GET(TERR("error")))
	. . DO SENDTEXT^MIOWS(.DEV,RESP)
	. SET RESP=$$TERMEVT("terminal.resize",.OUT)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="terminal.poll"!(EVT="terminal.drain")!(EVT="ping.terminal") DO  QUIT
	. NEW TREE,TERR,OUT,TERMID
	. DO PURGESTALE^MIOMOSTPIPE(.CONF)
	. IF $EXTRACT($GET(PAYLOAD),1)="{" SET OK=$$DECODE^MIOJSON(PAYLOAD,.TREE,.TERR)
	. SET TERMID=$GET(TREE("terminalId"))
	. IF '$$POLL^MIOMOSTPIPE(.STATE,TERMID,.OUT,.TERR) DO  QUIT
	. . SET RESP=$$ERRJSON("terminal_poll_failed",$GET(TERR("error")))
	. . DO SENDTEXT^MIOWS(.DEV,RESP)
	. SET RESP=$$TERMEVT("terminal.stdout",.OUT)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	IF EVT="terminal.close" DO  QUIT
	. NEW TREE,TERR,OUT,TERMID
	. IF $EXTRACT($GET(PAYLOAD),1)="{" SET OK=$$DECODE^MIOJSON(PAYLOAD,.TREE,.TERR)
	. SET TERMID=$GET(TREE("terminalId"))
	. IF '$$CLOSE^MIOMOSTPIPE(.STATE,TERMID,.OUT,.TERR) DO  QUIT
	. . SET RESP=$$ERRJSON("terminal_close_failed",$GET(TERR("error")))
	. . DO SENDTEXT^MIOWS(.DEV,RESP)
	. SET RESP=$$TERMEVT("terminal.close",.OUT)
	. DO SENDTEXT^MIOWS(.DEV,RESP)
	DO EVENTX^MIOMOSAUD("ws_unsupported",.CTX,.STATE,EVT)
	SET RESP=$$ERRJSON("unsupported_event",EVT)
	DO SENDTEXT^MIOWS(.DEV,RESP)
	QUIT
	;
EVENT(PAY)
	NEW TREE,ERR,EVT
	SET EVT=""
	IF $GET(PAY)="" QUIT EVT
	IF $EXTRACT(PAY,1)="{" DO  QUIT:$GET(EVT)'="" EVT
	. IF '$$DECODE^MIOJSON($GET(PAY),.TREE,.ERR) QUIT
	. SET EVT=$GET(TREE("event"))
	IF PAY="hello" QUIT "hello"
	IF PAY="ping" QUIT "ping"
	QUIT EVT
	;
APPKEY(PAY)
	NEW TREE,ERR
	IF $EXTRACT($GET(PAY),1)="{" DO  QUIT $GET(TREE("appKey"))
	. IF '$$DECODE^MIOJSON($GET(PAY),.TREE,.ERR) QUIT
	QUIT ""
	;
ROOM(PAYLOAD,STATE)
	NEW TREE,ERR,ROOM
	SET ROOM=$GET(STATE("chatRoom"),"general")
	IF $EXTRACT($GET(PAYLOAD),1)'="{" QUIT ROOM
	IF '$$DECODE^MIOJSON($GET(PAYLOAD),.TREE,.ERR) QUIT ROOM
	IF $GET(TREE("room"))'="" SET ROOM=$GET(TREE("room"))
	QUIT ROOM
	;
TEXT(PAYLOAD)
	NEW TREE,ERR
	IF $EXTRACT($GET(PAYLOAD),1)'="{" QUIT ""
	IF '$$DECODE^MIOJSON($GET(PAYLOAD),.TREE,.ERR) QUIT ""
	QUIT $GET(TREE("text"))
	;
SESSIONID(PAY)
	NEW TREE,ERR,SID
	SET SID=""
	IF $GET(PAY)="" QUIT SID
	IF $EXTRACT(PAY,1)'="{" QUIT SID
	IF '$$DECODE^MIOJSON($GET(PAY),.TREE,.ERR) QUIT SID
	SET SID=$GET(TREE("sessionId"))
	QUIT SID
	;
INJECTAUTH(CONF,SID,CTX,ERR)
	NEW KEY,USER,ROLES,I,X
	KILL ERR
	SET ERR("routine")="MIOMOSWS"
	IF $GET(SID)="" SET ERR("error")="session_id_missing" QUIT 0
	SET KEY=$GET(^MIO("MIOMOS","SESSION",SID,"principal"))
	IF KEY="" SET ERR("error")="session_not_found" QUIT 0
	SET USER=$GET(^MIO("MIOMOS","SESSION",SID,"userName"))
	IF USER="" SET USER=KEY
	SET ROLES=$GET(^MIO("MIOMOS","SESSION",SID,"roles"))
	KILL CTX("auth")
	SET CTX("auth","ok")=1
	SET CTX("auth","claims","sub")=KEY
	SET CTX("auth","claims","name")=USER
	FOR I=1:1:$LENGTH(ROLES,",") DO
	. SET X=$$TRIM^MIOUTIL($PIECE(ROLES,",",I))
	. IF X'="" SET CTX("auth","roles",X)=1
	QUIT 1
	;
HELLO(STATE)
	NEW OBJ
	SET OBJ("ok")=1
	SET OBJ("event")="hello"
	SET OBJ("sessionId")=$GET(STATE("sessionId"))
	SET OBJ("userName")=$GET(STATE("userName"))
	SET OBJ("profile")=$GET(STATE("profile"))
	SET OBJ("themeKey")=$GET(STATE("themeKey"))
	SET OBJ("serverTime")=$$NOWISO^MIOUTIL()
	SET OBJ("idleTimeoutSeconds")=+$GET(STATE("idleTimeoutSeconds"))
	SET OBJ("absoluteTimeoutSeconds")=+$GET(STATE("absoluteTimeoutSeconds"))
	QUIT $$EN^MIOJSON1(.OBJ)
	;
PONG(STATE)
	NEW OBJ
	SET OBJ("ok")=1
	SET OBJ("event")="pong"
	SET OBJ("sessionId")=$GET(STATE("sessionId"))
	SET OBJ("serverTime")=$$NOWISO^MIOUTIL()
	QUIT $$EN^MIOJSON1(.OBJ)
	;
ACK(EVT,APPKEY,STATE)
	NEW OBJ
	SET OBJ("ok")=1
	SET OBJ("event")=$GET(EVT)
	SET OBJ("appKey")=$GET(APPKEY)
	SET OBJ("sessionId")=$GET(STATE("sessionId"))
	SET OBJ("serverTime")=$$NOWISO^MIOUTIL()
	SET OBJ("savedAt")=$GET(^MIO("MIOMOS","SESSION",$GET(STATE("sessionId")),"layoutSavedAt"))
	QUIT $$EN^MIOJSON1(.OBJ)
	;
DECODEPAY(PAYLOAD,TREE,ERR)
	KILL TREE,ERR
	SET ERR("routine")="MIOMOSWS"
	IF $EXTRACT($GET(PAYLOAD),1)'="{" SET ERR("error")="payload_not_json" QUIT 0
	QUIT $$DECODE^MIOJSON($GET(PAYLOAD),.TREE,.ERR)
	;
CMDOKJSON(REQID,CMD,OUT)
	NEW OBJ
	MERGE OBJ=OUT
	SET OBJ("ok")=1
	SET OBJ("event")="command.result"
	SET OBJ("requestId")=$GET(REQID)
	SET OBJ("command")=$SELECT($GET(CMD)'="":$GET(CMD),1:$GET(OUT("command")))
	SET OBJ("transport")="websocket"
	QUIT $$EN^MIOJSON1(.OBJ)
	;
CMDERRJSON(REQID,CMD,STATUS,CODE,DETAIL)
	NEW OBJ
	SET OBJ("ok")=0
	SET OBJ("event")="command.error"
	SET OBJ("requestId")=$GET(REQID)
	SET OBJ("command")=$GET(CMD)
	SET OBJ("status")=+$GET(STATUS,400)
	SET OBJ("error")=$GET(CODE)
	SET OBJ("detail")=$GET(DETAIL)
	SET OBJ("transport")="websocket"
	SET OBJ("routine")="MIOMOSWS"
	QUIT $$EN^MIOJSON1(.OBJ)
	;
COMMANDSIDJSON(CONF,REQ,CTX,SID,PAYLOAD,RESP,ERR)
	NEW TREE,TERR
	KILL RESP,ERR
	SET ERR("routine")="MIOMOSWS"
	DO CONFDEF^MIOMOS(.CONF)
	IF '$$DECODEPAY(PAYLOAD,.TREE,.TERR) DO  QUIT 0
	. MERGE ERR=TERR
	. SET RESP=$$CMDERRJSON("","",400,"invalid_json",$GET(TERR("error")))
	IF $GET(SID)'="" SET CTX("miomos","sessionId")=$GET(SID)
	IF $GET(TREE("sessionId"))="",$GET(SID)'="" SET TREE("sessionId")=$GET(SID)
	QUIT $$DOCMD(.CONF,.REQ,.CTX,.TREE,.RESP,.ERR)
	;
COMMANDJSON(CONF,REQ,CTX,PAYLOAD,RESP,ERR)
	NEW TREE,TERR
	KILL RESP,ERR
	SET ERR("routine")="MIOMOSWS"
	DO CONFDEF^MIOMOS(.CONF)
	IF '$$DECODEPAY(PAYLOAD,.TREE,.TERR) DO  QUIT 0
	. MERGE ERR=TERR
	. SET RESP=$$CMDERRJSON("","",400,"invalid_json",$GET(TERR("error")))
	QUIT $$DOCMD(.CONF,.REQ,.CTX,.TREE,.RESP,.ERR)
	;
DOCMD(CONF,REQ,CTX,TREE,RESP,ERR)
	NEW STATE,COUT,CERR,REQID,CMD,OK,SID,DEVKEY,USER,ROLES,I,X
	KILL RESP,ERR
	SET ERR("routine")="MIOMOSWS"
	SET REQID=$GET(TREE("requestId"))
	SET CMD=$GET(TREE("command"))
	SET SID=$GET(TREE("sessionId"))
	IF SID'="",$GET(CTX("miomos","sessionId"))="" SET CTX("miomos","sessionId")=SID
	SET OK=$$ENSURE^MIOMOSST(.CONF,.REQ,.CTX,.STATE,.ERR)
	IF 'OK DO
	. SET SID=$GET(CTX("miomos","sessionId"))
	. IF SID="" SET SID=$GET(TREE("sessionId"))
	. IF SID'="" DO
	. . IF $$INJECTAUTH(.CONF,SID,.CTX,.ERR) SET OK=$$ENSURE^MIOMOSST(.CONF,.REQ,.CTX,.STATE,.ERR)
	IF 'OK,$$DEVPROFILE^MIOMOS(.CONF) DO
	. SET DEVKEY=$GET(CONF("miomos","dev","principal"),"dev-user")
	. IF $GET(^MIO("MIOMOS","SESSION","BYKEY",DEVKEY))'="" SET CTX("miomos","sessionId")=$GET(^MIO("MIOMOS","SESSION","BYKEY",DEVKEY))
	. KILL CTX("auth")
	. SET USER=$GET(CONF("miomos","dev","userName"),"Developer")
	. SET ROLES=$GET(CONF("miomos","dev","roles"),"developer,admin")
	. SET CTX("auth","ok")=1
	. SET CTX("auth","claims","sub")=DEVKEY
	. SET CTX("auth","claims","name")=USER
	. FOR I=1:1:$LENGTH(ROLES,",") DO
	. . SET X=$$TRIM^MIOUTIL($PIECE(ROLES,",",I))
	. . IF X'="" SET CTX("auth","roles",X)=1
	. SET OK=$$ENSURE^MIOMOSST(.CONF,.REQ,.CTX,.STATE,.ERR)
	IF 'OK SET RESP=$$CMDERRJSON(REQID,CMD,400,"session_error",$GET(ERR("error"))) QUIT 0
	KILL TREE("event"),TREE("requestId"),TREE("sessionId")
	IF '$$EXEC^MIOMOSCMD(.STATE,.CONF,.TREE,.COUT,.CERR) DO  QUIT 0
	. MERGE ERR=CERR
	. SET RESP=$$CMDERRJSON(REQID,CMD,+$GET(CERR("status"),400),$GET(CERR("error"),"command_failed"),$SELECT($GET(CERR("detail"))'="":$GET(CERR("detail")),1:$GET(CERR("error"))))
	DO TOUCH^MIOMOSST($GET(STATE("sessionId")),"command."_CMD)
	SET RESP=$$CMDOKJSON(REQID,CMD,.COUT)
	QUIT 1
	;
SIGNOUTJSON(CONF,REQ,CTX,PAYLOAD,RESP,ERR)
	NEW STATE,OK,SID,REQID
	KILL RESP,ERR
	SET ERR("routine")="MIOMOSWS"
	SET REQID=$$REQID(PAYLOAD)
	SET OK=$$ENSURE^MIOMOSST(.CONF,.REQ,.CTX,.STATE,.ERR)
	IF 'OK DO
	. SET SID=$GET(CTX("miomos","sessionId"))
	. IF SID="" SET SID=$$SESSIONID(PAYLOAD)
	. IF $$INJECTAUTH(.CONF,SID,.CTX,.ERR) SET OK=$$ENSURE^MIOMOSST(.CONF,.REQ,.CTX,.STATE,.ERR)
	IF 'OK SET RESP=$$ERRJSON("session_error",$GET(ERR("error"))) QUIT 0
	DO SIGNOUT^MIOMOSAUTH(.CONF,.REQ,.CTX)
	DO EVENTX^MIOMOSAUD("auth_signout",.CTX,.STATE,"")
	DO ACCESS^MIOMOSOBS("auth_signout",.CTX,.STATE)
	SET RESP=$$AUTHACKJSON("auth.signout.ack",REQID,.STATE)
	QUIT 1
	;
REQID(PAYLOAD)
	NEW TREE,ERR
	IF '$$DECODEPAY($GET(PAYLOAD),.TREE,.ERR) QUIT ""
	QUIT $GET(TREE("requestId"))
	;
AUTHACKJSON(EVT,REQID,STATE)
	NEW OBJ
	SET OBJ("ok")=1
	SET OBJ("event")=$GET(EVT)
	SET OBJ("requestId")=$GET(REQID)
	SET OBJ("sessionId")=$GET(STATE("sessionId"))
	SET OBJ("transport")="websocket"
	SET OBJ("serverTime")=$$NOWISO^MIOUTIL()
	QUIT $$EN^MIOJSON1(.OBJ)
	;
	;
TERMEVT(EVT,OUT)
	NEW OBJ,N
	SET OBJ("ok")=1
	SET OBJ("event")=$GET(EVT)
	SET OBJ("terminalId")=$GET(OUT("terminalId"))
	IF $DATA(OUT("profile")) MERGE OBJ("profile")=OUT("profile")
	IF $GET(OUT("clear")) SET OBJ("clear")=1
	IF $GET(OUT("opened")) SET OBJ("opened")=1
	IF $GET(OUT("attached")) SET OBJ("attached")=1
	IF $GET(OUT("closed")) SET OBJ("closed")=1
	IF $GET(OUT("transport"))'="" SET OBJ("transport")=$GET(OUT("transport"))
	SET N=""
	FOR  SET N=$ORDER(OUT("write",N)) QUIT:N=""  SET OBJ("write",N)=OUT("write",N)
	IF $DATA(OUT("cols")) SET OBJ("cols")=+$GET(OUT("cols"))
	IF $DATA(OUT("rows")) SET OBJ("rows")=+$GET(OUT("rows"))
	QUIT $$EN^MIOJSON1(.OBJ)
	;
ERRJSON(CODE,DETAIL)
	NEW OBJ
	SET OBJ("ok")=0
	SET OBJ("error")=$GET(CODE)
	SET OBJ("detail")=$GET(DETAIL)
	SET OBJ("routine")="MIOMOSWS"
	QUIT $$EN^MIOJSON1(.OBJ)
	;
	;