MIOMIDEAPI ; MIOIDE API handlers
	QUIT
	;
BOOTSTRAP(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,OBJ
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,401,"login_required",$GET(ERR("error")),.CTX)
	DO BOOTOBJ^MIOMIDEST(.STATE,.CONF,.OBJ)
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,200,.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
ROUTINES(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,OBJ,LIST,I
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,401,"login_required",$GET(ERR("error")),.CTX)
	IF '$$LIST^MIOMIDERT(.CONF,.LIST,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,500,$GET(ERR("error"),"list_failed"),$GET(ERR("detail")),.CTX)
	SET OBJ("ok")=1
	SET OBJ("count")=+$GET(LIST("count"))
	FOR I=1:1:+$GET(LIST("count")) DO
	. SET OBJ("items",I,"name")=$GET(LIST(I,"name"))
	. SET OBJ("items",I,"type")=$GET(LIST(I,"type"))
	. SET OBJ("items",I,"path")=$GET(LIST(I,"path"))
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,200,.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
ROUTINE(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,OBJ,NAME
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,401,"login_required",$GET(ERR("error")),.CTX)
	SET NAME=$GET(REQ("params","name"))
	IF '$$LOAD^MIOMIDERT(.CONF,NAME,.OBJ,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,404,$GET(ERR("error"),"load_failed"),$GET(ERR("detail")),.CTX)
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,200,.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
SAVE(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,TREE,LINES,OBJ,NAME
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,401,"login_required",$GET(ERR("error")),.CTX)
	IF '$$PARSEINPUT(.REQ,.TREE,.LINES,.ERR,1) DO  QUIT
	. DO RESPERR(.DEV,.CONF,400,$GET(ERR("error"),"body_invalid"),$GET(ERR("detail")),.CTX)
	SET NAME=$GET(REQ("params","name")) IF NAME="" SET NAME=$GET(TREE("name"))
	IF '$$SAVEARR^MIOMIDERT(.CONF,NAME,.LINES,.OBJ,.ERR) DO  QUIT
	. DO RESPERRX(.DEV,.CONF,400,$GET(ERR("error"),"save_failed"),$GET(ERR("detail")),.OBJ,.CTX)
	SET OBJ("message")="Routine saved"
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,200,.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
COMPILE(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,TREE,LINES,OBJ,SAVEOBJ,NAME,HASBODY,SAVED
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,401,"login_required",$GET(ERR("error")),.CTX)
	SET HASBODY=$$HASBODY(.REQ),SAVED=0
	IF HASBODY,'$$PARSEINPUT(.REQ,.TREE,.LINES,.ERR,0) DO  QUIT
	. DO RESPERR(.DEV,.CONF,400,$GET(ERR("error"),"body_invalid"),$GET(ERR("detail")),.CTX)
	SET NAME=$GET(REQ("params","name")) IF NAME="" SET NAME=$GET(TREE("name"))
	IF HASBODY,$DATA(LINES) DO
	. IF '$$SAVEARR^MIOMIDERT(.CONF,NAME,.LINES,.SAVEOBJ,.ERR) DO  QUIT
	. . DO RESPERRX(.DEV,.CONF,400,$GET(ERR("error"),"save_failed"),$GET(ERR("detail")),.SAVEOBJ,.CTX)
	. SET SAVED=1
	IF $GET(CTX("responseSent")) QUIT
	IF '$$COMPILE^MIOMIDERT(.CONF,NAME,.OBJ,.ERR) DO  QUIT
	. IF SAVED MERGE OBJ("save")=SAVEOBJ
	. SET OBJ("saved")=SAVED
	. DO RESPERRX(.DEV,.CONF,422,$GET(ERR("error"),"compile_failed"),$GET(ERR("detail")),.OBJ,.CTX)
	IF SAVED MERGE OBJ("save")=SAVEOBJ
	SET OBJ("saved")=SAVED
	SET OBJ("message")="Routine compiled"
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,200,.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
RUN(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,TREE,OBJ,NAME,LINES
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,401,"login_required",$GET(ERR("error")),.CTX)
	IF $$HASBODY(.REQ),'$$PARSEINPUT(.REQ,.TREE,.LINES,.ERR,0) DO  QUIT
	. DO RESPERR(.DEV,.CONF,400,$GET(ERR("error"),"body_invalid"),$GET(ERR("detail")),.CTX)
	SET NAME=$GET(TREE("name"))
	IF NAME="" SET NAME=$GET(REQ("params","name"))
	IF '$$RUN^MIOMIDERT(.CONF,NAME,.OBJ,.ERR) DO  QUIT
	. DO RESPERRX(.DEV,.CONF,400,$GET(ERR("error"),"run_failed"),$GET(ERR("detail")),.OBJ,.CTX)
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,200,.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
SEARCH(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,OBJ,TERM
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,401,"login_required",$GET(ERR("error")),.CTX)
	SET TERM=$GET(REQ("query","q"))
	IF '$$SEARCH^MIOMIDERT(.CONF,TERM,.OBJ,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,400,$GET(ERR("error"),"search_failed"),$GET(ERR("detail")),.CTX)
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,200,.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
GLOBALS(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,OBJ,ROOT,LIMIT
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,401,"login_required",$GET(ERR("error")),.CTX)
	SET ROOT=$GET(REQ("query","root"))
	SET LIMIT=$GET(REQ("query","limit"))
	IF '$$GLOBALS^MIOMIDERT(.CONF,ROOT,LIMIT,.OBJ,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,400,$GET(ERR("error"),"globals_failed"),$GET(ERR("detail")),.CTX)
	SET OBJ("ok")=1
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,200,.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
DEBUG(DEV,CONF,REQ,CTX)
	NEW STATE,ERR,OBJ,NAME
	IF '$$ENSURE^MIOMIDEST(.CONF,.REQ,.CTX,.STATE,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,401,"login_required",$GET(ERR("error")),.CTX)
	SET NAME=$GET(REQ("query","name"))
	IF '$$DEBUGSNAP^MIOMIDERT(.CONF,NAME,.OBJ,.ERR) DO  QUIT
	. DO RESPERR(.DEV,.CONF,400,$GET(ERR("error"),"debug_failed"),$GET(ERR("detail")),.CTX)
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,200,.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
PARSEINPUT(REQ,TREE,LINES,ERR,REQUIRED)
	NEW JSON
	KILL TREE,LINES
	SET REQUIRED=+$GET(REQUIRED)
	SET JSON=$$BODYTXT(.REQ)
	IF JSON="" DO  QUIT $SELECT(REQUIRED:0,1:1)
	. IF REQUIRED SET ERR("routine")="MIOMIDEAPI",ERR("error")="body_missing"
	IF '$$DECODE^MIOJSON(JSON,.TREE,.ERR) SET ERR("routine")="MIOMIDEAPI" QUIT 0
	DO EXTRACTLINES(.TREE,.LINES)
	QUIT 1
	;
HASBODY(REQ)
	NEW MODE
	SET MODE=$GET(REQ("body","mode"),"scalar")
	IF MODE="global" QUIT $GET(REQ("body","ref"))'=""
	QUIT $GET(REQ("body"))'=""
	;
EXTRACTLINES(TREE,LINES)
	NEW I,TEXT
	KILL LINES
	SET I=""
	FOR  SET I=$ORDER(TREE("sourceLines",I)) QUIT:I=""  DO
	. SET LINES(+I)=$$STRIPCR($GET(TREE("sourceLines",I)))
	IF $DATA(LINES) QUIT
	SET TEXT=$GET(TREE("source"))
	DO SPLIT(.TEXT,.LINES)
	QUIT
	;
SPLIT(TEXT,LINES)
	NEW I,MAX,LINE
	KILL LINES
	IF $GET(TEXT)="" SET LINES(1)="" QUIT
	SET MAX=$LENGTH(TEXT,$CHAR(10))
	IF MAX<1 SET MAX=1
	FOR I=1:1:MAX DO
	. SET LINE=$PIECE(TEXT,$CHAR(10),I)
	. SET LINES(I)=$$STRIPCR(LINE)
	QUIT
	;
STRIPCR(X)
	IF $EXTRACT($GET(X),$LENGTH($GET(X)))=$CHAR(13) QUIT $EXTRACT(X,1,$LENGTH(X)-1)
	QUIT $GET(X)
	;
BODYTXT(REQ)
	NEW MODE,REF,N,I,TXT
	SET MODE=$GET(REQ("body","mode"),"scalar")
	IF MODE="scalar" QUIT $GET(REQ("body"))
	IF MODE'="global" QUIT ""
	SET REF=$GET(REQ("body","ref"))
	IF REF="" QUIT ""
	SET N=+$GET(REQ("body","n")),TXT=""
	FOR I=1:1:N SET TXT=TXT_$GET(@REF@(I))
	QUIT TXT
	;
RESPERR(DEV,CONF,STATUS,CODE,DETAIL,CTX)
	NEW OBJ
	SET OBJ("ok")=0
	SET OBJ("routine")="MIOMIDEAPI"
	SET OBJ("error")=$GET(CODE,"mioide_api_error")
	SET OBJ("detail")=$GET(DETAIL)
	SET CTX("responseSent")=1
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,+$GET(STATUS,500),.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
	;
RESPERRX(DEV,CONF,STATUS,CODE,DETAIL,EXTRA,CTX)
	NEW OBJ
	MERGE OBJ=EXTRA
	SET OBJ("ok")=0
	SET OBJ("routine")="MIOMIDEAPI"
	SET OBJ("error")=$GET(CODE,"mioide_api_error")
	SET OBJ("detail")=$GET(DETAIL)
	SET CTX("responseSent")=1
	DO RESPJSONX^MIOHTTP(.DEV,.CONF,+$GET(STATUS,500),.OBJ,$GET(CTX("request_id")),.CTX)
	QUIT
