MIOMOSAUD ; MIOMOS audit helpers
	QUIT
	;
EVENT(NAME,CTX,STATE)
	DO EVENTX($GET(NAME),.CTX,.STATE,"")
	QUIT
	;
EVENTX(NAME,CTX,STATE,DETAIL)
	NEW ID,NOWD,NOWS,CORR
	SET ID=$INCREMENT(^MIO("MIOMOS","AUDIT","SEQ"))
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	SET CORR=$$CORRID(.CTX,.STATE)
	SET ^MIO("MIOMOS","AUDIT",ID,"ts")=$$NOWISO^MIOUTIL()
	SET ^MIO("MIOMOS","AUDIT",ID,"day")=NOWD
	SET ^MIO("MIOMOS","AUDIT",ID,"sec")=NOWS
	SET ^MIO("MIOMOS","AUDIT",ID,"event")=$GET(NAME)
	SET ^MIO("MIOMOS","AUDIT",ID,"detail")=$$DETAIL($GET(DETAIL))
	SET ^MIO("MIOMOS","AUDIT",ID,"requestId")=$GET(CTX("request_id"))
	SET ^MIO("MIOMOS","AUDIT",ID,"correlationId")=CORR
	SET ^MIO("MIOMOS","AUDIT",ID,"route")=$GET(CTX("route"))
	SET ^MIO("MIOMOS","AUDIT",ID,"principal")=$GET(STATE("principal"))
	SET ^MIO("MIOMOS","AUDIT",ID,"sessionId")=$GET(STATE("sessionId"))
	SET ^MIO("MIOMOS","AUDIT",ID,"profile")=$GET(STATE("profile"))
	QUIT
	;
DETAIL(X)
	SET X=$GET(X)
	IF $LENGTH(X)>240 SET X=$EXTRACT(X,1,240)
	QUIT X
	;
CORRID(CTX,STATE)
	NEW X
	SET X=$GET(CTX("request_id")) IF X'="" QUIT X
	SET X=$GET(CTX("miomos","sessionId")) IF X'="" QUIT X
	SET X=$GET(STATE("sessionId")) IF X'="" QUIT X
	QUIT "miomos-corr-unknown"
	;
TAIL(LIMIT,OUT)
	NEW ID,N,START
	KILL OUT
	SET LIMIT=+$GET(LIMIT,8) IF LIMIT<1 SET LIMIT=8
	SET START=+$GET(^MIO("MIOMOS","AUDIT","SEQ"))
	SET N=0
	FOR ID=START:-1:1 QUIT:N'<LIMIT  DO
	. IF '$DATA(^MIO("MIOMOS","AUDIT",ID)) QUIT
	. SET N=N+1
	. DO MERGE1(ID,$NAME(OUT(N)))
	QUIT
	;
MERGE1(ID,ROOT)
	SET @ROOT@("id")=ID
	SET @ROOT@("ts")=$GET(^MIO("MIOMOS","AUDIT",ID,"ts"))
	SET @ROOT@("event")=$GET(^MIO("MIOMOS","AUDIT",ID,"event"))
	SET @ROOT@("detail")=$GET(^MIO("MIOMOS","AUDIT",ID,"detail"))
	SET @ROOT@("principal")=$GET(^MIO("MIOMOS","AUDIT",ID,"principal"))
	SET @ROOT@("sessionId")=$GET(^MIO("MIOMOS","AUDIT",ID,"sessionId"))
	SET @ROOT@("route")=$GET(^MIO("MIOMOS","AUDIT",ID,"route"))
	SET @ROOT@("correlationId")=$GET(^MIO("MIOMOS","AUDIT",ID,"correlationId"))
	QUIT
	;
COUNT()
	NEW ID,N
	SET (ID,N)=0
	FOR  SET ID=$ORDER(^MIO("MIOMOS","AUDIT",ID)) QUIT:ID=""  DO
	. IF +ID'>0 QUIT
	. SET N=N+1
	QUIT N
	;
EXPORT(LIMIT,OUT)
	NEW ID,LAST,N
	KILL OUT
	SET LIMIT=+$GET(LIMIT,250) IF LIMIT<1 SET LIMIT=250
	SET LAST=+$GET(^MIO("MIOMOS","AUDIT","SEQ"))
	SET N=0
	FOR ID=LAST:-1:1 QUIT:N'<LIMIT  DO
	. IF '$DATA(^MIO("MIOMOS","AUDIT",ID)) QUIT
	. SET N=N+1
	. DO MERGE1(ID,$NAME(OUT(N)))
	DO REVERSE(.OUT)
	QUIT
	;
REVERSE(OUT)
	NEW TMP,N,M
	MERGE TMP=OUT
	KILL OUT
	SET N=0,M=""
	FOR  SET M=$ORDER(TMP(M),-1) QUIT:M=""  DO
	. SET N=N+1
	. MERGE OUT(N)=TMP(M)
	QUIT
	;
PRUNE(KEEP,DAYS,OUT)
	NEW NOWD,NOWS,ID,REMOVED,ACTIVE,DAY,SEC,EXPIRE
	KILL OUT
	SET KEEP=+$GET(KEEP) IF KEEP<0 SET KEEP=0
	SET DAYS=+$GET(DAYS) IF DAYS<0 SET DAYS=0
	SET NOWD=+$PIECE($HOROLOG,",",1),NOWS=+$PIECE($HOROLOG,",",2)
	SET ACTIVE=$$COUNT(),REMOVED=0
	SET ID=0
	FOR  SET ID=$ORDER(^MIO("MIOMOS","AUDIT",ID)) QUIT:ID=""  DO
	. IF +ID'>0 QUIT
	. SET DAY=+$GET(^MIO("MIOMOS","AUDIT",ID,"day"))
	. SET SEC=+$GET(^MIO("MIOMOS","AUDIT",ID,"sec"))
	. SET EXPIRE=0
	. IF DAYS>0,DAY>0 DO
	. . IF $$AGESEC(DAY,SEC,NOWD,NOWS)>(DAYS*86400) SET EXPIRE=1
	. IF 'EXPIRE,ACTIVE'>KEEP QUIT
	. KILL ^MIO("MIOMOS","AUDIT",ID)
	. SET REMOVED=REMOVED+1,ACTIVE=ACTIVE-1
	SET OUT("type")="AUDIT"
	SET OUT("removed")=REMOVED
	SET OUT("remaining")=ACTIVE
	QUIT
	;
AGESEC(D1,S1,D2,S2)
	IF (+$GET(D1)=0),(+$GET(S1)=0) QUIT 0
	QUIT (((+$GET(D2)-+$GET(D1))*86400)+(+$GET(S2)-+$GET(S1)))
	;
