MIOOSFS ; MIOOS global-backed virtual file system
	QUIT
	;
CHUNK(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","fs","chunkSize"),524288)
	IF N<2048 SET N=2048
	IF N>524288 SET N=524288
	QUIT N
	;
INIT(CONF)
	NEW OWNER,ROLES,ROOT,DOCS,DESK,README,NOW
	SET OWNER=$GET(CONF("mioos","bootstrapAuth","admin","username"),"admin")
	SET ROLES="admin,operator,guest"
	IF '$DATA(^MIO("MIOOS","FS","SEQ")) SET ^MIO("MIOOS","FS","SEQ")=0
	SET NOW=$HOROLOG
	DO SAVEENTRY("root","folder","","/","inode/directory",0,NOW,NOW,OWNER,ROLES,1,1,1)
	DO ENSUREFOLDER("root","Desktop",OWNER,ROLES,.DESK)
	DO ENSUREFOLDER("root","Documents",OWNER,ROLES,.DOCS)
	DO ENSUREFILE("root","README.txt","Welcome to MIOOS VFS","text/plain",OWNER,ROLES,.README,.CONF)
	QUIT
	;
ENSUREFOLDER(PARENT,NAME,OWNER,ROLES,OUTID)
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",$GET(PARENT),$GET(NAME)))
	IF OUTID'="",$$EXISTS(OUTID),$$FIELD(OUTID,1)="folder" QUIT
	IF OUTID'="" KILL ^MIO("MIOOS","FS","CHILD",PARENT,NAME)
	DO MKDIRID($GET(PARENT),$GET(NAME),$GET(OWNER),$GET(ROLES),.OUTID)
	QUIT
	;
ENSUREFILE(PARENT,NAME,DATA,MIME,OWNER,ROLES,OUTID,CONF)
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",$GET(PARENT),$GET(NAME)))
	IF OUTID'="",('$$EXISTS(OUTID)!($$FIELD(OUTID,1)'="file")) DO
	. KILL ^MIO("MIOOS","FS","CHILD",PARENT,NAME)
	. SET OUTID=""
	DO WRITEFILE($GET(PARENT),$GET(NAME),$GET(DATA),$GET(MIME),$GET(OWNER),$GET(ROLES),.OUTID,.CONF)
	QUIT
	;
NEXTID()
	NEW N
	SET N=$INCREMENT(^MIO("MIOOS","FS","SEQ"))
	QUIT "fs-"_N
	;
SAVEENTRY(ID,KIND,PARENT,NAME,MIME,SIZE,CDT,MDT,OWNER,ROLES,CANR,CANW,CAND)
	NEW U SET U="^"
	SET ^MIO("MIOOS","FS","ENTRY",ID)=KIND_U_PARENT_U_NAME_U_MIME_U_SIZE_U_CDT_U_MDT_U_OWNER_U_ROLES_U_CANR_U_CANW_U_CAND
	QUIT
	;
EXISTS(ID)
	QUIT $DATA(^MIO("MIOOS","FS","ENTRY",$GET(ID)))#2
	;
FIELD(ID,PIECE)
	NEW U SET U="^"
	QUIT $PIECE($GET(^MIO("MIOOS","FS","ENTRY",$GET(ID))),U,+$GET(PIECE))
	;
ROOTID()
	QUIT "root"
	;
TEXTLIKE(MIME,NAME)
	NEW LOWM,LOWN
	SET LOWM=$$LOW^MIOUTIL($GET(MIME))
	SET LOWN=$$LOW^MIOUTIL($GET(NAME))
	IF LOWM["text/" QUIT 1
	IF LOWM["json" QUIT 1
	IF LOWM["xml" QUIT 1
	IF LOWM["javascript" QUIT 1
	IF LOWM["ecmascript" QUIT 1
	IF LOWM["css" QUIT 1
	IF LOWM["html" QUIT 1
	IF LOWM["markdown" QUIT 1
	IF LOWM["csv" QUIT 1
	IF LOWM["yaml" QUIT 1
	IF LOWM["x-mumps" QUIT 1
	IF $LENGTH(LOWN)>3,$EXTRACT(LOWN,$LENGTH(LOWN)-3,$LENGTH(LOWN))=".txt" QUIT 1
	IF $LENGTH(LOWN)>2,$EXTRACT(LOWN,$LENGTH(LOWN)-2,$LENGTH(LOWN))=".md" QUIT 1
	IF $LENGTH(LOWN)>4,$EXTRACT(LOWN,$LENGTH(LOWN)-4,$LENGTH(LOWN))=".json" QUIT 1
	IF $LENGTH(LOWN)>2,$EXTRACT(LOWN,$LENGTH(LOWN)-2,$LENGTH(LOWN))=".js" QUIT 1
	IF $LENGTH(LOWN)>3,$EXTRACT(LOWN,$LENGTH(LOWN)-3,$LENGTH(LOWN))=".css" QUIT 1
	IF $LENGTH(LOWN)>4,$EXTRACT(LOWN,$LENGTH(LOWN)-4,$LENGTH(LOWN))=".html" QUIT 1
	IF $LENGTH(LOWN)>3,$EXTRACT(LOWN,$LENGTH(LOWN)-3,$LENGTH(LOWN))=".xml" QUIT 1
	IF $LENGTH(LOWN)>3,$EXTRACT(LOWN,$LENGTH(LOWN)-3,$LENGTH(LOWN))=".csv" QUIT 1
	IF $LENGTH(LOWN)>1,$EXTRACT(LOWN,$LENGTH(LOWN)-1,$LENGTH(LOWN))=".m" QUIT 1
	QUIT 0
	;
ISTEXT(DATA)
	NEW I,C,LEN
	SET LEN=$LENGTH($GET(DATA))
	IF LEN=0 QUIT 1
	FOR I=1:1:LEN DO  QUIT:$GET(C)=-1
	. SET C=$ASCII(DATA,I)
	. IF C=9!(C=10)!(C=13) QUIT
	. IF C<32 SET C=-1 QUIT
	. IF C=127 SET C=-1 QUIT
	IF $GET(C)=-1 QUIT 0
	QUIT 1
	;
HOMEID()
	NEW ID
	SET ID=$GET(^MIO("MIOOS","FS","CHILD","root","Documents"))
	IF ID="" SET ID="root"
	QUIT ID
	;
VALIDNAME(NAME)
	SET NAME=$GET(NAME)
	IF NAME="" QUIT 0
	IF NAME["/" QUIT 0
	IF NAME="." QUIT 0
	IF NAME=".." QUIT 0
	QUIT 1
	;
RESOLVE(PATH,OUTID,ERR)
	NEW I,NODE,NAME
	SET ERR("routine")="MIOOSFS",OUTID=""
	SET PATH=$GET(PATH)
	IF PATH="" SET ERR("error")="path_missing" QUIT 0
	IF $$EXISTS(PATH) SET OUTID=PATH QUIT 1
	IF PATH="root" SET OUTID="root" QUIT 1
	IF $EXTRACT(PATH,1)'="/" SET PATH="/"_PATH
	SET NODE="root"
	IF PATH="/" SET OUTID=NODE QUIT 1
	FOR I=2:1:$LENGTH(PATH,"/") DO  QUIT:NODE=""
	. SET NAME=$PIECE(PATH,"/",I)
	. QUIT:NAME=""
	. SET NODE=$GET(^MIO("MIOOS","FS","CHILD",NODE,NAME))
	. IF NODE'="",'$$EXISTS(NODE) SET NODE=""
	IF NODE="" SET ERR("error")="path_not_found",ERR("detail")=PATH QUIT 0
	SET OUTID=NODE
	QUIT 1
	;
PATH(ID)
	NEW CUR,NAME,OUT,PARENT
	SET ID=$GET(ID)
	IF ID="" QUIT ""
	IF ID="root" QUIT "/"
	SET CUR=ID,OUT=""
	FOR  DO  QUIT:CUR=""!(CUR="root")
	. SET NAME=$$FIELD(CUR,3),PARENT=$$FIELD(CUR,2)
	. SET OUT="/"_NAME_OUT
	. SET CUR=PARENT
	IF OUT="" SET OUT="/"
	QUIT OUT
	;
ROLEOK(ROLECSV,STATE)
	NEW I,R,CSV
	SET CSV=","_$GET(ROLECSV)_","
	IF CSV=",," QUIT 1
	FOR I=1:1:$LENGTH($GET(STATE("roles")),",") DO  QUIT:$GET(R)'=""
	. NEW X SET X=$PIECE($GET(STATE("roles")),",",I) QUIT:X=""
	. IF CSV[","_X_"," SET R=X
	QUIT $SELECT(R'="":1,1:0)
	;
CAN(ID,STATE,MODE)
	NEW OWNER,ROLES,FLAG,USER
	SET USER=$GET(STATE("principal"))
	IF USER="" SET USER="guest"
	IF '$$EXISTS(ID) QUIT 0
	SET OWNER=$$FIELD(ID,8),ROLES=$$FIELD(ID,9)
	IF USER=OWNER QUIT 1
	IF '$$ROLEOK(ROLES,.STATE) QUIT 0
	SET FLAG=$SELECT($GET(MODE)="write":$$FIELD(ID,11),$GET(MODE)="delete":$$FIELD(ID,12),1:$$FIELD(ID,10))
	QUIT +FLAG
	;
MKDIRID(PARENT,NAME,OWNER,ROLES,OUTID)
	NEW ID,NOW
	SET OUTID=""
	IF '$$VALIDNAME($GET(NAME)) QUIT
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PARENT,NAME))
	IF OUTID'="",$$EXISTS(OUTID),$$FIELD(OUTID,1)="folder" QUIT
	IF OUTID'="" KILL ^MIO("MIOOS","FS","CHILD",PARENT,NAME)
	SET ID=$$NEXTID(),NOW=$HOROLOG
	DO SAVEENTRY(ID,"folder",PARENT,NAME,"inode/directory",0,NOW,NOW,$GET(OWNER),$GET(ROLES),1,1,1)
	SET ^MIO("MIOOS","FS","CHILD",PARENT,NAME)=ID
	SET OUTID=ID
	QUIT
	;
MKDIR(STATE,PARENT,NAME,OUT,ERR)
	NEW PID,OWNER,ROLES,ID
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$VALIDNAME($GET(NAME)) SET ERR("error")="invalid_name" QUIT 0
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	IF $GET(^MIO("MIOOS","FS","CHILD",PID,NAME))'="" SET ERR("error")="name_conflict" QUIT 0
	SET OWNER=$GET(STATE("principal"),"guest"),ROLES=$GET(STATE("roles"),"guest")
	DO MKDIRID(PID,$GET(NAME),OWNER,ROLES,.ID)
	IF ID="" SET ERR("error")="mkdir_failed" QUIT 0
	DO META(.STATE,ID,.OUT,.ERR)
	QUIT 1
	;
WRITEFILE(PARENT,NAME,DATA,MIME,OWNER,ROLES,OUTID,CONF)
	NEW NOW,CHUNK,POS,IDX,LEN,SIZE,U
	SET U="^",NOW=$HOROLOG,CHUNK=$$CHUNK(.CONF)
	IF '$$VALIDNAME($GET(NAME)) SET OUTID="" QUIT
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PARENT,NAME))
	IF OUTID'="",('$$EXISTS(OUTID)!($$FIELD(OUTID,1)'="file")) DO
	. KILL ^MIO("MIOOS","FS","CHILD",PARENT,NAME)
	. SET OUTID=""
	IF OUTID="" DO
	. SET OUTID=$$NEXTID()
	. DO SAVEENTRY(OUTID,"file",PARENT,NAME,$GET(MIME,"application/octet-stream"),0,NOW,NOW,$GET(OWNER),$GET(ROLES),1,1,1)
	. SET ^MIO("MIOOS","FS","CHILD",PARENT,NAME)=OUTID
	KILL ^MIO("MIOOS","FS","DATA",OUTID)
	DO SETCHUNK(OUTID,CHUNK)
	SET LEN=$ZLENGTH($GET(DATA)),SIZE=LEN,IDX=0
	IF LEN=0 SET ^MIO("MIOOS","FS","DATA",OUTID,1)=""
	FOR POS=1:CHUNK:LEN DO
	. SET IDX=IDX+1
	. SET ^MIO("MIOOS","FS","DATA",OUTID,IDX)=$ZEXTRACT(DATA,POS,POS+CHUNK-1)
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,1)="file"
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,2)=PARENT
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,3)=NAME
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,4)=$GET(MIME,"application/octet-stream")
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,5)=SIZE
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,7)=NOW
	SET ^MIO("MIOOS","FS","HASH",OUTID)=$$SHA256^MIOSHA256($GET(DATA))
	QUIT
	;
WRITE(STATE,PARENT,NAME,DATA,MIME,OUT,ERR)
	NEW PID,OWNER,ROLES,ID
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$VALIDNAME($GET(NAME)) SET ERR("error")="invalid_name" QUIT 0
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	SET OWNER=$GET(STATE("principal"),"guest"),ROLES=$GET(STATE("roles"),"guest")
	DO WRITEFILE(PID,$GET(NAME),$GET(DATA),$GET(MIME,"application/octet-stream"),OWNER,ROLES,.ID)
	IF ID="" SET ERR("error")="write_failed" QUIT 0
	DO META(.STATE,ID,.OUT,.ERR)
	QUIT 1
	;
WRITEPART(STATE,PARENT,NAME,MIME,MP,IDX,OUT,ERR)
	NEW PID,OWNER,ROLES,ID
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$VALIDNAME($GET(NAME)) SET ERR("error")="invalid_name" QUIT 0
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	SET OWNER=$GET(STATE("principal"),"guest"),ROLES=$GET(STATE("roles"),"guest")
	DO WRITEPARTF(PID,$GET(NAME),$GET(MIME,"application/octet-stream"),OWNER,ROLES,.MP,+$GET(IDX),.ID,.ERR)
	IF ID="" QUIT 0
	DO META(.STATE,ID,.OUT,.ERR)
	QUIT 1
	;
WRITEPARTF(PARENT,NAME,MIME,OWNER,ROLES,MP,IDX,OUTID,ERR)
	NEW NOW,CHUNK,U,CUR,DATA,BUF,LEN,SEG,CONF
	SET U="^",NOW=$HOROLOG,CHUNK=$$CHUNK(.CONF),OUTID=""
	SET ERR("routine")="MIOOSFS"
	IF '$$VALIDNAME($GET(NAME)) SET ERR("error")="invalid_name" QUIT
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PARENT,NAME))
	IF OUTID'="",('$$EXISTS(OUTID)!($$FIELD(OUTID,1)'="file")) DO
	. KILL ^MIO("MIOOS","FS","CHILD",PARENT,NAME)
	. SET OUTID=""
	IF OUTID="" DO
	. SET OUTID=$$NEXTID()
	. DO SAVEENTRY(OUTID,"file",PARENT,NAME,$GET(MIME,"application/octet-stream"),0,NOW,NOW,$GET(OWNER),$GET(ROLES),1,1,1)
	. SET ^MIO("MIOOS","FS","CHILD",PARENT,NAME)=OUTID
	KILL ^MIO("MIOOS","FS","DATA",OUTID)
	KILL ^MIO("MIOOS","FS","HASH",OUTID)
	DO SETCHUNK(OUTID,CHUNK)
	SET BUF="",LEN=0,SEG=0
	DO PARTOPEN^MIOHTTPMPU(.MP,+$GET(IDX),.CUR,.CONF)
	FOR  QUIT:'$$PARTNEXT^MIOHTTPMPU(.MP,+$GET(IDX),.CUR,.DATA)  DO
	. SET LEN=LEN+$L($GET(DATA)),BUF=BUF_$GET(DATA)
	. FOR  QUIT:$L(BUF)<CHUNK  DO
	. . SET SEG=SEG+1
	. . SET ^MIO("MIOOS","FS","DATA",OUTID,SEG)=$E(BUF,1,CHUNK)
	. . SET BUF=$E(BUF,CHUNK+1,999999)
	DO ITCLOSE^MIOHTTPMPU(.CUR)
	IF LEN=0!(BUF'="") DO
	. SET SEG=SEG+1
	. SET ^MIO("MIOOS","FS","DATA",OUTID,SEG)=BUF
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,1)="file"
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,2)=PARENT
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,3)=NAME
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,4)=$GET(MIME,"application/octet-stream")
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,5)=LEN
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,7)=NOW
	QUIT
	;
READ(STATE,ID,OUT,ERR)
	NEW RID,I,TXT,MIME,NAME
	SET ERR("routine")="MIOOSFS",TXT=""
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF '$$CAN(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)'="file" SET ERR("error")="not_file" QUIT 0
	SET I=0 FOR  SET I=$ORDER(^MIO("MIOOS","FS","DATA",RID,I)) QUIT:I'>0  SET TXT=TXT_$GET(^MIO("MIOOS","FS","DATA",RID,I))
	SET NAME=$$FIELD(RID,3),MIME=$$FIELD(RID,4)
	SET OUT("id")=RID
	SET OUT("kind")="file"
	SET OUT("name")=NAME
	SET OUT("mime")=MIME
	SET OUT("size")=+$$FIELD(RID,5)
	SET OUT("path")=$$PATH(RID)
	IF $$TEXTLIKE(MIME,NAME)!$$ISTEXT(TXT) DO
	. SET OUT("encoding")="text"
	. SET OUT("content")=TXT
	. IF MIME=""!(MIME="application/octet-stream") SET OUT("mime")="text/plain"
	ELSE  DO
	. SET OUT("encoding")="base64-dataurl"
	. SET OUT("content")="data:"_$SELECT(MIME'="":MIME,1:"application/octet-stream")_";base64,"_$$B64E^MIOSJWT(TXT)
	QUIT 1
	;
READWIN(STATE,ID,OFFSET,LEN,OUT,ERR)
	NEW RID,SLICE,READ,TOTAL,MIME,NAME,CHKLEN,SAMPLE,FERR,NEXT
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF '$$CAN(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)'="file" SET ERR("error")="not_file" QUIT 0
	SET NAME=$$FIELD(RID,3),MIME=$$FIELD(RID,4),TOTAL=+$$FIELD(RID,5)
	IF '$$TEXTLIKE(MIME,NAME) DO
	. SET CHKLEN=$SELECT(TOTAL<4096:TOTAL,1:4096)
	. IF CHKLEN<1 QUIT
	. KILL FERR
	. IF '$$READRANGE(RID,0,CHKLEN,.SAMPLE,.READ,.FERR) DO  QUIT
	. . MERGE ERR=FERR
	. IF '$$ISTEXT(SAMPLE) SET ERR("error")="not_text_file"
	IF $DATA(ERR("error")) QUIT 0
	SET OFFSET=+$GET(OFFSET) IF OFFSET<0 SET OFFSET=0
	SET LEN=+$GET(LEN) IF LEN<1 SET LEN=16384
	KILL FERR
	IF '$$READRANGE(RID,OFFSET,LEN,.SLICE,.READ,.FERR) DO  QUIT 0
	. MERGE ERR=FERR
	. IF $GET(ERR("error"))="" SET ERR("error")="read_range_failed"
	SET NEXT=OFFSET+READ
	SET OUT("id")=RID
	SET OUT("kind")="file"
	SET OUT("name")=NAME
	SET OUT("mime")=$SELECT(MIME'="":MIME,1:"text/plain")
	IF OUT("mime")="application/octet-stream" SET OUT("mime")="text/plain"
	SET OUT("size")=TOTAL
	SET OUT("path")=$$PATH(RID)
	SET OUT("encoding")="text"
	SET OUT("offset")=OFFSET
	SET OUT("readBytes")=READ
	SET OUT("nextOffset")=NEXT
	SET OUT("eof")=$SELECT(NEXT'<TOTAL:1,1:0)
	SET OUT("truncated")=$SELECT(OUT("eof")=1:0,1:1)
	SET OUT("content")=$GET(SLICE)
	QUIT 1
	;
STORECHUNK(ID,CONF)
	NEW N,F,HAS2
	SET N=+$GET(^MIO("MIOOS","FS","INFO",$GET(ID),"chunkSize"))
	SET F=$ZLENGTH($GET(^MIO("MIOOS","FS","DATA",$GET(ID),1)))
	SET HAS2=$DATA(^MIO("MIOOS","FS","DATA",$GET(ID),2))#2
	IF N>0 DO  QUIT N
	. IF F>2048,HAS2,F'=N SET N=F,^MIO("MIOOS","FS","INFO",$GET(ID),"chunkSize")=N
	IF F>2048 DO  QUIT F
	. SET ^MIO("MIOOS","FS","INFO",$GET(ID),"chunkSize")=F
	IF $GET(ID)'="" QUIT 2048
	QUIT $$CHUNK(.CONF)
	;
SETCHUNK(ID,SIZE)
	SET ^MIO("MIOOS","FS","INFO",$GET(ID),"chunkSize")=+$GET(SIZE)
	QUIT
	;
READRAW(ID,OUT,SIZE)
	NEW RID,I
	SET OUT="",SIZE=0,RID=$GET(ID)
	IF '$$EXISTS(RID) QUIT 0
	IF $$FIELD(RID,1)'="file" QUIT 0
	SET I=0 FOR  SET I=$ORDER(^MIO("MIOOS","FS","DATA",RID,I)) QUIT:I'>0  SET OUT=OUT_$GET(^MIO("MIOOS","FS","DATA",RID,I))
	SET SIZE=$ZLENGTH(OUT)
	QUIT 1
	;
READRANGE(ID,OFFSET,LEN,OUT,READ,ERR)
	NEW RID,TOTAL,CHSZ,POS,REMAIN,IDX,SEG,SEGBYTES,OFFINSEG,TAKE,PART,SEND
	SET ERR("routine")="MIOOSFS",OUT="",READ=0
	SET RID=$GET(ID)
	IF '$$EXISTS(RID)!($$FIELD(RID,1)'="file") SET ERR("error")="not_file" QUIT 0
	SET TOTAL=+$$FIELD(RID,5)
	SET OFFSET=+$GET(OFFSET),LEN=+$GET(LEN)
	IF OFFSET<0 SET OFFSET=0
	IF LEN<0 SET LEN=0
	IF LEN=0!(OFFSET>=TOTAL) QUIT 1
	SET CHSZ=$$STORECHUNK(RID),POS=OFFSET,REMAIN=LEN
	FOR  QUIT:(REMAIN<1)!(POS>=TOTAL)  DO
	. SET IDX=(POS\CHSZ)+1
	. SET SEG=$GET(^MIO("MIOOS","FS","DATA",RID,IDX))
	. SET SEGBYTES=$ZLENGTH(SEG)
	. IF SEGBYTES<1 SET ERR("error")="range_segment_missing",ERR("detail")=IDX QUIT
	. SET OFFINSEG=(POS#CHSZ)+1
	. SET TAKE=(SEGBYTES-OFFINSEG)+1
	. IF TAKE>REMAIN SET TAKE=REMAIN
	. IF (POS+TAKE)>TOTAL SET TAKE=TOTAL-POS
	. IF TAKE<1 SET REMAIN=0 QUIT
	. SET PART=$SELECT(OFFINSEG=1&(TAKE=SEGBYTES):SEG,1:$ZEXTRACT(SEG,OFFINSEG,OFFINSEG+TAKE-1))
	. SET SEND=$ZLENGTH(PART)
	. IF SEND<1 SET ERR("error")="range_segment_empty",ERR("detail")=IDX QUIT
	. SET OUT=OUT_PART,READ=READ+SEND,POS=POS+SEND,REMAIN=REMAIN-SEND
	IF $DATA(ERR("error")) SET OUT="",READ=0 QUIT 0
	QUIT 1
	;
HASH(STATE,ID,OUT,ERR)
	NEW RID,TXT,SIZE
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF '$$CAN(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF '$$READRAW(RID,.TXT,.SIZE) SET ERR("error")="not_file" QUIT 0
	SET OUT("id")=RID
	SET OUT("name")=$$FIELD(RID,3)
	SET OUT("path")=$$PATH(RID)
	SET OUT("mime")=$$FIELD(RID,4)
	SET OUT("size")=SIZE
	IF $GET(^MIO("MIOOS","FS","HASH",RID))="" SET ^MIO("MIOOS","FS","HASH",RID)=$$SHA256^MIOSHA256(TXT)
	SET OUT("sha256")=$GET(^MIO("MIOOS","FS","HASH",RID))
	QUIT 1
	;
SEARCH(STATE,PARENT,QUERY,RECURSE,LIMIT,OUT,ERR)
	NEW PID,TERM,COUNT
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	SET TERM=$$LOW^MIOUTIL($$TRIM^MIOUTIL($GET(QUERY)))
	SET LIMIT=+$GET(LIMIT) IF LIMIT<1 SET LIMIT=50
	SET OUT("folder","id")=PID
	SET OUT("folder","path")=$$PATH(PID)
	SET OUT("query")=$GET(QUERY)
	SET OUT("recurse")=+$GET(RECURSE)
	SET OUT("limit")=LIMIT
	SET COUNT=0
	DO SEARCH1(.STATE,PID,TERM,+$GET(RECURSE),LIMIT,.COUNT,$NAME(OUT("entries")),.ERR)
	SET OUT("count")=COUNT
	QUIT 1
	;
SEARCH1(STATE,PID,TERM,RECURSE,LIMIT,COUNT,ROOT,ERR)
	NEW NAME,ID,META,LOW,OK
	SET NAME=""
	FOR  SET NAME=$ORDER(^MIO("MIOOS","FS","CHILD",PID,NAME)) QUIT:NAME=""!(COUNT'<LIMIT)  DO
	. SET ID=$GET(^MIO("MIOOS","FS","CHILD",PID,NAME))
	. IF '$$CAN(ID,.STATE,"read") QUIT
	. SET LOW=$$LOW^MIOUTIL($GET(NAME))
	. IF TERM=""!(LOW[TERM) DO
	. . KILL META
	. . SET OK=$$META(.STATE,ID,.META,.ERR)
	. . IF OK DO
	. . . SET COUNT=COUNT+1
	. . . MERGE @ROOT@(COUNT)=META
	. IF RECURSE,$$FIELD(ID,1)="folder",COUNT<LIMIT DO SEARCH1(.STATE,ID,TERM,RECURSE,LIMIT,.COUNT,ROOT,.ERR)
	QUIT
	;
META(STATE,ID,OUT,ERR)
	NEW RID
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT:$Q 0 QUIT
	IF '$$CAN(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT:$Q 0 QUIT
	SET OUT("id")=RID
	SET OUT("kind")=$$FIELD(RID,1)
	SET OUT("parentId")=$$FIELD(RID,2)
	SET OUT("name")=$$FIELD(RID,3)
	SET OUT("mime")=$$FIELD(RID,4)
	SET OUT("size")=+$$FIELD(RID,5)
	SET OUT("createdAt")=$$FIELD(RID,6)
	SET OUT("modifiedAt")=$$FIELD(RID,7)
	SET OUT("owner")=$$FIELD(RID,8)
	SET OUT("roles")=$$FIELD(RID,9)
	SET OUT("permRead")=+$$FIELD(RID,10)
	SET OUT("permWrite")=+$$FIELD(RID,11)
	SET OUT("permDelete")=+$$FIELD(RID,12)
	SET OUT("path")=$$PATH(RID)
	QUIT:$Q 1 QUIT
	;
LIST(STATE,PARENT,OUT,ERR)
	NEW PID,NAME,N,ID,META,OK
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	KILL META
	SET OK=$$META(.STATE,PID,.META,.ERR)
	IF 'OK QUIT 0
	MERGE OUT("folder")=META
	SET N=0,NAME=""
	FOR  SET NAME=$ORDER(^MIO("MIOOS","FS","CHILD",PID,NAME)) QUIT:NAME=""  DO
	. SET ID=$GET(^MIO("MIOOS","FS","CHILD",PID,NAME))
	. IF '$$CAN(ID,.STATE,"read") QUIT
	. KILL META
	. SET OK=$$META(.STATE,ID,.META,.ERR)
	. IF 'OK QUIT
	. SET N=N+1
	. MERGE OUT("entries",N)=META
	SET OUT("count")=N
	QUIT 1
	;
RENAME(STATE,ID,NEWNAME,OUT,ERR)
	NEW RID,PID,OLD,U
	SET U="^",ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$VALIDNAME($GET(NEWNAME)) SET ERR("error")="invalid_name" QUIT 0
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	SET PID=$$FIELD(RID,2),OLD=$$FIELD(RID,3)
	IF PID="" SET ERR("error")="rename_root_forbidden" QUIT 0
	IF '$$CAN(RID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	IF NEWNAME'=OLD,$GET(^MIO("MIOOS","FS","CHILD",PID,NEWNAME))'="" SET ERR("error")="name_conflict" QUIT 0
	KILL ^MIO("MIOOS","FS","CHILD",PID,OLD)
	SET ^MIO("MIOOS","FS","CHILD",PID,$GET(NEWNAME))=RID
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,3)=$GET(NEWNAME)
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,7)=$HOROLOG
	DO META(.STATE,RID,.OUT,.ERR)
	QUIT 1
	;
ISDESC(ANCESTOR,ID)
	NEW CUR,FOUND
	SET CUR=$GET(ID),FOUND=0
	FOR  QUIT:CUR=""!(FOUND=1)  DO
	. IF CUR=$GET(ANCESTOR) SET FOUND=1 QUIT
	. SET CUR=$$FIELD(CUR,2)
	QUIT FOUND
	;
MOVE(STATE,ID,NEWPARENT,OUT,ERR)
	NEW RID,NPID,OPID,NAME,U
	SET U="^",ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF RID="root" SET ERR("error")="move_root_forbidden" QUIT 0
	IF '$$RESOLVE($GET(NEWPARENT),.NPID,.ERR) QUIT 0
	IF $$FIELD(NPID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF ('$$CAN(RID,.STATE,"write"))!('$$CAN(NPID,.STATE,"write")) SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)="folder",$$ISDESC(RID,NPID) SET ERR("error")="move_cycle_forbidden" QUIT 0
	SET OPID=$$FIELD(RID,2),NAME=$$FIELD(RID,3)
	IF $GET(^MIO("MIOOS","FS","CHILD",NPID,NAME))'="",$GET(^MIO("MIOOS","FS","CHILD",NPID,NAME))'=RID SET ERR("error")="name_conflict" QUIT 0
	IF OPID'="" KILL ^MIO("MIOOS","FS","CHILD",OPID,NAME)
	SET ^MIO("MIOOS","FS","CHILD",NPID,NAME)=RID
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,2)=NPID
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,7)=$HOROLOG
	DO META(.STATE,RID,.OUT,.ERR)
	QUIT 1
	;
COPY(STATE,ID,NEWPARENT,NEWNAME,OUT,ERR)
	NEW RID,NPID,NAME,COPYID
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF RID="root" SET ERR("error")="copy_root_forbidden" QUIT 0
	IF '$$RESOLVE($GET(NEWPARENT),.NPID,.ERR) QUIT 0
	IF $$FIELD(NPID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF ('$$CAN(RID,.STATE,"read"))!('$$CAN(NPID,.STATE,"write")) SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)="folder",$$ISDESC(RID,NPID) SET ERR("error")="copy_cycle_forbidden" QUIT 0
	SET NAME=$GET(NEWNAME) IF NAME="" SET NAME=$$FIELD(RID,3)
	IF '$$VALIDNAME(NAME) SET ERR("error")="invalid_name" QUIT 0
	IF $GET(^MIO("MIOOS","FS","CHILD",NPID,NAME))'="" SET ERR("error")="name_conflict" QUIT 0
	IF '$$COPYREC(.STATE,RID,NPID,NAME,.COPYID,.ERR) QUIT 0
	DO META(.STATE,COPYID,.OUT,.ERR)
	QUIT 1
	;
COPYREC(STATE,SRC,PARENT,NAME,OUTID,ERR)
	NEW KIND,MIME,SIZE,NOW,OWNER,ROLES,CANR,CANW,CAND,CHILD,CHILDID,NEWID,OK,TMP,IDX
	SET KIND=$$FIELD(SRC,1),MIME=$$FIELD(SRC,4),SIZE=+$$FIELD(SRC,5)
	SET NOW=$HOROLOG,OWNER=$$FIELD(SRC,8),ROLES=$$FIELD(SRC,9)
	SET CANR=+$$FIELD(SRC,10),CANW=+$$FIELD(SRC,11),CAND=+$$FIELD(SRC,12)
	SET NEWID=$$NEXTID(),OUTID=NEWID
	IF KIND="folder" DO  QUIT 1
	. DO SAVEENTRY(NEWID,"folder",PARENT,NAME,"inode/directory",0,NOW,NOW,OWNER,ROLES,CANR,CANW,CAND)
	. SET ^MIO("MIOOS","FS","CHILD",PARENT,NAME)=NEWID
	. SET CHILD="",OK=1
	. FOR  SET CHILD=$ORDER(^MIO("MIOOS","FS","CHILD",SRC,CHILD)) QUIT:CHILD=""!(OK=0)  DO
	. . SET CHILDID=$GET(^MIO("MIOOS","FS","CHILD",SRC,CHILD))
	. . IF '$$COPYREC(.STATE,CHILDID,NEWID,CHILD,.TMP,.ERR) SET OK=0
	. IF 'OK SET ERR("error")=$SELECT($GET(ERR("error"))'="":$GET(ERR("error")),1:"copy_failed") QUIT 0
	DO SAVEENTRY(NEWID,"file",PARENT,NAME,$SELECT(MIME'="":MIME,1:"application/octet-stream"),SIZE,NOW,NOW,OWNER,ROLES,CANR,CANW,CAND)
	SET ^MIO("MIOOS","FS","CHILD",PARENT,NAME)=NEWID
	KILL ^MIO("MIOOS","FS","DATA",NEWID)
	DO SETCHUNK(NEWID,$$STORECHUNK(SRC))
	SET IDX=0 FOR  SET IDX=$ORDER(^MIO("MIOOS","FS","DATA",SRC,IDX)) QUIT:IDX'>0  SET ^MIO("MIOOS","FS","DATA",NEWID,IDX)=$GET(^MIO("MIOOS","FS","DATA",SRC,IDX))
	IF SIZE=0,'$DATA(^MIO("MIOOS","FS","DATA",NEWID,1)) SET ^MIO("MIOOS","FS","DATA",NEWID,1)=""
	KILL ^MIO("MIOOS","FS","HASH",NEWID)
	IF $DATA(^MIO("MIOOS","FS","HASH",SRC)) SET ^MIO("MIOOS","FS","HASH",NEWID)=$GET(^MIO("MIOOS","FS","HASH",SRC))
	QUIT 1
	;
DELETE(STATE,ID,OUT,ERR)
	NEW RID,PID,NAME
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF RID="root" SET ERR("error")="delete_root_forbidden" QUIT 0
	IF '$$CAN(RID,.STATE,"delete") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)="folder",$ORDER(^MIO("MIOOS","FS","CHILD",RID,""))'="" SET ERR("error")="folder_not_empty" QUIT 0
	SET PID=$$FIELD(RID,2),NAME=$$FIELD(RID,3)
	KILL ^MIO("MIOOS","FS","DATA",RID)
	KILL ^MIO("MIOOS","FS","CHILD",RID)
	KILL ^MIO("MIOOS","FS","HASH",RID)
	KILL ^MIO("MIOOS","FS","INFO",RID)
	KILL ^MIO("MIOOS","FS","ENTRY",RID)
	IF PID'="" KILL ^MIO("MIOOS","FS","CHILD",PID,NAME)
	SET OUT("id")=RID,OUT("deleted")=1
	QUIT 1
	;
	;