MIOOSTRXDN ; MIOOS transfer download foundation
	QUIT
	;
BEGIN(STATE,CONF,TREE,OUT,ERR)
	NEW META,ID,FILEID,FOUT,SIZE,CSZ,COUNT
	KILL OUT
	SET ERR("routine")="MIOOSTRXDN"
	SET FILEID=$SELECT($GET(TREE("id"))'="":$GET(TREE("id")),1:$GET(TREE("path")))
	IF FILEID="" SET ERR("error")="file_missing" QUIT 0
	IF '$$READ^MIOOSFS(.STATE,FILEID,.FOUT,.ERR) QUIT 0
	SET SIZE=+$GET(FOUT("size")),CSZ=$$CHUNK^MIOOSTRX(.CONF)
	SET COUNT=$SELECT(SIZE<1:0,1:((SIZE-1)\CSZ)+1)
	SET META("id")=$GET(FOUT("id")),META("name")=$GET(FOUT("name")),META("mime")=$GET(FOUT("mime")),META("sizeBytes")=SIZE,META("path")=$GET(FOUT("path"))
	SET META("kind")="download",META("protocol")=1
	SET ID=$$INIT^MIOOSTRX(.STATE,.CONF,"download",.META,.OUT,.ERR)
	IF ID="" QUIT 0
	SET ^MIO("MIOOS","TRANSFER",ID,"bytesTotal")=SIZE
	SET ^MIO("MIOOS","TRANSFER",ID,"chunkTotal")=COUNT
	SET ^MIO("MIOOS","TRANSFER",ID,"fileId")=$GET(FOUT("id"))
	DO SNAP^MIOOSTRX(ID,.OUT)
	QUIT 1
	;
CHUNK(STATE,CONF,TREE,OUT,ERR)
	NEW ID,IDX,FILEID,FOUT,CSZ,START,STOP,TXT,LEN,WORKER
	KILL OUT
	SET ERR("routine")="MIOOSTRXDN"
	SET ID=$GET(TREE("transferId"))
	IF '$$OWNOK^MIOOSTRX(.STATE,ID,.ERR) QUIT 0
	IF $GET(^MIO("MIOOS","TRANSFER",ID,"direction"))'="download" SET ERR("error")="direction_mismatch" QUIT 0
	IF $GET(^MIO("MIOOS","TRANSFER",ID,"state"))'="active" SET ERR("error")="transfer_not_active" QUIT 0
	SET FILEID=$GET(^MIO("MIOOS","TRANSFER",ID,"fileId")) IF FILEID="" SET ERR("error")="file_missing" QUIT 0
	SET IDX=+$GET(TREE("chunkIndex")) IF IDX<1 SET ERR("error")="chunk_index_invalid" QUIT 0
	SET WORKER=$GET(TREE("workerId"))
	IF '$$READ^MIOOSFS(.STATE,FILEID,.FOUT,.ERR) QUIT 0
	SET CSZ=+$GET(^MIO("MIOOS","TRANSFER",ID,"chunkSize")) IF CSZ<1 SET CSZ=$$CHUNK^MIOOSTRX(.CONF)
	SET START=((IDX-1)*CSZ)+1,STOP=START+CSZ-1
	SET TXT=$EXTRACT($GET(FOUT("content")),START,STOP),LEN=$LENGTH(TXT)
	SET OUT("transferId")=ID,OUT("chunkIndex")=IDX,OUT("data")=TXT
	SET OUT("bytes")=LEN,OUT("mime")=$GET(FOUT("mime")),OUT("name")=$GET(FOUT("name"))
	IF WORKER'="" SET OUT("workerId")=WORKER,^MIO("MIOOS","TRANSFER",ID,"worker",WORKER,"lastChunk")=IDX,^MIO("MIOOS","TRANSFER",ID,"worker",WORKER,"updatedAt")=$HOROLOG
	IF $DATA(^MIO("MIOOS","TRANSFER",ID,"sent",IDX))#2=0 DO
	. SET ^MIO("MIOOS","TRANSFER",ID,"sent",IDX)=LEN
	. SET ^MIO("MIOOS","TRANSFER",ID,"chunkSent")=$GET(^MIO("MIOOS","TRANSFER",ID,"chunkSent"))+1
	. SET ^MIO("MIOOS","TRANSFER",ID,"bytesDone")=$GET(^MIO("MIOOS","TRANSFER",ID,"bytesDone"))+LEN
	DO TOUCH^MIOOSTRX(ID)
	QUIT 1
	;
END(STATE,CONF,TREE,OUT,ERR)
	NEW ID
	KILL OUT
	SET ERR("routine")="MIOOSTRXDN"
	SET ID=$GET(TREE("transferId"))
	IF '$$OWNOK^MIOOSTRX(.STATE,ID,.ERR) QUIT 0
	DO DONE^MIOOSTRX(ID,$GET(^MIO("MIOOS","TRANSFER",ID,"fileId")))
	DO SNAP^MIOOSTRX(ID,.OUT)
	QUIT 1
	;
ABORT(STATE,CONF,TREE,OUT,ERR)
	QUIT $$ABORT^MIOOSTRX(.STATE,$GET(TREE("transferId")),.OUT,.ERR)
	;
STATUS(STATE,CONF,TREE,OUT,ERR)
	NEW ID
	KILL OUT
	SET ERR("routine")="MIOOSTRXDN"
	SET ID=$GET(TREE("transferId"))
	IF '$$OWNOK^MIOOSTRX(.STATE,ID,.ERR) QUIT 0
	DO SNAP^MIOOSTRX(ID,.OUT)
	QUIT 1
	;
