MIOOSUI ; MIOOS UI helpers
	QUIT
	;
DESKCTX(STATE,CONF,DATA)
	KILL DATA
	SET DATA("page","title")=$GET(STATE("brandTitle"),"MIOOS")_" "_$$TXT^MIOOSI18N($GET(STATE("localeCode"),"en"),"page.desktop","Desktop")
	SET DATA("brandTitle")=$GET(STATE("brandTitle"),"MIOOS")
	SET DATA("brandSubtitle")=$GET(STATE("brandSubtitle"),"MUMPS-powered web desktop shell")
	SET DATA("profile")=$GET(STATE("profile"),"dev")
	SET DATA("sessionId")=$GET(STATE("sessionId"))
	SET DATA("desktopPath")=$GET(STATE("desktopPath"))
	SET DATA("bootstrapPath")=$GET(STATE("bootstrapPath"))
	SET DATA("viewPath")=$GET(STATE("viewPath"))
	SET DATA("fsUploadPath")=$GET(STATE("fsUploadPath"))
	SET DATA("fsUploadBeginPath")=$GET(STATE("fsUploadBeginPath"))
	SET DATA("fsUploadChunkPath")=$GET(STATE("fsUploadChunkPath"))
	SET DATA("fsUploadStatusPath")=$GET(STATE("fsUploadStatusPath"))
	SET DATA("fsUploadCommitPath")=$GET(STATE("fsUploadCommitPath"))
	SET DATA("fsUploadAbortPath")=$GET(STATE("fsUploadAbortPath"))
	SET DATA("fsCopyPath")=$GET(STATE("fsCopyPath"))
	SET DATA("signinPath")=$GET(STATE("signinPath"))
	SET DATA("signoutPath")=$GET(STATE("signoutPath"))
	SET DATA("guestSigninPath")=$GET(STATE("guestSigninPath"))
	SET DATA("wsPath")=$GET(STATE("wsPath"))
	SET DATA("wsTerminalPath")=$GET(STATE("wsTerminalPath"))
	SET DATA("wsMaxSockets")=+$GET(STATE("wsMaxSockets"),4)
	SET DATA("wsFsSockets")=+$GET(STATE("wsFsSockets"),3)
	SET DATA("commandEvent")=$GET(STATE("commandEvent"),"desktop.command")
	SET DATA("commandResultEvent")=$GET(STATE("commandResultEvent"),"desktop.result")
	SET DATA("themeKey")=$GET(STATE("themeKey"),"foundation-light")
	SET DATA("wallpaper")=$GET(STATE("wallpaper"),"aurora")
	SET DATA("density")=$GET(STATE("density"),"comfortable")
	SET DATA("launcherLabel")=$GET(STATE("launcherLabel"),"Menu")
	SET DATA("shellChrome")=$GET(STATE("shellChrome"),"shell-foundation")
	SET DATA("taskbarStyle")=$GET(STATE("taskbarStyle"),"taskbar-foundation")
	SET DATA("startMenuStyle")=$GET(STATE("startMenuStyle"),"launcher-foundation")
	SET DATA("shellDialogModel")=$GET(STATE("shellDialogModel"),"shell-modal")
	SET DATA("windowManager")=$GET(STATE("windowManager"),"mioos-native-vue-css")
	SET DATA("themeMode")=$GET(STATE("themeMode"),"light")
	SET DATA("motionPreference")=$GET(STATE("a11yMotionPreference"),"respect-user-preference")
	SET DATA("windowSnapThreshold")=+$GET(STATE("windowSnapThreshold"),28)
	SET DATA("windowResizeModel")="all-edges-and-corners"
	SET DATA("authRequired")=+$GET(STATE("authRequired"),0)
	SET DATA("localAuthEnabled")=+$GET(STATE("localAuthEnabled"),0)
	SET DATA("guestLoginEnabled")=+$GET(STATE("guestLoginEnabled"),0)
	SET DATA("localeCode")=$GET(STATE("localeCode"),"en")
	SET DATA("localeDir")=$GET(STATE("localeDir"),"ltr")
	SET DATA("bootJson")=$$BOOTJSON^MIOOSST(.STATE,.CONF)
	QUIT
	;