MIOOSFSDN ; MIOOS chunked downloads
	QUIT
	;
SESSIONKEY(STATE)
	QUIT $GET(STATE("sessionId"),"mioos-shell")_":"_$GET(STATE("principal"),"guest")
	;
NEXTID()
	NEW N
	SET N=$INCREMENT(^MIO("MIOOS","DL","SEQ"))
	QUIT "dl-"_N
	;
BEGIN(STATE,CONF,ID,OUT,ERR)
	NEW RID,SKEY,DLID,SIZE,CHUNK,RAW,RAWSIZE
	SET ERR("routine")="MIOOSFSDN"
	IF '$$RESOLVE^MIOOSFS($GET(ID),.RID,.ERR) QUIT 0
	IF '$$CAN^MIOOSFS(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD^MIOOSFS(RID,1)'="file" SET ERR("error")="not_file" QUIT 0
	SET SIZE=+$$FIELD^MIOOSFS(RID,5)
	IF '$$READRAW^MIOOSFS(RID,.RAW,.RAWSIZE) SET ERR("error")="not_file" QUIT 0
	SET CHUNK=+$GET(CONF("mioos","fs","downloadChunkSize"))
	IF CHUNK<256 SET CHUNK=+$GET(CONF("mioos","upload","chunkBytes"),32768)
	IF CHUNK<256 SET CHUNK=32768
	IF CHUNK>65536 SET CHUNK=65536
	SET SKEY=$$SESSIONKEY(.STATE),DLID=$$NEXTID()
	KILL ^MIO("MIOOS","DL",SKEY,DLID)
	SET ^MIO("MIOOS","DL",SKEY,DLID,"fileId")=RID
	SET ^MIO("MIOOS","DL",SKEY,DLID,"size")=SIZE
	SET ^MIO("MIOOS","DL",SKEY,DLID,"chunkSize")=CHUNK
	SET OUT("downloadId")=DLID
	SET OUT("id")=RID
	SET OUT("name")=$$FIELD^MIOOSFS(RID,3)
	SET OUT("mime")=$$FIELD^MIOOSFS(RID,4)
	SET OUT("size")=SIZE
	SET OUT("transferBytes")=RAWSIZE
	SET OUT("path")=$$PATH^MIOOSFS(RID)
	SET OUT("chunkSize")=CHUNK
	QUIT 1
	;
CHUNK(STATE,DLID,OFFSET,SIZE,OUT,ERR)
	NEW SKEY,RID,RAW,RAWSIZE,REQSIZE,NEXTOFF,SLICE
	SET ERR("routine")="MIOOSFSDN"
	SET SKEY=$$SESSIONKEY(.STATE)
	IF $GET(DLID)="" SET ERR("error")="download_missing" QUIT 0
	SET RID=$GET(^MIO("MIOOS","DL",SKEY,DLID,"fileId"))
	IF RID="" SET ERR("error")="download_not_found" QUIT 0
	IF '$$CAN^MIOOSFS(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF '$$READRAW^MIOOSFS(RID,.RAW,.RAWSIZE) SET ERR("error")="not_file" QUIT 0
	SET OFFSET=+$GET(OFFSET) IF OFFSET<0 SET OFFSET=0
	SET REQSIZE=+$GET(SIZE) IF REQSIZE<1 SET REQSIZE=+$GET(^MIO("MIOOS","DL",SKEY,DLID,"chunkSize"),32768)
	SET SLICE=$EXTRACT(RAW,OFFSET+1,OFFSET+REQSIZE)
	SET NEXTOFF=OFFSET+$LENGTH(SLICE)
	SET OUT("downloadId")=DLID
	SET OUT("id")=RID
	SET OUT("name")=$$FIELD^MIOOSFS(RID,3)
	SET OUT("mime")=$$FIELD^MIOOSFS(RID,4)
	SET OUT("offset")=OFFSET
	SET OUT("size")=$LENGTH(SLICE)
	SET OUT("nextOffset")=NEXTOFF
	SET OUT("totalBytes")=RAWSIZE
	SET OUT("eof")=$SELECT(NEXTOFF'<RAWSIZE:1,1:0)
	SET OUT("data")=SLICE
	QUIT 1
	;
ABORT(STATE,DLID,OUT,ERR)
	NEW SKEY
	SET ERR("routine")="MIOOSFSDN"
	SET SKEY=$$SESSIONKEY(.STATE)
	IF $GET(DLID)="" SET ERR("error")="download_missing" QUIT 0
	KILL ^MIO("MIOOS","DL",SKEY,DLID)
	SET OUT("downloadId")=DLID
	SET OUT("aborted")=1
	QUIT 1
	;
