MIOOSFSUP ; MIOOS chunked upload helpers
	QUIT
	;
UPCHUNK(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","upload","chunkBytes"),32768)
	IF N<4096 SET N=4096
	IF N>32768 SET N=32768
	QUIT N
	;
UPCONCUR(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","upload","concurrency"),7)
	IF N<1 SET N=1
	IF N>7 SET N=7
	QUIT N
	;
NEXTUP()
	NEW N
	SET N=$INCREMENT(^MIO("MIOOS","UPLOAD","SEQ"))
	QUIT "up-"_N
	;
BEGIN(STATE,CONF,PARENT,NAME,MIME,TOTAL,ENCODING,OUT,ERR)
	NEW PID,UPID,OWNER,ROLES,NOW
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	IF '$$RESOLVE^MIOOSFS($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD^MIOOSFS(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN^MIOOSFS(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	IF $GET(NAME)="" SET ERR("error")="name_missing" QUIT 0
	SET UPID=$$NEXTUP()
	SET OWNER=$GET(STATE("principal"),"guest")
	SET ROLES=$GET(STATE("roles"),"guest")
	SET NOW=$HOROLOG
	SET ^MIO("MIOOS","UPLOAD","META",UPID)=PID_"^"_$GET(NAME)_"^"_$GET(MIME,"application/octet-stream")_"^"_OWNER_"^"_ROLES_"^"_$GET(ENCODING,"base64-dataurl")_"^"_(+$GET(TOTAL))_"^"_NOW
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"chunks")=0
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"bytes")=0
	SET OUT("uploadId")=UPID
	SET OUT("parentId")=PID
	SET OUT("name")=$GET(NAME)
	SET OUT("mime")=$GET(MIME,"application/octet-stream")
	SET OUT("encoding")=$GET(ENCODING,"base64-dataurl")
	SET OUT("chunkBytes")=$$UPCHUNK(.CONF)
	SET OUT("strategy")="chunked"
	SET OUT("concurrencyDefault")=$$UPCONCUR(.CONF)
	QUIT 1
	;
CHUNK(STATE,CONF,UPLOADID,INDEX,DATA,OUT,ERR)
	NEW META,OWNER,RECV
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	IF +$GET(INDEX)<1 SET ERR("error")="chunk_index_invalid" QUIT 0
	SET ^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,+INDEX)=$GET(DATA)
	SET RECV=$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes"))+$LENGTH($GET(DATA))
	SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes")=RECV
	IF +$GET(INDEX)>+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")) SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")=+INDEX
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("index")=+INDEX
	SET OUT("receivedBytes")=RECV
	QUIT 1
	;
BATCH(STATE,CONF,UPLOADID,CHROOT,OUT,ERR)
	NEW META,OWNER,I,COUNT,IDX,DATA,RECV,MAXIDX
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	SET (I,COUNT,MAXIDX)=0,RECV=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes"))
	FOR  SET I=$ORDER(@CHROOT@(I)) QUIT:I'>0  DO
	. SET IDX=+$GET(@CHROOT@(I,"index"))
	. SET DATA=$GET(@CHROOT@(I,"data"))
	. IF IDX<1 SET ERR("error")="chunk_index_invalid" QUIT
	. SET ^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,IDX)=DATA
	. SET RECV=RECV+$LENGTH(DATA)
	. IF IDX>MAXIDX SET MAXIDX=IDX
	. SET COUNT=COUNT+1
	IF $DATA(ERR("error")) QUIT 0
	SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes")=RECV
	IF MAXIDX>+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")) SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")=MAXIDX
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("batchCount")=COUNT
	SET OUT("highestIndex")=MAXIDX
	SET OUT("receivedBytes")=RECV
	QUIT 1
	;
COMMIT(STATE,CONF,UPLOADID,OUT,ERR)
	NEW META,PID,NAME,MIME,OWNER,ROLES,ENC,OUTID,NOW,IDX,BUF,SIZE,CHSZ,PREFIX,TEMP,OK
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET PID=$PIECE(META,"^",1),NAME=$PIECE(META,"^",2),MIME=$PIECE(META,"^",3)
	SET OWNER=$PIECE(META,"^",4),ROLES=$PIECE(META,"^",5),ENC=$PIECE(META,"^",6)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	IF '$$CAN^MIOOSFS(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	SET NOW=$HOROLOG,CHSZ=$$CHUNK^MIOOSFS(.CONF)
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PID,NAME))
	IF OUTID="" DO
	. SET OUTID=$$NEXTID^MIOOSFS()
	. DO SAVEENTRY^MIOOSFS(OUTID,"file",PID,NAME,$GET(MIME,"application/octet-stream"),0,NOW,NOW,OWNER,ROLES,1,1,1)
	. SET ^MIO("MIOOS","FS","CHILD",PID,NAME)=OUTID
	ELSE  DO
	. KILL ^MIO("MIOOS","FS","DATA",OUTID)
	SET IDX=0,BUF="",SIZE=0
	IF ENC="base64-dataurl" DO
	. SET PREFIX="data:"_$GET(MIME,"application/octet-stream")_";base64,"
	. DO APPEND(OUTID,PREFIX,.IDX,.BUF,.SIZE,CHSZ)
	SET TEMP=0 FOR  SET TEMP=$ORDER(^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,TEMP)) QUIT:TEMP'>0  DO
	. DO APPEND(OUTID,$GET(^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,TEMP)),.IDX,.BUF,.SIZE,CHSZ)
	IF BUF'="" DO
	. SET IDX=IDX+1
	. SET ^MIO("MIOOS","FS","DATA",OUTID,IDX)=BUF
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),"^",4)=$GET(MIME,"application/octet-stream")
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),"^",5)=SIZE
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),"^",7)=NOW
	DO CLEAN(UPLOADID)
	SET OK=$$META^MIOOSFS(.STATE,OUTID,.OUT,.ERR)
	IF 'OK QUIT 0
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("committed")=1
	QUIT 1
	;
ABORT(STATE,CONF,UPLOADID,OUT,ERR)
	NEW META,OWNER
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	DO CLEAN($GET(UPLOADID))
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("aborted")=1
	QUIT 1
	;
APPEND(ID,SEG,IDX,BUF,SIZE,CHSZ)
	SET SIZE=+$GET(SIZE)+$LENGTH($GET(SEG))
	SET BUF=$GET(BUF)_$GET(SEG)
	FOR  QUIT:$LENGTH(BUF)<+$GET(CHSZ)  DO
	. SET IDX=+$GET(IDX)+1
	. SET ^MIO("MIOOS","FS","DATA",ID,IDX)=$EXTRACT(BUF,1,CHSZ)
	. SET BUF=$EXTRACT(BUF,CHSZ+1,1048576)
	QUIT
	;
CLEAN(UPLOADID)
	KILL ^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID))
	KILL ^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID))
	KILL ^MIO("MIOOS","UPLOAD","CHUNK",$GET(UPLOADID))
	QUIT
