MIOOSTHEME ; MIOOS globals-backed theme profiles
	QUIT
	;
USERKEY(STATE)
	NEW KEY
	SET KEY=$$TRIM^MIOUTIL($GET(STATE("principal")))
	IF KEY="" SET KEY=$$TRIM^MIOUTIL($GET(STATE("userName")))
	IF KEY="" SET KEY="guest"
	QUIT $$LOW^MIOUTIL(KEY)
	;
NEXTKEY(USER)
	NEW N
	SET N=$INCREMENT(^MIO("MIOOS","THEME","SEQ",$GET(USER)))
	QUIT "theme-"_N
	;

ACTIVE(STATE,OUT)
	NEW USER,KEY
	KILL OUT
	SET USER=$$USERKEY(.STATE)
	SET KEY=$GET(^MIO("MIOOS","THEME","ACTIVE",USER))
	IF KEY="" QUIT 0
	IF '$DATA(^MIO("MIOOS","THEME","PROFILE",USER,KEY)) QUIT 0
	MERGE OUT=^MIO("MIOOS","THEME","PROFILE",USER,KEY)
	SET OUT("key")=KEY
	QUIT 1
	;
LOAD(STATE,CONF,OUT,ERR)
	NEW USER,KEY,IDX,ACTIVE,REQKEY
	SET USER=$$USERKEY(.STATE)
	SET REQKEY=$GET(STATE("themeRequest","key"))
	KILL OUT
	SET OUT("ok")=1,OUT("user")=USER
	SET ACTIVE=$GET(^MIO("MIOOS","THEME","ACTIVE",USER))
	SET OUT("activeKey")=ACTIVE
	IF REQKEY="" SET REQKEY=ACTIVE
	IF REQKEY'="",$DATA(^MIO("MIOOS","THEME","PROFILE",USER,REQKEY)) DO
	. MERGE OUT("profile")=^MIO("MIOOS","THEME","PROFILE",USER,REQKEY)
	. SET OUT("profileKey")=REQKEY
	SET KEY="",IDX=0
	FOR  SET KEY=$ORDER(^MIO("MIOOS","THEME","PROFILE",USER,KEY)) QUIT:KEY=""  DO
	. SET IDX=IDX+1
	. SET OUT("profiles",IDX,"key")=KEY
	. SET OUT("profiles",IDX,"name")=$GET(^MIO("MIOOS","THEME","PROFILE",USER,KEY,"name"))
	. SET OUT("profiles",IDX,"family")=$GET(^MIO("MIOOS","THEME","PROFILE",USER,KEY,"family"))
	. SET OUT("profiles",IDX,"mode")=$GET(^MIO("MIOOS","THEME","PROFILE",USER,KEY,"mode"))
	. MERGE OUT("profiles",IDX,"data")=^MIO("MIOOS","THEME","PROFILE",USER,KEY)
	QUIT 1
	;
SAVE(STATE,CONF,IN,OUT,ERR)
	NEW USER,KEY,ACTIVATE
	SET USER=$$USERKEY(.STATE)
	SET KEY=$GET(IN("key"))
	IF KEY="" SET KEY=$$NEXTKEY(USER)
	SET ACTIVATE=+$GET(IN("activate"))
	KILL ^MIO("MIOOS","THEME","PROFILE",USER,KEY)
	IF $DATA(IN("profile")) MERGE ^MIO("MIOOS","THEME","PROFILE",USER,KEY)=IN("profile")
	ELSE  MERGE ^MIO("MIOOS","THEME","PROFILE",USER,KEY)=IN
	SET ^MIO("MIOOS","THEME","PROFILE",USER,KEY,"key")=KEY
	IF ACTIVATE SET ^MIO("MIOOS","THEME","ACTIVE",USER)=KEY
	KILL OUT
	SET OUT("ok")=1,OUT("saved")=1,OUT("key")=KEY,OUT("activeKey")=$GET(^MIO("MIOOS","THEME","ACTIVE",USER))
	MERGE OUT("profile")=^MIO("MIOOS","THEME","PROFILE",USER,KEY)
	QUIT 1
