MIOOSFSUP ; MIOOS chunked upload helpers
	QUIT
	;
UPMODE(CONF)
	NEW MODE
	SET MODE=$$LOW^MIOUTIL($GET(CONF("mioos","upload","mode"),"resumable-chunk-session"))
	IF MODE="" SET MODE="resumable-chunk-session"
	IF MODE="resumable" SET MODE="resumable-chunk-session"
	IF MODE="chunked" SET MODE="resumable-chunk-session"
	IF MODE="chunked-session" SET MODE="resumable-chunk-session"
	IF MODE="single" SET MODE="single-request"
	IF MODE="single-request-http" SET MODE="single-request"
	IF MODE="single-request-multipart" SET MODE="single-request"
	IF MODE'="single-request",MODE'="resumable-chunk-session" SET MODE="resumable-chunk-session"
	QUIT MODE
	;
UPCHUNK(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","upload","chunkBytes"),256000)
	IF N<4096 SET N=4096
	IF N>(65536*10) SET N=65536*10
	QUIT N
	;
UPCONCUR(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","upload","concurrency"),4)
	IF N<1 SET N=1
	IF N>8 SET N=8
	QUIT N
	;
UPBATCH(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","websocket","uploadBatchSize"),1)
	IF N<1 SET N=1
	IF N>2 SET N=2
	QUIT N
	;
UPTTL(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","upload","staleSeconds"),1800)
	IF N<60 SET N=60
	QUIT N
	;
NEXTUP()
	NEW N
	SET N=$INCREMENT(^MIO("MIOOS","UPLOAD","SEQ"))
	QUIT "up-"_N
	;
NOW()
	QUIT $HOROLOG
	;
SECSDIFF(FROM,TO)
	NEW FD,FS,TD,TS
	SET FROM=$GET(FROM),TO=$GET(TO)
	IF FROM="" QUIT 0
	IF TO="" SET TO=$$NOW()
	SET FD=+FROM,FS=+$PIECE(FROM,",",2),TD=+TO,TS=+$PIECE(TO,",",2)
	QUIT (((TD-FD)*86400)+(TS-FS))
	;
TOUCH(UPLOADID)
	SET ^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"updatedAt")=$$NOW()
	QUIT
	;
RAWBYTES(UPLOADID)
	NEW IDX,TOTAL
	SET (IDX,TOTAL)=0
	FOR  SET IDX=$ORDER(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"chunkBytes",IDX)) QUIT:IDX'>0  SET TOTAL=TOTAL+$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"chunkBytes",IDX))
	QUIT TOTAL
	;
BEGIN(STATE,CONF,PARENT,NAME,MIME,TOTAL,ENCODING,OUT,ERR)
	NEW PID,UPID,OWNER,ROLES,NOW
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	IF '$$RESOLVE^MIOOSFS($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD^MIOOSFS(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN^MIOOSFS(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	IF $GET(NAME)="" SET ERR("error")="name_missing" QUIT 0
	SET UPID=$$NEXTUP()
	SET OWNER=$GET(STATE("principal"),"guest")
	SET ROLES=$GET(STATE("roles"),"guest")
	SET NOW=$$NOW()
	SET ^MIO("MIOOS","UPLOAD","META",UPID)=PID_"^"_$GET(NAME)_"^"_$GET(MIME,"application/octet-stream")_"^"_OWNER_"^"_ROLES_"^"_$GET(ENCODING,"base64-dataurl")_"^"_(+$GET(TOTAL))_"^"_NOW
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"chunks")=0
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"bytes")=0
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"totalBytes")=+$GET(TOTAL)
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"createdAt")=NOW
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"updatedAt")=NOW
	SET OUT("uploadId")=UPID
	SET OUT("parentId")=PID
	SET OUT("name")=$GET(NAME)
	SET OUT("mime")=$GET(MIME,"application/octet-stream")
	SET OUT("encoding")=$GET(ENCODING,"base64-dataurl")
	SET OUT("chunkBytes")=$$UPCHUNK(.CONF)
	SET OUT("strategy")="chunked"
	SET OUT("concurrencyDefault")=$$UPCONCUR(.CONF)
	SET OUT("batchSize")=$$UPBATCH(.CONF)
	QUIT 1
	;
CHUNK(STATE,CONF,UPLOADID,INDEX,DATA,BYTES,OUT,ERR)
	NEW META,OWNER,RECV,PREV
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	IF +$GET(INDEX)<1 SET ERR("error")="chunk_index_invalid" QUIT 0
	SET PREV=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunkBytes",+INDEX))
	SET ^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,+INDEX)=$GET(DATA)
	SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunkBytes",+INDEX)=+$GET(BYTES,$LENGTH($GET(DATA)))
	SET RECV=$$RAWBYTES(UPLOADID)
	SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes")=RECV
	IF +$GET(INDEX)>+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")) SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")=+INDEX
	DO TOUCH(UPLOADID)
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("index")=+INDEX
	SET OUT("receivedBytes")=RECV
	QUIT 1
	;
BATCH(STATE,CONF,UPLOADID,CHROOT,OUT,ERR)
	NEW META,OWNER,I,COUNT,IDX,DATA,RECV,MAXIDX,BYTES
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	SET (I,COUNT,MAXIDX)=0
	FOR  SET I=$ORDER(@CHROOT@(I)) QUIT:I'>0  DO
	. SET IDX=+$GET(@CHROOT@(I,"index"))
	. SET DATA=$GET(@CHROOT@(I,"data"))
	. SET BYTES=+$GET(@CHROOT@(I,"bytes"),$LENGTH(DATA))
	. IF IDX<1 SET ERR("error")="chunk_index_invalid" QUIT
	. SET ^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,IDX)=DATA
	. SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunkBytes",IDX)=BYTES
	. IF IDX>MAXIDX SET MAXIDX=IDX
	. SET COUNT=COUNT+1
	IF $DATA(ERR("error")) QUIT 0
	SET RECV=$$RAWBYTES(UPLOADID)
	SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes")=RECV
	IF MAXIDX>+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")) SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")=MAXIDX
	DO TOUCH(UPLOADID)
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("batchCount")=COUNT
	SET OUT("highestIndex")=MAXIDX
	SET OUT("receivedBytes")=RECV
	QUIT 1
	;
STATUS(STATE,CONF,UPLOADID,OUT,ERR)
	NEW META,OWNER,TOTAL,CREATED,UPDATED
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	SET TOTAL=+$PIECE(META,"^",7)
	SET CREATED=$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"createdAt"),$PIECE(META,"^",8))
	SET UPDATED=$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"updatedAt"),CREATED)
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("parentId")=$PIECE(META,"^",1)
	SET OUT("name")=$PIECE(META,"^",2)
	SET OUT("mime")=$PIECE(META,"^",3)
	SET OUT("encoding")=$PIECE(META,"^",6)
	SET OUT("totalBytes")=TOTAL
	SET OUT("receivedBytes")=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes"))
	SET OUT("chunkCount")=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks"))
	SET OUT("createdAt")=CREATED
	SET OUT("updatedAt")=UPDATED
	SET OUT("ageSeconds")=$$SECSDIFF(UPDATED,$$NOW())
	SET OUT("nextIndex")=+$GET(OUT("chunkCount"))+1
	QUIT 1
	;
COMMIT(STATE,CONF,UPLOADID,OUT,ERR)
	NEW META,PID,NAME,MIME,OWNER,ROLES,ENC,OUTID,NOW,IDX,BUF,SIZE,CHSZ,PREFIX,TEMP,OK
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET PID=$PIECE(META,"^",1),NAME=$PIECE(META,"^",2),MIME=$PIECE(META,"^",3)
	SET OWNER=$PIECE(META,"^",4),ROLES=$PIECE(META,"^",5),ENC=$PIECE(META,"^",6)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	IF '$$CAN^MIOOSFS(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	SET NOW=$$NOW(),CHSZ=$$CHUNK^MIOOSFS(.CONF)
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PID,NAME))
	IF OUTID="" DO
	. SET OUTID=$$NEXTID^MIOOSFS()
	. DO SAVEENTRY^MIOOSFS(OUTID,"file",PID,NAME,$GET(MIME,"application/octet-stream"),0,NOW,NOW,OWNER,ROLES,1,1,1)
	. SET ^MIO("MIOOS","FS","CHILD",PID,NAME)=OUTID
	ELSE  DO
	. KILL ^MIO("MIOOS","FS","DATA",OUTID)
	SET IDX=0,BUF="",SIZE=0
	SET TEMP=0 FOR  SET TEMP=$ORDER(^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,TEMP)) QUIT:TEMP'>0  DO
	. NEW SEG,DEC
	. SET SEG=$GET(^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,TEMP))
	. SET DEC=$$DECODECHUNK(SEG,ENC)
	. DO APPEND(OUTID,DEC,.IDX,.BUF,.SIZE,CHSZ)
	IF BUF'="" DO
	. SET IDX=IDX+1
	. SET ^MIO("MIOOS","FS","DATA",OUTID,IDX)=BUF
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),"^",4)=$GET(MIME,"application/octet-stream")
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),"^",5)=SIZE
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),"^",7)=NOW
	KILL ^MIO("MIOOS","FS","HASH",OUTID)
	DO CLEAN(UPLOADID)
	SET OK=$$META^MIOOSFS(.STATE,OUTID,.OUT,.ERR)
	IF 'OK QUIT 0
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("committed")=1
	QUIT 1
	;
ABORT(STATE,CONF,UPLOADID,OUT,ERR)
	NEW META,OWNER
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	DO CLEAN($GET(UPLOADID))
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("aborted")=1
	QUIT 1
	;
APPEND(ID,SEG,IDX,BUF,SIZE,CHSZ)
	SET SIZE=+$GET(SIZE)+$LENGTH($GET(SEG))
	SET BUF=$GET(BUF)_$GET(SEG)
	FOR  QUIT:$LENGTH(BUF)<+$GET(CHSZ)  DO
	. SET IDX=+$GET(IDX)+1
	. SET ^MIO("MIOOS","FS","DATA",ID,IDX)=$EXTRACT(BUF,1,CHSZ)
	. SET BUF=$EXTRACT(BUF,CHSZ+1,256000)
	QUIT
	;
DECODECHUNK(DATA,ENC)
	NEW TXT,MODE
	SET TXT=$GET(DATA),MODE=$$LOW^MIOUTIL($GET(ENC))
	IF MODE="" QUIT TXT
	IF MODE="text" QUIT TXT
	IF MODE="base64-dataurl" DO
	. IF TXT["base64," SET TXT=$PIECE(TXT,"base64,",2,999)
	. SET TXT=$$B64D^MIOSJWT(TXT)
	. QUIT
	IF MODE="base64" QUIT $$B64D^MIOSJWT(TXT)
	QUIT TXT
	;
PURGE(CONF,OUT)
	NEW NOW,TTL,UPID,META,CREATED,UPDATED,PURGED
	SET NOW=$$NOW(),TTL=$$UPTTL(.CONF),PURGED=0
	SET UPID=""
	FOR  SET UPID=$ORDER(^MIO("MIOOS","UPLOAD","META",UPID)) QUIT:UPID=""  DO
	. SET META=$GET(^MIO("MIOOS","UPLOAD","META",UPID))
	. SET CREATED=$PIECE(META,"^",8)
	. SET UPDATED=$GET(^MIO("MIOOS","UPLOAD","INFO",UPID,"updatedAt"),CREATED)
	. IF $$SECSDIFF(UPDATED,NOW)>TTL DO
	. . DO CLEAN(UPID)
	. . SET PURGED=PURGED+1
	IF $DATA(OUT) SET OUT("purged")=PURGED,OUT("ttlSeconds")=TTL
	QUIT PURGED
	;
CLEAN(UPLOADID)
	KILL ^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID))
	KILL ^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID))
	KILL ^MIO("MIOOS","UPLOAD","CHUNK",$GET(UPLOADID))
	QUIT
	;