MIOOSFSDN ; MIOOS chunked downloads
	QUIT
	;
SESSIONKEY(STATE)
	QUIT $GET(STATE("sessionId"),"mioos-shell")_":"_$GET(STATE("principal"),"guest")
	;
NEXTID()
	NEW N
	SET N=$INCREMENT(^MIO("MIOOS","DL","SEQ"))
	QUIT "dl-"_N
	;
NOW()
	QUIT $HOROLOG
	;
SECSDIFF(FROM,TO)
	NEW FD,FS,TD,TS
	SET FROM=$GET(FROM),TO=$GET(TO)
	IF FROM="" QUIT 0
	IF TO="" SET TO=$$NOW()
	SET FD=+FROM,FS=+$PIECE(FROM,",",2),TD=+TO,TS=+$PIECE(TO,",",2)
	QUIT (((TD-FD)*86400)+(TS-FS))
	;
DLTTL(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","download","staleSeconds"),900)
	IF N<60 SET N=60
	QUIT N
	;
TOUCH(STATE,DLID)
	NEW SKEY
	SET SKEY=$$SESSIONKEY(.STATE)
	SET ^MIO("MIOOS","DL",SKEY,$GET(DLID),"updatedAt")=$$NOW()
	QUIT
	;
DLCHUNK(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","fs","downloadChunkSize"))
	IF N<256 SET N=+$GET(CONF("mioos","upload","chunkBytes"),65536)
	IF N<256 SET N=65536
	IF N>65536 SET N=65536
	QUIT N
	;
BEGIN(STATE,CONF,ID,OUT,ERR)
	NEW RID,SKEY,DLID,SIZE,CHUNK,CACHEDHASH,NOW
	KILL OUT
	SET ERR("routine")="MIOOSFSDN"
	IF '$$RESOLVE^MIOOSFS($GET(ID),.RID,.ERR) QUIT 0
	IF '$$CAN^MIOOSFS(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD^MIOOSFS(RID,1)'="file" SET ERR("error")="not_file" QUIT 0
	SET SIZE=+$$FIELD^MIOOSFS(RID,5)
	SET CHUNK=$$DLCHUNK(.CONF)
	SET SKEY=$$SESSIONKEY(.STATE),DLID=$$NEXTID(),NOW=$$NOW()
	KILL ^MIO("MIOOS","DL",SKEY,DLID)
	SET ^MIO("MIOOS","DL",SKEY,DLID,"fileId")=RID
	SET ^MIO("MIOOS","DL",SKEY,DLID,"size")=SIZE
	SET ^MIO("MIOOS","DL",SKEY,DLID,"chunkSize")=CHUNK
	SET ^MIO("MIOOS","DL",SKEY,DLID,"createdAt")=NOW
	SET ^MIO("MIOOS","DL",SKEY,DLID,"updatedAt")=NOW
	SET OUT("downloadId")=DLID
	SET OUT("id")=RID
	SET OUT("name")=$$FIELD^MIOOSFS(RID,3)
	SET OUT("mime")=$$FIELD^MIOOSFS(RID,4)
	SET OUT("size")=SIZE
	SET OUT("transferBytes")=SIZE
	SET OUT("path")=$$PATH^MIOOSFS(RID)
	SET OUT("chunkSize")=CHUNK
	SET OUT("verifyHash")=0
	SET CACHEDHASH=$GET(^MIO("MIOOS","FS","HASH",RID))
	IF CACHEDHASH'="" SET OUT("verifyHash")=1,OUT("sha256")=CACHEDHASH
	QUIT 1
	;
CHUNK(STATE,DLID,OFFSET,SIZE,OUT,ERR)
	NEW SKEY,RID,REQSIZE,NEXTOFF,SLICE,READ,TOTAL,FERR
	KILL OUT
	SET ERR("routine")="MIOOSFSDN"
	SET SKEY=$$SESSIONKEY(.STATE)
	IF $GET(DLID)="" SET ERR("error")="download_missing" QUIT 0
	SET RID=$GET(^MIO("MIOOS","DL",SKEY,DLID,"fileId"))
	IF RID="" SET ERR("error")="download_not_found" QUIT 0
	IF '$$CAN^MIOOSFS(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD^MIOOSFS(RID,1)'="file" SET ERR("error")="not_file" QUIT 0
	SET TOTAL=+$$FIELD^MIOOSFS(RID,5)
	SET OFFSET=+$GET(OFFSET) IF OFFSET<0 SET OFFSET=0
	SET REQSIZE=+$GET(SIZE) IF REQSIZE<1 SET REQSIZE=+$GET(^MIO("MIOOS","DL",SKEY,DLID,"chunkSize"),65536)
	IF OFFSET>TOTAL SET OFFSET=TOTAL
	KILL FERR
	IF '$$READRANGE^MIOOSFS(RID,OFFSET,REQSIZE,.SLICE,.READ,.FERR) DO  QUIT 0
	. SET ERR("error")=$GET(FERR("error"),"download_read_failed")
	SET NEXTOFF=OFFSET+READ
	DO TOUCH(.STATE,DLID)
	SET OUT("downloadId")=DLID
	SET OUT("id")=RID
	SET OUT("name")=$$FIELD^MIOOSFS(RID,3)
	SET OUT("mime")=$$FIELD^MIOOSFS(RID,4)
	SET OUT("offset")=OFFSET
	SET OUT("size")=READ
	SET OUT("nextOffset")=NEXTOFF
	SET OUT("totalBytes")=TOTAL
	SET OUT("eof")=$SELECT(NEXTOFF'<TOTAL:1,1:0)
	SET OUT("data")=$GET(SLICE)
	QUIT 1
	;
ABORT(STATE,DLID,OUT,ERR)
	NEW SKEY
	KILL OUT
	SET ERR("routine")="MIOOSFSDN"
	SET SKEY=$$SESSIONKEY(.STATE)
	IF $GET(DLID)="" SET ERR("error")="download_missing" QUIT 0
	KILL ^MIO("MIOOS","DL",SKEY,DLID)
	SET OUT("downloadId")=DLID
	SET OUT("aborted")=1
	QUIT 1
	;
PURGE(CONF,OUT)
	NEW SKEY,DLID,NOW,TTL,UPDATED,CREATED,PURGED
	SET NOW=$$NOW(),TTL=$$DLTTL(.CONF),PURGED=0
	SET SKEY=""
	FOR  SET SKEY=$ORDER(^MIO("MIOOS","DL",SKEY)) QUIT:SKEY=""  DO
	. SET DLID=""
	. FOR  SET DLID=$ORDER(^MIO("MIOOS","DL",SKEY,DLID)) QUIT:DLID=""  DO
	. . SET CREATED=$GET(^MIO("MIOOS","DL",SKEY,DLID,"createdAt"))
	. . SET UPDATED=$GET(^MIO("MIOOS","DL",SKEY,DLID,"updatedAt"),CREATED)
	. . IF $$SECSDIFF(UPDATED,NOW)>TTL DO
	. . . KILL ^MIO("MIOOS","DL",SKEY,DLID)
	. . . SET PURGED=PURGED+1
	IF $DATA(OUT) SET OUT("purged")=PURGED,OUT("ttlSeconds")=TTL
	QUIT PURGED
