MIOOSTRXUP ; MIOOS transfer upload foundation
	QUIT
	;
BEGIN(STATE,CONF,TREE,OUT,ERR)
	NEW META,ID,PARENT,NAME,MIME,SIZE
	KILL OUT
	SET ERR("routine")="MIOOSTRXUP"
	SET PARENT=$SELECT($GET(TREE("parent"))'="":$GET(TREE("parent")),1:"root")
	SET NAME=$GET(TREE("name")) IF NAME="" SET ERR("error")="name_missing" QUIT 0
	SET MIME=$SELECT($GET(TREE("mime"))'="":$GET(TREE("mime")),1:"application/octet-stream")
	SET SIZE=+$GET(TREE("sizeBytes")) IF SIZE<0 SET SIZE=0
	SET META("parent")=PARENT,META("name")=NAME,META("mime")=MIME,META("sizeBytes")=SIZE
	SET META("kind")="upload",META("protocol")=1
	SET ID=$$INIT^MIOOSTRX(.STATE,.CONF,"upload",.META,.OUT,.ERR)
	IF ID="" QUIT 0
	SET ^MIO("MIOOS","TRANSFER",ID,"bytesTotal")=SIZE
	SET ^MIO("MIOOS","TRANSFER",ID,"chunkTotal")=+$GET(TREE("chunkTotal"))
	DO SNAP^MIOOSTRX(ID,.OUT)
	QUIT 1
	;
CHUNK(STATE,CONF,TREE,OUT,ERR)
	NEW ID,IDX,DATA,LEN,WORKER,ISNEW
	KILL OUT
	SET ERR("routine")="MIOOSTRXUP"
	SET ID=$GET(TREE("transferId"))
	IF '$$OWNOK^MIOOSTRX(.STATE,ID,.ERR) QUIT 0
	IF $GET(^MIO("MIOOS","TRANSFER",ID,"direction"))'="upload" SET ERR("error")="direction_mismatch" QUIT 0
	IF $GET(^MIO("MIOOS","TRANSFER",ID,"state"))'="active" SET ERR("error")="transfer_not_active" QUIT 0
	SET IDX=+$GET(TREE("chunkIndex")) IF IDX<1 SET ERR("error")="chunk_index_invalid" QUIT 0
	SET WORKER=$GET(TREE("workerId")) IF WORKER="" SET WORKER="w0"
	SET DATA=$GET(TREE("data")),LEN=$LENGTH(DATA)
	SET ISNEW=$SELECT($DATA(^MIO("MIOOS","TRANSFER",ID,"recv",IDX))#2:0,1:1)
	SET ^MIO("MIOOS","TRANSFER",ID,"chunk",IDX)=DATA
	IF ISNEW DO
	. SET ^MIO("MIOOS","TRANSFER",ID,"recv",IDX)=LEN
	. SET ^MIO("MIOOS","TRANSFER",ID,"chunkReceived")=$GET(^MIO("MIOOS","TRANSFER",ID,"chunkReceived"))+1
	. SET ^MIO("MIOOS","TRANSFER",ID,"bytesDone")=$GET(^MIO("MIOOS","TRANSFER",ID,"bytesDone"))+LEN
	SET ^MIO("MIOOS","TRANSFER",ID,"worker",WORKER,"updatedAt")=$HOROLOG
	SET ^MIO("MIOOS","TRANSFER",ID,"worker",WORKER,"lastChunk")=IDX
	IF ISNEW DO
	. SET ^MIO("MIOOS","TRANSFER",ID,"worker",WORKER,"chunkCount")=$GET(^MIO("MIOOS","TRANSFER",ID,"worker",WORKER,"chunkCount"))+1
	. SET ^MIO("MIOOS","TRANSFER",ID,"worker",WORKER,"bytesDone")=$GET(^MIO("MIOOS","TRANSFER",ID,"worker",WORKER,"bytesDone"))+LEN
	DO TOUCH^MIOOSTRX(ID)
	DO SNAP^MIOOSTRX(ID,.OUT)
	SET OUT("chunkIndex")=IDX,OUT("ack")=1,OUT("workerId")=WORKER
	QUIT 1
	;
COMMIT(STATE,CONF,TREE,OUT,ERR)
	NEW ID,PARENT,NAME,MIME,TOTAL,IDX,DATA,FILEID,FOUT,PID,RERR
	KILL OUT
	SET ERR("routine")="MIOOSTRXUP"
	SET ID=$GET(TREE("transferId"))
	IF '$$OWNOK^MIOOSTRX(.STATE,ID,.ERR) QUIT 0
	IF $GET(^MIO("MIOOS","TRANSFER",ID,"direction"))'="upload" SET ERR("error")="direction_mismatch" QUIT 0
	SET TOTAL=+$GET(^MIO("MIOOS","TRANSFER",ID,"chunkTotal"))
	IF TOTAL>0,+$GET(^MIO("MIOOS","TRANSFER",ID,"chunkReceived"))<TOTAL SET ERR("error")="chunks_missing" QUIT 0
	SET PARENT=$GET(^MIO("MIOOS","TRANSFER",ID,"meta","parent"))
	SET NAME=$GET(^MIO("MIOOS","TRANSFER",ID,"meta","name"))
	SET MIME=$GET(^MIO("MIOOS","TRANSFER",ID,"meta","mime"))
	SET DATA="",IDX=0
	FOR  SET IDX=$ORDER(^MIO("MIOOS","TRANSFER",ID,"chunk",IDX)) QUIT:IDX'>0  SET DATA=DATA_$GET(^MIO("MIOOS","TRANSFER",ID,"chunk",IDX))
	IF '$$WRITE^MIOOSFS(.STATE,PARENT,NAME,DATA,MIME,.FOUT,.RERR) DO  QUIT 0
	. MERGE ERR=RERR
	SET FILEID=$GET(FOUT("id"))
	DO DONE^MIOOSTRX(ID,FILEID)
	DO SNAP^MIOOSTRX(ID,.OUT)
	MERGE OUT("file")=FOUT
	QUIT 1
	;
ABORT(STATE,CONF,TREE,OUT,ERR)
	QUIT $$ABORT^MIOOSTRX(.STATE,$GET(TREE("transferId")),.OUT,.ERR)
	;
STATUS(STATE,CONF,TREE,OUT,ERR)
	NEW ID
	KILL OUT
	SET ERR("routine")="MIOOSTRXUP"
	SET ID=$GET(TREE("transferId"))
	IF '$$OWNOK^MIOOSTRX(.STATE,ID,.ERR) QUIT 0
	DO SNAP^MIOOSTRX(ID,.OUT)
	QUIT 1
	;
