MIOOSFSUP ; MIOOS chunked upload helpers
	QUIT
	;
UPCHUNK(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","upload","chunkBytes"),1048576)
	IF N<4096 SET N=4096
	IF N>1048576 SET N=1048576
	QUIT N
	;
UPCONCUR(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","upload","concurrency"),3)
	IF N<1 SET N=1
	IF N>9 SET N=9
	QUIT N
	;
	;
UPTTL(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","upload","staleSeconds"),1800)
	IF N<60 SET N=60
	QUIT N
	;
NEXTUP()
	NEW N
	SET N=$INCREMENT(^MIO("MIOOS","UPLOAD","SEQ"))
	QUIT "up-"_N
	;
NOW()
	QUIT $HOROLOG
	;
SECSDIFF(FROM,TO)
	NEW FD,FS,TD,TS
	SET FROM=$GET(FROM),TO=$GET(TO)
	IF FROM="" QUIT 0
	IF TO="" SET TO=$$NOW()
	SET FD=+FROM,FS=+$PIECE(FROM,",",2),TD=+TO,TS=+$PIECE(TO,",",2)
	QUIT (((TD-FD)*86400)+(TS-FS))
	;
TOUCH(UPLOADID)
	SET ^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"updatedAt")=$$NOW()
	QUIT
	;
RAWBYTES(UPLOADID)
	QUIT +$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"bytes"))
	;
BEGIN(STATE,CONF,PARENT,NAME,MIME,TOTAL,ENCODING,OUT,ERR)
	NEW PID,UPID,OWNER,ROLES,NOW,UPCH,EXIST,TEMPID,FAST
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	IF '$$RESOLVE^MIOOSFS($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD^MIOOSFS(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN^MIOOSFS(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	IF $GET(NAME)="" SET ERR("error")="name_missing" QUIT 0
	SET UPID=$$NEXTUP()
	SET OWNER=$GET(STATE("principal"),"guest")
	SET ROLES=$GET(STATE("roles"),"guest")
	SET NOW=$$NOW(),UPCH=$$UPCHUNK(.CONF)
	SET EXIST=$GET(^MIO("MIOOS","FS","CHILD",PID,$GET(NAME)))
	SET FAST=$SELECT($GET(ENCODING)="binary"&(EXIST=""):1,1:0)
	SET TEMPID=$SELECT(FAST:$$NEXTID^MIOOSFS(),1:"")
	SET ^MIO("MIOOS","UPLOAD","META",UPID)=PID_"^"_$GET(NAME)_"^"_$GET(MIME,"application/octet-stream")_"^"_OWNER_"^"_ROLES_"^"_$GET(ENCODING,"base64-dataurl")_"^"_(+$GET(TOTAL))_"^"_NOW
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"chunks")=0
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"bytes")=0
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"totalBytes")=+$GET(TOTAL)
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"createdAt")=NOW
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"updatedAt")=NOW
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"chunkBytesTarget")=UPCH
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"expectedChunks")=$SELECT(+$GET(TOTAL)>0:((+$GET(TOTAL)+UPCH-1)\UPCH),1:0)
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"fastPromote")=FAST
	SET ^MIO("MIOOS","UPLOAD","INFO",UPID,"tempId")=TEMPID
	IF FAST DO SETCHUNK^MIOOSFS(TEMPID,UPCH)
	SET OUT("uploadId")=UPID
	SET OUT("parentId")=PID
	SET OUT("name")=$GET(NAME)
	SET OUT("mime")=$GET(MIME,"application/octet-stream")
	SET OUT("encoding")=$GET(ENCODING,"base64-dataurl")
	SET OUT("chunkBytes")=UPCH
	SET OUT("strategy")="chunked"
	SET OUT("commitStrategy")=$SELECT(FAST:"direct-stage-promote",1:"copy-on-commit")
	SET OUT("concurrencyDefault")=$$UPCONCUR(.CONF)
	QUIT 1
	;
CHUNK(STATE,CONF,UPLOADID,INDEX,DATA,BYTES,OUT,ERR)
	NEW META,OWNER,RECV,PREV,NEWBYTES,FAST,TEMPID
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	IF +$GET(INDEX)<1 SET ERR("error")="chunk_index_invalid" QUIT 0
	SET PREV=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunkBytes",+INDEX))
	SET NEWBYTES=$ZLENGTH($GET(DATA))
	IF +$GET(BYTES)>0,+$GET(BYTES)'=NEWBYTES SET ERR("error")="chunk_size_mismatch",ERR("detail")=+INDEX QUIT 0
	IF NEWBYTES<1 SET ERR("error")="chunk_empty",ERR("detail")=+INDEX QUIT 0
	SET FAST=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"fastPromote"))
	SET TEMPID=$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"tempId"))
	IF FAST,TEMPID'="" SET ^MIO("MIOOS","FS","DATA",TEMPID,+INDEX)=$GET(DATA)
	ELSE  SET ^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,+INDEX)=$GET(DATA)
	SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunkBytes",+INDEX)=NEWBYTES
	SET RECV=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes"))+NEWBYTES-PREV
	IF RECV<0 SET RECV=0
	SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes")=RECV
	IF +$GET(INDEX)>+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")) SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")=+INDEX
	DO TOUCH(UPLOADID)
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("index")=+INDEX
	SET OUT("receivedBytes")=RECV
	QUIT 1
	;
BATCH(STATE,CONF,UPLOADID,CHROOT,OUT,ERR)
	NEW META,OWNER,I,COUNT,IDX,DATA,RECV,MAXIDX,BYTES,PREV,DELTA,FAST,TEMPID
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	SET FAST=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"fastPromote"))
	SET TEMPID=$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"tempId"))
	SET (I,COUNT,MAXIDX,DELTA)=0
	FOR  SET I=$ORDER(@CHROOT@(I)) QUIT:I'>0  DO
	. SET IDX=+$GET(@CHROOT@(I,"index"))
	. SET DATA=$GET(@CHROOT@(I,"data"))
	. SET BYTES=$ZLENGTH(DATA)
	. IF +$GET(@CHROOT@(I,"bytes"))>0,+$GET(@CHROOT@(I,"bytes"))'=BYTES SET ERR("error")="chunk_size_mismatch",ERR("detail")=IDX QUIT
	. IF BYTES<1 SET ERR("error")="chunk_empty",ERR("detail")=IDX QUIT
	. IF IDX<1 SET ERR("error")="chunk_index_invalid" QUIT
	. SET PREV=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunkBytes",IDX))
	. IF FAST,TEMPID'="" SET ^MIO("MIOOS","FS","DATA",TEMPID,IDX)=DATA
	. ELSE  SET ^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,IDX)=DATA
	. SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunkBytes",IDX)=BYTES
	. SET DELTA=DELTA+BYTES-PREV
	. IF IDX>MAXIDX SET MAXIDX=IDX
	. SET COUNT=COUNT+1
	IF $DATA(ERR("error")) QUIT 0
	SET RECV=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes"))+DELTA
	IF RECV<0 SET RECV=0
	SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes")=RECV
	IF MAXIDX>+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")) SET ^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks")=MAXIDX
	DO TOUCH(UPLOADID)
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("batchCount")=COUNT
	SET OUT("highestIndex")=MAXIDX
	SET OUT("receivedBytes")=RECV
	QUIT 1
	;
MAXIDX(UPLOADID)
	QUIT +$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"chunks"))
	;
NEXTMISS(UPLOADID)
	NEW EXPECT,MAX,TOTAL,RECV,LIMIT,IDX,MISS
	SET EXPECT=+$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"expectedChunks"))
	SET MAX=$$MAXIDX(UPLOADID)
	SET TOTAL=+$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"totalBytes"))
	SET RECV=+$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"bytes"))
	SET LIMIT=$SELECT(EXPECT>MAX:EXPECT,1:MAX)
	IF TOTAL>0,RECV<TOTAL SET LIMIT=LIMIT+1
	IF LIMIT<1 QUIT 1
	SET MISS=0
	FOR IDX=1:1:LIMIT DO  QUIT:MISS>0
	. IF +$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"chunkBytes",IDX))<1 SET MISS=IDX
	QUIT $SELECT(MISS>0:MISS,1:LIMIT+1)
	;
CONTIGBYTES(UPLOADID)
	NEW EXPECT,IDX,TOTAL
	SET EXPECT=+$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"expectedChunks")),TOTAL=0
	IF EXPECT<1 QUIT +$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"bytes"))
	FOR IDX=1:1:EXPECT DO  QUIT:+$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"chunkBytes",IDX))<1
	. SET TOTAL=TOTAL+$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"chunkBytes",IDX))
	QUIT TOTAL
	;
STATUS(STATE,CONF,UPLOADID,OUT,ERR)
	NEW META,OWNER,TOTAL,CREATED,UPDATED
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	SET TOTAL=+$PIECE(META,"^",7)
	SET CREATED=$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"createdAt"),$PIECE(META,"^",8))
	SET UPDATED=$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"updatedAt"),CREATED)
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("parentId")=$PIECE(META,"^",1)
	SET OUT("name")=$PIECE(META,"^",2)
	SET OUT("mime")=$PIECE(META,"^",3)
	SET OUT("encoding")=$PIECE(META,"^",6)
	SET OUT("totalBytes")=TOTAL
	SET OUT("receivedBytes")=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes"))
	SET OUT("chunkCount")=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunks"))
	SET OUT("expectedChunks")=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"expectedChunks"))
	SET OUT("chunkBytes")=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunkBytesTarget"))
	SET OUT("concurrencyDefault")=$$UPCONCUR(.CONF)
	SET OUT("nextIndex")=$$NEXTMISS(UPLOADID)
	SET OUT("contiguousBytes")=$$CONTIGBYTES(UPLOADID)
	SET OUT("createdAt")=CREATED
	SET OUT("updatedAt")=UPDATED
	SET OUT("ageSeconds")=$$SECSDIFF(UPDATED,$$NOW())
	SET OUT("commitStrategy")=$SELECT(+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"fastPromote"))=1:"direct-stage-promote",1:"copy-on-commit")
	QUIT 1
	;
COMMIT(STATE,CONF,UPLOADID,OUT,ERR)
	NEW META,PID,NAME,MIME,OWNER,ROLES,ENC,OUTID,NOW,IDX,BUF,SIZE,CHSZ,PREFIX,TEMP,OK,FAST,TEMPID
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET PID=$PIECE(META,"^",1),NAME=$PIECE(META,"^",2),MIME=$PIECE(META,"^",3)
	SET OWNER=$PIECE(META,"^",4),ROLES=$PIECE(META,"^",5),ENC=$PIECE(META,"^",6)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	IF '$$CAN^MIOOSFS(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	NEW EXPECT,NXMISS,TOTALBYTES,RECVBYTES,MAX
	SET NOW=$$NOW(),CHSZ=$$CHUNK^MIOOSFS(.CONF)
	SET FAST=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"fastPromote"))
	SET TEMPID=$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"tempId"))
	SET EXPECT=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"expectedChunks"))
	SET TOTALBYTES=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"totalBytes"))
	SET RECVBYTES=+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"bytes"))
	SET MAX=$$MAXIDX(UPLOADID)
	SET NXMISS=$$NEXTMISS(UPLOADID)
	IF TOTALBYTES>0,RECVBYTES<TOTALBYTES SET ERR("error")="missing_chunk",ERR("detail")=NXMISS QUIT 0
	IF MAX>0,NXMISS'>MAX SET ERR("error")="missing_chunk",ERR("detail")=NXMISS QUIT 0
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PID,NAME))
	IF FAST,TEMPID'="" DO
	. IF OUTID'="" SET ERR("error")="name_conflict",ERR("detail")=OUTID QUIT
	. SET SIZE=$SELECT(TOTALBYTES>0:TOTALBYTES,1:RECVBYTES)
	. DO SAVEENTRY^MIOOSFS(TEMPID,"file",PID,NAME,$GET(MIME,"application/octet-stream"),SIZE,NOW,NOW,OWNER,ROLES,1,1,1)
	. SET ^MIO("MIOOS","FS","CHILD",PID,NAME)=TEMPID
	. DO SETCHUNK^MIOOSFS(TEMPID,+$GET(^MIO("MIOOS","UPLOAD","INFO",UPLOADID,"chunkBytesTarget"),$$UPCHUNK(.CONF)))
	. KILL ^MIO("MIOOS","FS","HASH",TEMPID)
	. DO DROPSTAGE(UPLOADID)
	. SET OK=$$META^MIOOSFS(.STATE,TEMPID,.OUT,.ERR)
	. IF 'OK QUIT
	. SET OUT("uploadId")=$GET(UPLOADID)
	. SET OUT("committed")=1
	. SET OUT("promoted")=1
	IF FAST,TEMPID'="" QUIT $SELECT($DATA(ERR("error")):0,1:1)
	IF OUTID="" DO
	. SET OUTID=$$NEXTID^MIOOSFS()
	. DO SAVEENTRY^MIOOSFS(OUTID,"file",PID,NAME,$GET(MIME,"application/octet-stream"),0,NOW,NOW,OWNER,ROLES,1,1,1)
	. SET ^MIO("MIOOS","FS","CHILD",PID,NAME)=OUTID
	ELSE  DO
	. KILL ^MIO("MIOOS","FS","DATA",OUTID)
	SET IDX=0,BUF="",SIZE=0
	IF ENC="base64-dataurl" DO
	. SET PREFIX="data:"_$GET(MIME,"application/octet-stream")_";base64,"
	. DO APPEND(OUTID,PREFIX,.IDX,.BUF,.SIZE,CHSZ)
	SET TEMP=0 FOR  SET TEMP=$ORDER(^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,TEMP)) QUIT:TEMP'>0  DO
	. DO APPEND(OUTID,$GET(^MIO("MIOOS","UPLOAD","CHUNK",UPLOADID,TEMP)),.IDX,.BUF,.SIZE,CHSZ)
	IF BUF'="" DO
	. SET IDX=IDX+1
	. SET ^MIO("MIOOS","FS","DATA",OUTID,IDX)=BUF
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),"^",4)=$GET(MIME,"application/octet-stream")
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),"^",5)=SIZE
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),"^",7)=NOW
	DO SETCHUNK^MIOOSFS(OUTID,CHSZ)
	KILL ^MIO("MIOOS","FS","HASH",OUTID)
	DO CLEAN(UPLOADID)
	SET OK=$$META^MIOOSFS(.STATE,OUTID,.OUT,.ERR)
	IF 'OK QUIT 0
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("committed")=1
	QUIT 1
	;
ABORT(STATE,CONF,UPLOADID,OUT,ERR)
	NEW META,OWNER
	KILL OUT
	SET ERR("routine")="MIOOSFSUP"
	SET META=$GET(^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID)))
	IF META="" SET ERR("error")="upload_not_found" QUIT 0
	SET OWNER=$PIECE(META,"^",4)
	IF OWNER'=$GET(STATE("principal"),"guest") SET ERR("error")="access_denied" QUIT 0
	DO CLEAN($GET(UPLOADID))
	SET OUT("uploadId")=$GET(UPLOADID)
	SET OUT("aborted")=1
	QUIT 1
	;
DROPSTAGE(UPLOADID)
	KILL ^MIO("MIOOS","UPLOAD","META",$GET(UPLOADID))
	KILL ^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID))
	KILL ^MIO("MIOOS","UPLOAD","CHUNK",$GET(UPLOADID))
	QUIT
	;
APPEND(ID,SEG,IDX,BUF,SIZE,CHSZ)
	SET SIZE=+$GET(SIZE)+$ZLENGTH($GET(SEG))
	SET BUF=$GET(BUF)_$GET(SEG)
	FOR  QUIT:$ZLENGTH(BUF)<+$GET(CHSZ)  DO
	. SET IDX=+$GET(IDX)+1
	. SET ^MIO("MIOOS","FS","DATA",ID,IDX)=$ZEXTRACT(BUF,1,CHSZ)
	. SET BUF=$ZEXTRACT(BUF,CHSZ+1,$ZLENGTH(BUF))
	QUIT
	;
PURGE(CONF,OUT)
	NEW NOW,TTL,UPID,META,CREATED,UPDATED,PURGED
	SET NOW=$$NOW(),TTL=$$UPTTL(.CONF),PURGED=0
	SET UPID=""
	FOR  SET UPID=$ORDER(^MIO("MIOOS","UPLOAD","META",UPID)) QUIT:UPID=""  DO
	. SET META=$GET(^MIO("MIOOS","UPLOAD","META",UPID))
	. SET CREATED=$PIECE(META,"^",8)
	. SET UPDATED=$GET(^MIO("MIOOS","UPLOAD","INFO",UPID,"updatedAt"),CREATED)
	. IF $$SECSDIFF(UPDATED,NOW)>TTL DO
	. . DO CLEAN(UPID)
	. . SET PURGED=PURGED+1
	IF $DATA(OUT) SET OUT("purged")=PURGED,OUT("ttlSeconds")=TTL
	QUIT PURGED
	;
CLEAN(UPLOADID)
	NEW TEMPID
	SET TEMPID=$GET(^MIO("MIOOS","UPLOAD","INFO",$GET(UPLOADID),"tempId"))
	DO DROPSTAGE($GET(UPLOADID))
	IF TEMPID'="" DO
	. KILL ^MIO("MIOOS","FS","DATA",TEMPID)
	. KILL ^MIO("MIOOS","FS","HASH",TEMPID)
	. KILL ^MIO("MIOOS","FS","INFO",TEMPID)
	. KILL ^MIO("MIOOS","FS","ENTRY",TEMPID)
	QUIT
	;