MIOOSFS ; MIOOS global-backed virtual file system
	QUIT
	;
CHUNK(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","fs","chunkSize"),2048)
	IF N<256 SET N=256
	QUIT N
	;
INIT(CONF)
	NEW OWNER,ROLES,ROOT,DOCS,DESK,README,NOW
	SET OWNER=$GET(CONF("mioos","bootstrapAuth","admin","username"),"admin")
	SET ROLES="admin,operator,guest"
	IF '$DATA(^MIO("MIOOS","FS","SEQ")) SET ^MIO("MIOOS","FS","SEQ")=0
	SET NOW=$HOROLOG
	DO SAVEENTRY("root","folder","","/","inode/directory",0,NOW,NOW,OWNER,ROLES,1,1,1)
	DO ENSUREFOLDER("root","Desktop",OWNER,ROLES,.DESK)
	DO ENSUREFOLDER("root","Documents",OWNER,ROLES,.DOCS)
	DO ENSUREFILE("root","README.txt","Welcome to MIOOS VFS","text/plain",OWNER,ROLES,.README)
	QUIT
	;
ENSUREFOLDER(PARENT,NAME,OWNER,ROLES,OUTID)
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",$GET(PARENT),$GET(NAME)))
	IF OUTID'="",$$EXISTS(OUTID),$$FIELD(OUTID,1)="folder" QUIT
	IF OUTID'="" KILL ^MIO("MIOOS","FS","CHILD",PARENT,NAME)
	DO MKDIRID($GET(PARENT),$GET(NAME),$GET(OWNER),$GET(ROLES),.OUTID)
	QUIT
	;
ENSUREFILE(PARENT,NAME,DATA,MIME,OWNER,ROLES,OUTID)
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",$GET(PARENT),$GET(NAME)))
	IF OUTID'="",('$$EXISTS(OUTID)!($$FIELD(OUTID,1)'="file")) DO
	. KILL ^MIO("MIOOS","FS","CHILD",PARENT,NAME)
	. SET OUTID=""
	DO WRITEFILE($GET(PARENT),$GET(NAME),$GET(DATA),$GET(MIME),$GET(OWNER),$GET(ROLES),.OUTID)
	QUIT
	;
NEXTID()
	NEW N
	SET N=$INCREMENT(^MIO("MIOOS","FS","SEQ"))
	QUIT "fs-"_N
	;
SAVEENTRY(ID,KIND,PARENT,NAME,MIME,SIZE,CDT,MDT,OWNER,ROLES,CANR,CANW,CAND)
	NEW U SET U="^"
	SET ^MIO("MIOOS","FS","ENTRY",ID)=KIND_U_PARENT_U_NAME_U_MIME_U_SIZE_U_CDT_U_MDT_U_OWNER_U_ROLES_U_CANR_U_CANW_U_CAND
	QUIT
	;
EXISTS(ID)
	QUIT $DATA(^MIO("MIOOS","FS","ENTRY",$GET(ID)))#2
	;
FIELD(ID,PIECE)
	NEW U SET U="^"
	QUIT $PIECE($GET(^MIO("MIOOS","FS","ENTRY",$GET(ID))),U,+$GET(PIECE))
	;
ROOTID()
	QUIT "root"
	;
HOMEID()
	NEW ID
	SET ID=$GET(^MIO("MIOOS","FS","CHILD","root","Documents"))
	IF ID="" SET ID="root"
	QUIT ID
	;
VALIDNAME(NAME)
	SET NAME=$GET(NAME)
	IF NAME="" QUIT 0
	IF NAME["/" QUIT 0
	IF NAME="." QUIT 0
	IF NAME=".." QUIT 0
	QUIT 1
	;
RESOLVE(PATH,OUTID,ERR)
	NEW I,NODE,NAME
	SET ERR("routine")="MIOOSFS",OUTID=""
	SET PATH=$GET(PATH)
	IF PATH="" SET ERR("error")="path_missing" QUIT 0
	IF $$EXISTS(PATH) SET OUTID=PATH QUIT 1
	IF PATH="root" SET OUTID="root" QUIT 1
	IF $EXTRACT(PATH,1)'="/" SET PATH="/"_PATH
	SET NODE="root"
	IF PATH="/" SET OUTID=NODE QUIT 1
	FOR I=2:1:$LENGTH(PATH,"/") DO  QUIT:NODE=""
	. SET NAME=$PIECE(PATH,"/",I)
	. QUIT:NAME=""
	. SET NODE=$GET(^MIO("MIOOS","FS","CHILD",NODE,NAME))
	. IF NODE'="",'$$EXISTS(NODE) SET NODE=""
	IF NODE="" SET ERR("error")="path_not_found",ERR("detail")=PATH QUIT 0
	SET OUTID=NODE
	QUIT 1
	;
PATH(ID)
	NEW CUR,NAME,OUT,PARENT
	SET ID=$GET(ID)
	IF ID="" QUIT ""
	IF ID="root" QUIT "/"
	SET CUR=ID,OUT=""
	FOR  DO  QUIT:CUR=""!(CUR="root")
	. SET NAME=$$FIELD(CUR,3),PARENT=$$FIELD(CUR,2)
	. SET OUT="/"_NAME_OUT
	. SET CUR=PARENT
	IF OUT="" SET OUT="/"
	QUIT OUT
	;
ROLEOK(ROLECSV,STATE)
	NEW I,R,CSV
	SET CSV=","_$GET(ROLECSV)_","
	IF CSV=",," QUIT 1
	FOR I=1:1:$LENGTH($GET(STATE("roles")),",") DO  QUIT:$GET(R)'=""
	. NEW X SET X=$PIECE($GET(STATE("roles")),",",I) QUIT:X=""
	. IF CSV[","_X_"," SET R=X
	QUIT $SELECT(R'="":1,1:0)
	;
CAN(ID,STATE,MODE)
	NEW OWNER,ROLES,FLAG,USER
	SET USER=$GET(STATE("principal"))
	IF USER="" SET USER="guest"
	IF '$$EXISTS(ID) QUIT 0
	SET OWNER=$$FIELD(ID,8),ROLES=$$FIELD(ID,9)
	IF USER=OWNER QUIT 1
	IF '$$ROLEOK(ROLES,.STATE) QUIT 0
	SET FLAG=$SELECT($GET(MODE)="write":$$FIELD(ID,11),$GET(MODE)="delete":$$FIELD(ID,12),1:$$FIELD(ID,10))
	QUIT +FLAG
	;
MKDIRID(PARENT,NAME,OWNER,ROLES,OUTID)
	NEW ID,NOW
	SET OUTID=""
	IF '$$VALIDNAME($GET(NAME)) QUIT
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PARENT,NAME))
	IF OUTID'="",$$EXISTS(OUTID),$$FIELD(OUTID,1)="folder" QUIT
	IF OUTID'="" KILL ^MIO("MIOOS","FS","CHILD",PARENT,NAME)
	SET ID=$$NEXTID(),NOW=$HOROLOG
	DO SAVEENTRY(ID,"folder",PARENT,NAME,"inode/directory",0,NOW,NOW,$GET(OWNER),$GET(ROLES),1,1,1)
	SET ^MIO("MIOOS","FS","CHILD",PARENT,NAME)=ID
	SET OUTID=ID
	QUIT
	;
MKDIR(STATE,PARENT,NAME,OUT,ERR)
	NEW PID,OWNER,ROLES,ID
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$VALIDNAME($GET(NAME)) SET ERR("error")="invalid_name" QUIT 0
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	IF $GET(^MIO("MIOOS","FS","CHILD",PID,NAME))'="" SET ERR("error")="name_conflict" QUIT 0
	SET OWNER=$GET(STATE("principal"),"guest"),ROLES=$GET(STATE("roles"),"guest")
	DO MKDIRID(PID,$GET(NAME),OWNER,ROLES,.ID)
	IF ID="" SET ERR("error")="mkdir_failed" QUIT 0
	DO META(.STATE,ID,.OUT,.ERR)
	QUIT 1
	;
WRITEFILE(PARENT,NAME,DATA,MIME,OWNER,ROLES,OUTID)
	NEW NOW,CHUNK,POS,IDX,LEN,SIZE,U
	SET U="^",NOW=$HOROLOG,CHUNK=2048
	IF '$$VALIDNAME($GET(NAME)) SET OUTID="" QUIT
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PARENT,NAME))
	IF OUTID'="",('$$EXISTS(OUTID)!($$FIELD(OUTID,1)'="file")) DO
	. KILL ^MIO("MIOOS","FS","CHILD",PARENT,NAME)
	. SET OUTID=""
	IF OUTID="" DO
	. SET OUTID=$$NEXTID()
	. DO SAVEENTRY(OUTID,"file",PARENT,NAME,$GET(MIME,"application/octet-stream"),0,NOW,NOW,$GET(OWNER),$GET(ROLES),1,1,1)
	. SET ^MIO("MIOOS","FS","CHILD",PARENT,NAME)=OUTID
	KILL ^MIO("MIOOS","FS","DATA",OUTID)
	SET LEN=$LENGTH($GET(DATA)),SIZE=LEN,IDX=0
	IF LEN=0 SET ^MIO("MIOOS","FS","DATA",OUTID,1)=""
	FOR POS=1:CHUNK:LEN DO
	. SET IDX=IDX+1
	. SET ^MIO("MIOOS","FS","DATA",OUTID,IDX)=$EXTRACT(DATA,POS,POS+CHUNK-1)
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,1)="file"
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,2)=PARENT
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,3)=NAME
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,4)=$GET(MIME,"application/octet-stream")
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,5)=SIZE
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,7)=NOW
	QUIT
	;
WRITE(STATE,PARENT,NAME,DATA,MIME,OUT,ERR)
	NEW PID,OWNER,ROLES,ID
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$VALIDNAME($GET(NAME)) SET ERR("error")="invalid_name" QUIT 0
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	SET OWNER=$GET(STATE("principal"),"guest"),ROLES=$GET(STATE("roles"),"guest")
	DO WRITEFILE(PID,$GET(NAME),$GET(DATA),$GET(MIME,"application/octet-stream"),OWNER,ROLES,.ID)
	IF ID="" SET ERR("error")="write_failed" QUIT 0
	DO META(.STATE,ID,.OUT,.ERR)
	QUIT 1
	;
READ(STATE,ID,OUT,ERR)
	NEW RID,I,TXT
	SET ERR("routine")="MIOOSFS",TXT=""
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF '$$CAN(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)'="file" SET ERR("error")="not_file" QUIT 0
	SET I=0 FOR  SET I=$ORDER(^MIO("MIOOS","FS","DATA",RID,I)) QUIT:I'>0  SET TXT=TXT_$GET(^MIO("MIOOS","FS","DATA",RID,I))
	SET OUT("id")=RID
	SET OUT("kind")="file"
	SET OUT("name")=$$FIELD(RID,3)
	SET OUT("mime")=$$FIELD(RID,4)
	SET OUT("size")=+$$FIELD(RID,5)
	SET OUT("path")=$$PATH(RID)
	SET OUT("content")=TXT
	QUIT 1
	;
READRAW(ID,OUT,SIZE)
	NEW RID,I
	SET OUT="",SIZE=0,RID=$GET(ID)
	IF '$$EXISTS(RID) QUIT 0
	IF $$FIELD(RID,1)'="file" QUIT 0
	SET I=0 FOR  SET I=$ORDER(^MIO("MIOOS","FS","DATA",RID,I)) QUIT:I'>0  SET OUT=OUT_$GET(^MIO("MIOOS","FS","DATA",RID,I))
	SET SIZE=$LENGTH(OUT)
	QUIT 1
	;
READRANGE(ID,OFFSET,LEN,OUT,READ,ERR)
	NEW RAW,SIZE
	SET ERR("routine")="MIOOSFS",OUT="",READ=0
	IF '$$READRAW($GET(ID),.RAW,.SIZE) SET ERR("error")="not_file" QUIT 0
	SET OFFSET=+$GET(OFFSET),LEN=+$GET(LEN)
	IF OFFSET<0 SET OFFSET=0
	IF LEN<0 SET LEN=0
	IF LEN=0 QUIT 1
	SET OUT=$EXTRACT(RAW,OFFSET+1,OFFSET+LEN)
	SET READ=$LENGTH(OUT)
	QUIT 1
	;
HASH(STATE,ID,OUT,ERR)
	NEW RID,TXT,SIZE
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF '$$CAN(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF '$$READRAW(RID,.TXT,.SIZE) SET ERR("error")="not_file" QUIT 0
	SET OUT("id")=RID
	SET OUT("name")=$$FIELD(RID,3)
	SET OUT("path")=$$PATH(RID)
	SET OUT("mime")=$$FIELD(RID,4)
	SET OUT("size")=SIZE
	SET OUT("sha256")=$$SHA256^MIOSHA256(TXT)
	QUIT 1
	;
SEARCH(STATE,PARENT,QUERY,RECURSE,LIMIT,OUT,ERR)
	NEW PID,TERM,COUNT
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	SET TERM=$$LOW^MIOUTIL($$TRIM^MIOUTIL($GET(QUERY)))
	SET LIMIT=+$GET(LIMIT) IF LIMIT<1 SET LIMIT=50
	SET OUT("folder","id")=PID
	SET OUT("folder","path")=$$PATH(PID)
	SET OUT("query")=$GET(QUERY)
	SET OUT("recurse")=+$GET(RECURSE)
	SET OUT("limit")=LIMIT
	SET COUNT=0
	DO SEARCH1(.STATE,PID,TERM,+$GET(RECURSE),LIMIT,.COUNT,$NAME(OUT("entries")),.ERR)
	SET OUT("count")=COUNT
	QUIT 1
	;
SEARCH1(STATE,PID,TERM,RECURSE,LIMIT,COUNT,ROOT,ERR)
	NEW NAME,ID,META,LOW,OK
	SET NAME=""
	FOR  SET NAME=$ORDER(^MIO("MIOOS","FS","CHILD",PID,NAME)) QUIT:NAME=""!(COUNT'<LIMIT)  DO
	. SET ID=$GET(^MIO("MIOOS","FS","CHILD",PID,NAME))
	. IF '$$CAN(ID,.STATE,"read") QUIT
	. SET LOW=$$LOW^MIOUTIL($GET(NAME))
	. IF TERM=""!(LOW[TERM) DO
	. . KILL META
	. . SET OK=$$META(.STATE,ID,.META,.ERR)
	. . IF OK DO
	. . . SET COUNT=COUNT+1
	. . . MERGE @ROOT@(COUNT)=META
	. IF RECURSE,$$FIELD(ID,1)="folder",COUNT<LIMIT DO SEARCH1(.STATE,ID,TERM,RECURSE,LIMIT,.COUNT,ROOT,.ERR)
	QUIT
	;
META(STATE,ID,OUT,ERR)
	NEW RID
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT:$Q 0 QUIT
	IF '$$CAN(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT:$Q 0 QUIT
	SET OUT("id")=RID
	SET OUT("kind")=$$FIELD(RID,1)
	SET OUT("parentId")=$$FIELD(RID,2)
	SET OUT("name")=$$FIELD(RID,3)
	SET OUT("mime")=$$FIELD(RID,4)
	SET OUT("size")=+$$FIELD(RID,5)
	SET OUT("createdAt")=$$FIELD(RID,6)
	SET OUT("modifiedAt")=$$FIELD(RID,7)
	SET OUT("owner")=$$FIELD(RID,8)
	SET OUT("roles")=$$FIELD(RID,9)
	SET OUT("permRead")=+$$FIELD(RID,10)
	SET OUT("permWrite")=+$$FIELD(RID,11)
	SET OUT("permDelete")=+$$FIELD(RID,12)
	SET OUT("path")=$$PATH(RID)
	QUIT:$Q 1 QUIT
	;
LIST(STATE,PARENT,OUT,ERR)
	NEW PID,NAME,N,ID,META,OK
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	KILL META
	SET OK=$$META(.STATE,PID,.META,.ERR)
	IF 'OK QUIT 0
	MERGE OUT("folder")=META
	SET N=0,NAME=""
	FOR  SET NAME=$ORDER(^MIO("MIOOS","FS","CHILD",PID,NAME)) QUIT:NAME=""  DO
	. SET ID=$GET(^MIO("MIOOS","FS","CHILD",PID,NAME))
	. IF '$$CAN(ID,.STATE,"read") QUIT
	. KILL META
	. SET OK=$$META(.STATE,ID,.META,.ERR)
	. IF 'OK QUIT
	. SET N=N+1
	. MERGE OUT("entries",N)=META
	SET OUT("count")=N
	QUIT 1
	;
RENAME(STATE,ID,NEWNAME,OUT,ERR)
	NEW RID,PID,OLD,U
	SET U="^",ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$VALIDNAME($GET(NEWNAME)) SET ERR("error")="invalid_name" QUIT 0
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	SET PID=$$FIELD(RID,2),OLD=$$FIELD(RID,3)
	IF PID="" SET ERR("error")="rename_root_forbidden" QUIT 0
	IF '$$CAN(RID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	IF NEWNAME'=OLD,$GET(^MIO("MIOOS","FS","CHILD",PID,NEWNAME))'="" SET ERR("error")="name_conflict" QUIT 0
	KILL ^MIO("MIOOS","FS","CHILD",PID,OLD)
	SET ^MIO("MIOOS","FS","CHILD",PID,$GET(NEWNAME))=RID
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,3)=$GET(NEWNAME)
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,7)=$HOROLOG
	DO META(.STATE,RID,.OUT,.ERR)
	QUIT 1
	;
ISDESC(ANCESTOR,ID)
	NEW CUR,FOUND
	SET CUR=$GET(ID),FOUND=0
	FOR  QUIT:CUR=""!(FOUND=1)  DO
	. IF CUR=$GET(ANCESTOR) SET FOUND=1 QUIT
	. SET CUR=$$FIELD(CUR,2)
	QUIT FOUND
	;
MOVE(STATE,ID,NEWPARENT,OUT,ERR)
	NEW RID,NPID,OPID,NAME,U
	SET U="^",ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF RID="root" SET ERR("error")="move_root_forbidden" QUIT 0
	IF '$$RESOLVE($GET(NEWPARENT),.NPID,.ERR) QUIT 0
	IF $$FIELD(NPID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF ('$$CAN(RID,.STATE,"write"))!('$$CAN(NPID,.STATE,"write")) SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)="folder",$$ISDESC(RID,NPID) SET ERR("error")="move_cycle_forbidden" QUIT 0
	SET OPID=$$FIELD(RID,2),NAME=$$FIELD(RID,3)
	IF $GET(^MIO("MIOOS","FS","CHILD",NPID,NAME))'="",$GET(^MIO("MIOOS","FS","CHILD",NPID,NAME))'=RID SET ERR("error")="name_conflict" QUIT 0
	IF OPID'="" KILL ^MIO("MIOOS","FS","CHILD",OPID,NAME)
	SET ^MIO("MIOOS","FS","CHILD",NPID,NAME)=RID
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,2)=NPID
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,7)=$HOROLOG
	DO META(.STATE,RID,.OUT,.ERR)
	QUIT 1
	;
DELETE(STATE,ID,OUT,ERR)
	NEW RID,PID,NAME
	SET ERR("routine")="MIOOSFS"
	KILL OUT
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF RID="root" SET ERR("error")="delete_root_forbidden" QUIT 0
	IF '$$CAN(RID,.STATE,"delete") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)="folder",$ORDER(^MIO("MIOOS","FS","CHILD",RID,""))'="" SET ERR("error")="folder_not_empty" QUIT 0
	SET PID=$$FIELD(RID,2),NAME=$$FIELD(RID,3)
	KILL ^MIO("MIOOS","FS","DATA",RID)
	KILL ^MIO("MIOOS","FS","CHILD",RID)
	KILL ^MIO("MIOOS","FS","ENTRY",RID)
	IF PID'="" KILL ^MIO("MIOOS","FS","CHILD",PID,NAME)
	SET OUT("id")=RID,OUT("deleted")=1
	QUIT 1
	;
