MIOOSFS ; MIOOS global-backed virtual file system
	QUIT
	;
CHUNK(CONF)
	NEW N
	SET N=+$GET(CONF("mioos","fs","chunkSize"),2048)
	IF N<256 SET N=256
	QUIT N
	;
INIT(CONF)
	NEW ROOT,DOCS,DESK,OWNER,ROLES
	SET OWNER=$GET(CONF("mioos","bootstrapAuth","admin","username"),"admin")
	SET ROLES="admin,operator,guest"
	IF '$DATA(^MIO("MIOOS","FS","SEQ")) SET ^MIO("MIOOS","FS","SEQ")=0
	IF '$DATA(^MIO("MIOOS","FS","ENTRY","root")) DO
	. DO SAVEENTRY("root","folder","","/","inode/directory",0,$HOROLOG,$HOROLOG,OWNER,ROLES,1,1,1)
	IF '$DATA(^MIO("MIOOS","FS","CHILD","root","Desktop")) DO
	. DO MKDIRID("root","Desktop",OWNER,ROLES,.DESK)
	IF '$DATA(^MIO("MIOOS","FS","CHILD","root","Documents")) DO
	. DO MKDIRID("root","Documents",OWNER,ROLES,.DOCS)
	IF '$DATA(^MIO("MIOOS","FS","CHILD","root","README.txt")) DO
	. DO WRITEFILE("root","README.txt","Welcome to MIOOS VFS","text/plain",OWNER,ROLES,.ROOT)
	QUIT
	;
NEXTID()
	NEW N
	SET N=$INCREMENT(^MIO("MIOOS","FS","SEQ"))
	QUIT "fs-"_N
	;
SAVEENTRY(ID,KIND,PARENT,NAME,MIME,SIZE,CDT,MDT,OWNER,ROLES,CANR,CANW,CAND)
	NEW U SET U="^"
	SET ^MIO("MIOOS","FS","ENTRY",ID)=KIND_U_PARENT_U_NAME_U_MIME_U_SIZE_U_CDT_U_MDT_U_OWNER_U_ROLES_U_CANR_U_CANW_U_CAND
	QUIT
	;
EXISTS(ID)
	QUIT $DATA(^MIO("MIOOS","FS","ENTRY",$GET(ID)))#2
	;
FIELD(ID,PIECE)
	NEW U SET U="^"
	QUIT $PIECE($GET(^MIO("MIOOS","FS","ENTRY",$GET(ID))),U,+$GET(PIECE))
	;
ROOTID()
	QUIT "root"
	;
HOMEID()
	NEW ID
	SET ID=$GET(^MIO("MIOOS","FS","CHILD","root","Documents"))
	IF ID="" SET ID="root"
	QUIT ID
	;
RESOLVE(PATH,OUTID,ERR)
	NEW I,NODE,NAME
	SET ERR("routine")="MIOOSFS",OUTID=""
	IF $GET(PATH)="" SET ERR("error")="path_missing" QUIT 0
	IF PATH="root" SET OUTID="root" QUIT 1
	IF $EXTRACT(PATH,1)'="/" DO  QUIT:$GET(OUTID)'="" 1
	. IF $$EXISTS(PATH) SET OUTID=PATH QUIT
	. SET PATH="/"_PATH
	SET NODE="root"
	IF PATH="/" SET OUTID=NODE QUIT 1
	FOR I=2:1:$LENGTH(PATH,"/") DO  QUIT:NODE=""
	. SET NAME=$PIECE(PATH,"/",I)
	. QUIT:NAME=""
	. SET NODE=$GET(^MIO("MIOOS","FS","CHILD",NODE,NAME))
	IF NODE="" SET ERR("error")="path_not_found",ERR("detail")=PATH QUIT 0
	SET OUTID=NODE
	QUIT 1
	;
PATH(ID)
	NEW CUR,NAME,OUT,PARENT
	IF $GET(ID)="" QUIT ""
	IF ID="root" QUIT "/"
	SET CUR=ID,OUT=""
	FOR  DO  QUIT:CUR=""!(CUR="root")
	. SET NAME=$$FIELD(CUR,3),PARENT=$$FIELD(CUR,2)
	. SET OUT="/"_NAME_OUT
	. SET CUR=PARENT
	IF OUT="" SET OUT="/"
	QUIT OUT
	;
ROLEOK(ROLECSV,STATE)
	NEW I,ROLE,CSV
	SET CSV=","_$GET(ROLECSV)_","
	IF CSV=",," QUIT 1
	FOR I=1:1:$LENGTH($GET(STATE("roles")),",") DO  QUIT:$GET(ROLE)'=""
	. NEW R SET R=$PIECE($GET(STATE("roles")),",",I) QUIT:R=""
	. IF CSV[","_R_"," SET ROLE=R
	QUIT $SELECT(ROLE'="":1,1:0)
	;
CAN(ID,STATE,MODE)
	NEW OWNER,ROLES,FLAG,USER
	SET USER=$GET(STATE("principal"))
	IF USER="" SET USER="guest"
	IF '$$EXISTS(ID) QUIT 0
	SET OWNER=$$FIELD(ID,8),ROLES=$$FIELD(ID,9)
	IF USER=OWNER QUIT 1
	IF '$$ROLEOK(ROLES,.STATE) QUIT 0
	SET FLAG=$SELECT($GET(MODE)="write":$$FIELD(ID,11),$GET(MODE)="delete":$$FIELD(ID,12),1:$$FIELD(ID,10))
	QUIT +FLAG
	;
MKDIRID(PARENT,NAME,OWNER,ROLES,OUTID)
	NEW ID,NOW
	SET OUTID=""
	IF $GET(^MIO("MIOOS","FS","CHILD",PARENT,NAME))'="" SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PARENT,NAME)) QUIT
	SET ID=$$NEXTID(),NOW=$HOROLOG
	DO SAVEENTRY(ID,"folder",PARENT,NAME,"inode/directory",0,NOW,NOW,$GET(OWNER),$GET(ROLES),1,1,1)
	SET ^MIO("MIOOS","FS","CHILD",PARENT,NAME)=ID
	SET OUTID=ID
	QUIT
	;
MKDIR(STATE,PARENT,NAME,OUT,ERR)
	NEW PID,OWNER,ROLES
	SET ERR("routine")="MIOOSFS"
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	SET OWNER=$GET(STATE("principal"),"guest"),ROLES=$GET(STATE("roles"),"guest")
	N TARR M TARR=OUT("id")
	DO MKDIRID(PID,$GET(NAME),OWNER,ROLES,.TARR)
	M OUT("id")=TARR K TARR
	DO META(.STATE,$GET(OUT("id")),.OUT,.ERR)
	QUIT 1
	;
WRITEFILE(PARENT,NAME,DATA,MIME,OWNER,ROLES,OUTID)
	NEW ID,NOW,CHUNK,POS,IDX,LEN,SIZE
	NEW U SET U="^"
	SET OUTID=$GET(^MIO("MIOOS","FS","CHILD",PARENT,NAME))
	SET NOW=$HOROLOG,CHUNK=2048
	IF OUTID="" DO
	. SET OUTID=$$NEXTID()
	. DO SAVEENTRY(OUTID,"file",PARENT,NAME,$GET(MIME,"application/octet-stream"),0,NOW,NOW,$GET(OWNER),$GET(ROLES),1,1,1)
	. SET ^MIO("MIOOS","FS","CHILD",PARENT,NAME)=OUTID
	ELSE  DO
	. KILL ^MIO("MIOOS","FS","DATA",OUTID)
	SET LEN=$LENGTH($GET(DATA)),SIZE=LEN,IDX=0
	FOR POS=1:CHUNK:LEN DO
	. SET IDX=IDX+1
	. SET ^MIO("MIOOS","FS","DATA",OUTID,IDX)=$EXTRACT(DATA,POS,POS+CHUNK-1)
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,4)=$GET(MIME,"application/octet-stream")
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,5)=SIZE
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",OUTID),U,7)=NOW
	QUIT
	;
WRITE(STATE,PARENT,NAME,DATA,MIME,OUT,ERR)
	NEW PID,OWNER,ROLES,ID
	SET ERR("routine")="MIOOSFS"
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	SET OWNER=$GET(STATE("principal"),"guest"),ROLES=$GET(STATE("roles"),"guest")
	DO WRITEFILE(PID,$GET(NAME),$GET(DATA),$GET(MIME,"application/octet-stream"),OWNER,ROLES,.ID)
	DO META(.STATE,ID,.OUT,.ERR)
	QUIT 1
	;
READ(STATE,ID,OUT,ERR)
	NEW RID,I,TXT
	SET ERR("routine")="MIOOSFS",TXT=""
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF '$$CAN(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)'="file" SET ERR("error")="not_file" QUIT 0
	SET I=0 FOR  SET I=$ORDER(^MIO("MIOOS","FS","DATA",RID,I)) QUIT:I'>0  SET TXT=TXT_$GET(^MIO("MIOOS","FS","DATA",RID,I))
	SET OUT("id")=RID
	SET OUT("name")=$$FIELD(RID,3)
	SET OUT("mime")=$$FIELD(RID,4)
	SET OUT("size")=+$$FIELD(RID,5)
	SET OUT("path")=$$PATH(RID)
	SET OUT("content")=TXT
	QUIT 1
	;
META(STATE,ID,OUT,ERR)
	NEW RID
	SET ERR("routine")="MIOOSFS"
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT:$Q 0 Q
	IF '$$CAN(RID,.STATE,"read") SET ERR("error")="access_denied" QUIT:$Q 0 Q
	KILL OUT
	SET OUT("id")=RID
	SET OUT("kind")=$$FIELD(RID,1)
	SET OUT("parentId")=$$FIELD(RID,2)
	SET OUT("name")=$$FIELD(RID,3)
	SET OUT("mime")=$$FIELD(RID,4)
	SET OUT("size")=+$$FIELD(RID,5)
	SET OUT("createdAt")=$$FIELD(RID,6)
	SET OUT("modifiedAt")=$$FIELD(RID,7)
	SET OUT("owner")=$$FIELD(RID,8)
	SET OUT("roles")=$$FIELD(RID,9)
	SET OUT("permRead")=+$$FIELD(RID,10)
	SET OUT("permWrite")=+$$FIELD(RID,11)
	SET OUT("permDelete")=+$$FIELD(RID,12)
	SET OUT("path")=$$PATH(RID)
	QUIT:$Q 1 Q
	;
LIST(STATE,PARENT,OUT,ERR)
	NEW PID,NAME,N,ID,META
	SET ERR("routine")="MIOOSFS"
	IF '$$RESOLVE($GET(PARENT),.PID,.ERR) QUIT 0
	IF $$FIELD(PID,1)'="folder" SET ERR("error")="not_folder" QUIT 0
	IF '$$CAN(PID,.STATE,"read") SET ERR("error")="access_denied" QUIT 0
	KILL OUT N TARR M TARR=OUT("folder")
	DO META(.STATE,PID,.TARR,.ERR)
	M OUT("folder")=TARR K TARR
	SET N=0,NAME=""
	FOR  SET NAME=$ORDER(^MIO("MIOOS","FS","CHILD",PID,NAME)) QUIT:NAME=""  DO
	. SET ID=$GET(^MIO("MIOOS","FS","CHILD",PID,NAME))
	. IF '$$CAN(ID,.STATE,"read") QUIT
	. SET N=N+1
	. DO META(.STATE,ID,.META,.ERR)
	. MERGE OUT("entries",N)=META
	SET OUT("count")=N
	QUIT 1
	;
RENAME(STATE,ID,NEWNAME,OUT,ERR)
	NEW RID,PID,OLD,U SET U="^"
	SET ERR("routine")="MIOOSFS"
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	SET PID=$$FIELD(RID,2),OLD=$$FIELD(RID,3)
	IF '$$CAN(RID,.STATE,"write") SET ERR("error")="access_denied" QUIT 0
	IF PID="" SET ERR("error")="rename_root_forbidden" QUIT 0
	KILL ^MIO("MIOOS","FS","CHILD",PID,OLD)
	SET ^MIO("MIOOS","FS","CHILD",PID,$GET(NEWNAME))=RID
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,3)=$GET(NEWNAME)
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,7)=$HOROLOG
	DO META(.STATE,RID,.OUT,.ERR)
	QUIT 1
	;
MOVE(STATE,ID,NEWPARENT,OUT,ERR)
	NEW RID,NPID,OPID,NAME,U SET U="^"
	SET ERR("routine")="MIOOSFS"
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF '$$RESOLVE($GET(NEWPARENT),.NPID,.ERR) QUIT 0
	IF $$FIELD(NPID,1)'="folder" SET ERR("error")="parent_not_folder" QUIT 0
	IF ('$$CAN(RID,.STATE,"write"))!('$$CAN(NPID,.STATE,"write")) SET ERR("error")="access_denied" QUIT 0
	SET OPID=$$FIELD(RID,2),NAME=$$FIELD(RID,3)
	IF OPID'="" KILL ^MIO("MIOOS","FS","CHILD",OPID,NAME)
	SET ^MIO("MIOOS","FS","CHILD",NPID,NAME)=RID
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,2)=NPID
	SET $PIECE(^MIO("MIOOS","FS","ENTRY",RID),U,7)=$HOROLOG
	DO META(.STATE,RID,.OUT,.ERR)
	QUIT 1
	;
DELETE(STATE,ID,OUT,ERR)
	NEW RID,PID,NAME
	SET ERR("routine")="MIOOSFS"
	IF '$$RESOLVE($GET(ID),.RID,.ERR) QUIT 0
	IF RID="root" SET ERR("error")="delete_root_forbidden" QUIT 0
	IF '$$CAN(RID,.STATE,"delete") SET ERR("error")="access_denied" QUIT 0
	IF $$FIELD(RID,1)="folder",$ORDER(^MIO("MIOOS","FS","CHILD",RID,""))'="" SET ERR("error")="folder_not_empty" QUIT 0
	SET PID=$$FIELD(RID,2),NAME=$$FIELD(RID,3)
	KILL ^MIO("MIOOS","FS","DATA",RID)
	KILL ^MIO("MIOOS","FS","ENTRY",RID)
	IF PID'="" KILL ^MIO("MIOOS","FS","CHILD",PID,NAME)
	SET OUT("id")=RID,OUT("deleted")=1
	QUIT 1
	;