MIOUIBILLT ; MIOUI billing component test runner
 D START Q
 ;
START
 N FAIL
 S FAIL=0
 D START^MIOUIBILLT001(.FAIL)
 D START^MIOUIBILLT002(.FAIL)
 D START^MIOUIBILLT003(.FAIL)
 D START^MIOUIBILLT004(.FAIL)
 I 'FAIL W !,"OK - MIOUIBILLT"
 Q
 ;
