MIOUICOL ; Collaboration routes and renderers for MIOUI
 Q
 ;
REG(CONF)
 N META
 K META S META("authRequired")=0,META("roles")=""
 D REG1("GET","/mioui/collab-presence","PRESENCE^MIOUICOL",.META)
 D REG1("GET","/mioui/collab-avatars","AVATARS^MIOUICOL",.META)
 D REG1("GET","/mioui/collab-users","USERS^MIOUICOL",.META)
 D REG1("GET","/mioui/collab-chat","CHAT^MIOUICOL",.META)
 D REG1("GET","/mioui/collab-chat-dense","CHATDNS^MIOUICOL",.META)
 D REG1("GET","/mioui/collab-chat-balanced","CHATBAL^MIOUICOL",.META)
 D REG1("GET","/mioui/collab-onboarding","ONBOARD^MIOUICOL",.META)
 D REG1("GET","/mioui/collab-onboarding-dense","ONBDNS^MIOUICOL",.META)
 D REG1("GET","/mioui/collab-onboarding-guided","ONBGUIDE^MIOUICOL",.META)
 Q
 ;
REG1(METHOD,PATH,TARGET,META)
 D ADDM^MIOROUTE($G(METHOD),$G(PATH),$G(TARGET),.META)
 S ^MIO("ROUTE","RAW",$G(METHOD),$G(PATH))=$G(TARGET)
 S ^MIO("ROUTE","META",$G(METHOD),$G(PATH),"authRequired")=+$G(META("authRequired"))
 S ^MIO("ROUTE","META",$G(METHOD),$G(PATH),"roles")=$G(META("roles"))
 Q
 ;
PRESENCE(DEV,CONF,REQ,CTX)
 N TCTX,OUT,ERR
 D BUILDPR^MIOUICOLD(.CONF,.REQ,.CTX,.TCTX)
 D RENDER("pages/miouicol_presence.html",.CONF,.CTX,.TCTX,.OUT,.ERR)
 I $D(ERR) D RESPERR^MIOUIDEMO(.DEV,.CONF,.CTX,500,"template_error") Q
 D RESPHTML^MIOUIDEMO(.DEV,.CONF,.CTX,.OUT)
 Q
 ;
AVATARS(DEV,CONF,REQ,CTX)
 N TCTX,OUT,ERR
 D BUILDAV^MIOUICOLD(.CONF,.REQ,.CTX,.TCTX)
 D RENDER("pages/miouicol_avatars.html",.CONF,.CTX,.TCTX,.OUT,.ERR)
 I $D(ERR) D RESPERR^MIOUIDEMO(.DEV,.CONF,.CTX,500,"template_error") Q
 D RESPHTML^MIOUIDEMO(.DEV,.CONF,.CTX,.OUT)
 Q
 ;
USERS(DEV,CONF,REQ,CTX)
 N TCTX,OUT,ERR
 D BUILDUS^MIOUICOLD(.CONF,.REQ,.CTX,.TCTX)
 D RENDER("pages/miouicol_users.html",.CONF,.CTX,.TCTX,.OUT,.ERR)
 I $D(ERR) D RESPERR^MIOUIDEMO(.DEV,.CONF,.CTX,500,"template_error") Q
 D RESPHTML^MIOUIDEMO(.DEV,.CONF,.CTX,.OUT)
 Q
 ;
CHAT(DEV,CONF,REQ,CTX)
 N TCTX,OUT,ERR
 D BUILDCH^MIOUICOLD(.CONF,.REQ,.CTX,.TCTX,"standard")
 D RENDER("pages/miouicol_chat.html",.CONF,.CTX,.TCTX,.OUT,.ERR)
 I $D(ERR) D RESPERR^MIOUIDEMO(.DEV,.CONF,.CTX,500,"template_error") Q
 D RESPHTML^MIOUIDEMO(.DEV,.CONF,.CTX,.OUT)
 Q
 ;
CHATDNS(DEV,CONF,REQ,CTX)
 N TCTX,OUT,ERR
 D BUILDCH^MIOUICOLD(.CONF,.REQ,.CTX,.TCTX,"dense")
 D RENDER("pages/miouicol_chat_dense.html",.CONF,.CTX,.TCTX,.OUT,.ERR)
 I $D(ERR) D RESPERR^MIOUIDEMO(.DEV,.CONF,.CTX,500,"template_error") Q
 D RESPHTML^MIOUIDEMO(.DEV,.CONF,.CTX,.OUT)
 Q
 ;
CHATBAL(DEV,CONF,REQ,CTX)
 N TCTX,OUT,ERR
 D BUILDCH^MIOUICOLD(.CONF,.REQ,.CTX,.TCTX,"balanced")
 D RENDER("pages/miouicol_chat_balanced.html",.CONF,.CTX,.TCTX,.OUT,.ERR)
 I $D(ERR) D RESPERR^MIOUIDEMO(.DEV,.CONF,.CTX,500,"template_error") Q
 D RESPHTML^MIOUIDEMO(.DEV,.CONF,.CTX,.OUT)
 Q
 ;
ONBOARD(DEV,CONF,REQ,CTX)
 N TCTX,OUT,ERR
 D BUILDON^MIOUICOLD(.CONF,.REQ,.CTX,.TCTX,"standard")
 D RENDER("pages/miouicol_onboarding.html",.CONF,.CTX,.TCTX,.OUT,.ERR)
 I $D(ERR) D RESPERR^MIOUIDEMO(.DEV,.CONF,.CTX,500,"template_error") Q
 D RESPHTML^MIOUIDEMO(.DEV,.CONF,.CTX,.OUT)
 Q
 ;
ONBDNS(DEV,CONF,REQ,CTX)
 N TCTX,OUT,ERR
 D BUILDON^MIOUICOLD(.CONF,.REQ,.CTX,.TCTX,"dense")
 D RENDER("pages/miouicol_onboarding_dense.html",.CONF,.CTX,.TCTX,.OUT,.ERR)
 I $D(ERR) D RESPERR^MIOUIDEMO(.DEV,.CONF,.CTX,500,"template_error") Q
 D RESPHTML^MIOUIDEMO(.DEV,.CONF,.CTX,.OUT)
 Q
 ;
ONBGUIDE(DEV,CONF,REQ,CTX)
 N TCTX,OUT,ERR
 D BUILDON^MIOUICOLD(.CONF,.REQ,.CTX,.TCTX,"guided")
 D RENDER("pages/miouicol_onboarding_guided.html",.CONF,.CTX,.TCTX,.OUT,.ERR)
 I $D(ERR) D RESPERR^MIOUIDEMO(.DEV,.CONF,.CTX,500,"template_error") Q
 D RESPHTML^MIOUIDEMO(.DEV,.CONF,.CTX,.OUT)
 Q
 ;
RENDER(PAGE,CONF,CTX,TCTX,OUT,ERR)
 D INIT^MIOUI(.CONF)
 D RENDERPAGE^MIOTPL($G(PAGE),"layouts/mioui_app.html",.CONF,.TCTX,.OUT,.ERR)
 Q
 ;
