MIOUIBILLT ; MIOUI billing component test runner
 D START Q
 ;
START
 N FAIL
 S FAIL=0
 D START^MIOUIBILLT001(.FAIL)
 D START^MIOUIBILLT002(.FAIL)
 D START^MIOUIBILLT003(.FAIL)
 D START^MIOUIBILLT004(.FAIL)
 D START^MIOUIBILLT005(.FAIL)
 D START^MIOUIBILLT006(.FAIL)
 D START^MIOUIBILLT007(.FAIL)
 D START^MIOUIBILLT008(.FAIL)
 D START^MIOUIBILLT009(.FAIL)
 D START^MIOUIBILLT010(.FAIL)
 D START^MIOUIBILLT011(.FAIL)
 D START^MIOUIBILLT012(.FAIL)
 D START^MIOUIBILLT013(.FAIL)
 D START^MIOUIBILLT014(.FAIL)
 D START^MIOUIBILLT015(.FAIL)
 D START^MIOUIBILLT016(.FAIL)
 I 'FAIL W !,"OK - MIOUIBILLT"
 Q
 ;
