MIOUICOLT ; Collaboration UI test runner
 D START Q
 ;
START(FAIL)
 N LOCAL,TOP
 S TOP='$D(FAIL),LOCAL=0
 D START^MIOUICOLT001(.LOCAL)
 D START^MIOUICOLT002(.LOCAL)
 D START^MIOUICOLT003(.LOCAL)
 D START^MIOUICOLT004(.LOCAL)
 D START^MIOUICOLT005(.LOCAL)
 D START^MIOUICOLT006(.LOCAL)
 I TOP D  Q
 . I 'LOCAL W !,"OK - MIOUICOLT"
 I LOCAL S FAIL=1
 Q
 ;
