MIOWST ; MIOWS streaming parse tests
;
; Run:
;   YDB>ZL "MIOWS.m","MIOWST.m","MIOTASSERT.m","MIOSOCK.m"
;   YDB>D ^MIOWST
;
	DO T001
	DO T002
	DO T003
	DO T004
	DO T005
	QUIT
	;
TMPPATH(NAME)
	QUIT "tmp/miowst_"_NAME_"_"_$J_"_"_$P($H,",",2)_".bin"
	;
WRFILE(PATH,TXT)
	NEW DEV SET DEV=PATH
	OPEN DEV:(new:stream:nowrap):1 ELSE  QUIT
	USE DEV WRITE TXT
	CLOSE DEV
	QUIT
	;
OPENR(PATH)
	NEW DEV SET DEV=PATH
	OPEN DEV:(readonly:stream):1 ELSE  QUIT ""
	QUIT DEV
	;
CLOSER(DEV)
	IF $GET(DEV)'="" CLOSE DEV
	QUIT
	;
REPEAT(CH,N)
	NEW I,S SET S=""
	FOR I=1:1:N SET S=S_CH
	QUIT S
	;
MASKPAY(PAY,MK)
	NEW I,O,P SET O=""
	FOR I=1:1:$L(PAY) SET P=((I-1)#4)+1,O=O_$C($$XOR^MIOWS($A(PAY,I),$A(MK,P),8))
	QUIT O
	;
LENHDR(LEN)
	IF LEN<126 QUIT $C(128+LEN)
	IF LEN<65536 QUIT $C(128+126)_$C(LEN\256)_$C(LEN#256)
	NEW I,REM,BUF SET BUF="",REM=LEN
	FOR I=8:-1:1 SET BUF=$C(REM#256)_BUF,REM=REM\256
	QUIT $C(128+127)_BUF
	;
FRAME(OPC,FIN,PAY,MK)
	NEW B1,MASKED
	SET B1=$C($SELECT(FIN:128,1:0)+OPC)
	SET MASKED=$$MASKPAY(PAY,MK)
	QUIT B1_$$LENHDR($L(PAY))_MK_MASKED
	;
SINK(CBCTX,MODE,SEG,META)
	IF MODE="start" SET CBCTX("start")=+$GET(CBCTX("start"))+1 QUIT
	IF MODE="end" SET CBCTX("end")=+$GET(CBCTX("end"))+1 QUIT
	IF MODE="data" DO
	. SET CBCTX("data")=+$GET(CBCTX("data"))+1
	. SET CBCTX("payload")=$GET(CBCTX("payload"))_$GET(SEG)
	QUIT
	;
T001 ; UNMSKSEG honors absolute offset
	NEW MK,PAY,MASKED,S1,S2
	SET MK="ABCD",PAY="HelloWorld"
	SET MASKED=$$MASKPAY(PAY,MK)
	SET S1=$$UNMSKSEG^MIOWS($EXTRACT(MASKED,1,4),MK,0)
	SET S2=$$UNMSKSEG^MIOWS($EXTRACT(MASKED,5,10),MK,4)
	DO EQ^MIOTASSERT(S1_S2,PAY,"[T001][unmaskseg offset]")
	QUIT
	;
T002 ; READFRAMEST streams one frame in bounded slices
	NEW PATH,DEV,MK,PAY,TXT,FIN,OPC,ERR,CBCTX
	SET PATH=$$TMPPATH("t002"),MK="MASK",PAY="HelloWorld"
	SET TXT=$$FRAME(1,1,PAY,MK)
	DO WRFILE(PATH,TXT)
	SET DEV=$$OPENR(PATH)
	KILL CBCTX,ERR
	DO READFRAMEST^MIOWS(.DEV,5,.FIN,.OPC,.ERR,65536,3,"SINK^MIOWST",.CBCTX)
	DO CLOSER(DEV)
	DO EQ^MIOTASSERT($DATA(ERR),0,"[T002][no err]")
	DO EQ^MIOTASSERT(FIN,1,"[T002][fin]")
	DO EQ^MIOTASSERT(OPC,1,"[T002][opc]")
	DO EQ^MIOTASSERT($GET(CBCTX("payload")),PAY,"[T002][payload]")
	DO EQ^MIOTASSERT($GET(CBCTX("data")),4,"[T002][chunk count]")
	QUIT
	;
T003 ; READMSGST streams fragmented message without buffering
	NEW PATH,DEV,MK,TXT,CONF,S,OPC,ERR,CBCTX,OK
	SET PATH=$$TMPPATH("t003"),MK="MASK"
	SET TXT=$$FRAME(1,0,"Hello",MK)_$$FRAME(0,1,"World",MK)
	DO WRFILE(PATH,TXT)
	SET DEV=$$OPENR(PATH)
	KILL CONF,S DO INITSTATE^MIOWS(.S,.CONF)
	KILL CBCTX,ERR
	SET OK=$$READMSGST^MIOWS(.DEV,.S,.OPC,.ERR,4,"SINK^MIOWST",.CBCTX)
	DO CLOSER(DEV)
	DO EQ^MIOTASSERT(OK,1,"[T003][ok]")
	DO EQ^MIOTASSERT($DATA(ERR),0,"[T003][no err]")
	DO EQ^MIOTASSERT(OPC,1,"[T003][opc]")
	DO EQ^MIOTASSERT($GET(CBCTX("start")),1,"[T003][start]")
	DO EQ^MIOTASSERT($GET(CBCTX("end")),1,"[T003][end]")
	DO EQ^MIOTASSERT($GET(CBCTX("payload")),"HelloWorld","[T003][payload]")
	QUIT
	;
T004 ; READFRAMEHDR parses extended payload length 126
	NEW PATH,DEV,MK,PAY,TXT,HDR,ERR
	SET PATH=$$TMPPATH("t004"),MK="MASK",PAY=$$REPEAT("A",300)
	SET TXT=$$FRAME(2,1,PAY,MK)
	DO WRFILE(PATH,TXT)
	SET DEV=$$OPENR(PATH)
	KILL HDR,ERR
	DO READFRAMEHDR^MIOWS(.DEV,5,.HDR,.ERR,65536)
	DO CLOSER(DEV)
	DO EQ^MIOTASSERT($DATA(ERR),0,"[T004][no err]")
	DO EQ^MIOTASSERT($GET(HDR("opc")),2,"[T004][opc]")
	DO EQ^MIOTASSERT($GET(HDR("len")),300,"[T004][len]")
	QUIT
	;
T005 ; READFRAMEHDR rejects oversized frames before payload buffering
	NEW PATH,DEV,MK,PAY,TXT,HDR,ERR
	SET PATH=$$TMPPATH("t005"),MK="MASK",PAY=$$REPEAT("B",300)
	SET TXT=$$FRAME(2,1,PAY,MK)
	DO WRFILE(PATH,TXT)
	SET DEV=$$OPENR(PATH)
	KILL HDR,ERR
	DO READFRAMEHDR^MIOWS(.DEV,5,.HDR,.ERR,128)
	DO CLOSER(DEV)
	DO EQ^MIOTASSERT($GET(ERR("error")),"ws_frame_too_large","[T005][frame too large]")
	QUIT
	;
