MIOJSON2
	; JSON HELPERS
	;
	Q
	;
MIOJSONET
		S ERRMSG=$ZSTATUS 
		G XERRX
ENCODE(MIOROOT,MIOJSON,MIOERR)
	S $ET="G MIOJSONET^MIOJSON2"
	S MIOERR=$G(MIOERR)
	I '$L($G(MIOROOT)) Q
	I '$L($G(MIOJSON)) Q
	N MIOLINE,MIOMAX,MIOERRORS
	S MIOLINE=1,MIOMAX=1048000,MIOERRORS=0
	S @MIOJSON@(MIOLINE)=""
	D SEROBJ(MIOROOT)
	Q
SEROBJ(MIOROOT)
	N MIOFIRST,MIOSUB,MIONXT
	S @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_"{"
	S MIOFIRST=1
	S MIOSUB="" F  S MIOSUB=$O(@MIOROOT@(MIOSUB)) Q:MIOSUB=""  D
	. S:'MIOFIRST @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_"," S MIOFIRST=0
	. D SERNAME(MIOSUB)
	. I $$ISVALUE(MIOROOT,MIOSUB) D SERVAL(MIOROOT,MIOSUB) Q
	. I $D(@MIOROOT@(MIOSUB))=10 S MIONXT=$O(@MIOROOT@(MIOSUB,"")) D  Q
	. . I +MIONXT D SERARY($NA(@MIOROOT@(MIOSUB))) I 1
	. . E  D SEROBJ($NA(@MIOROOT@(MIOSUB)))
	. D ERRX("SOB",MIOSUB)
	S @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_"}"
	Q
SERARY(MIOROOT)
	N MIOFIRST,MIOI,MIONXT
	S @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_"["
	S MIOFIRST=1
	S MIOI=0 F  S MIOI=$O(@MIOROOT@(MIOI)) Q:'MIOI  D
	. S:'MIOFIRST @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_"," S MIOFIRST=0
	. I $$ISVALUE(MIOROOT,MIOI) D SERVAL(MIOROOT,MIOI) Q 
	. I $D(@MIOROOT@(MIOI))=10 S MIONXT=$O(@MIOROOT@(MIOI,"")) D  Q
	. . I +MIONXT D SERARY($NA(@MIOROOT@(MIOI))) I 1
	. . E  D SEROBJ($NA(@MIOROOT@(MIOI)))
	. D ERRX("SAR",MIOI)
	S @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_"]"
	Q
SERNAME(MIOSUB)
	I ($L(MIOSUB)+$L(@MIOJSON@(MIOLINE)))>MIOMAX S MIOLINE=MIOLINE+1,@MIOJSON@(MIOLINE)=""
	S @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_""""_MIOSUB_""""_":"
	Q
SERVAL(MIOROOT,MIOSUB)
	N MIOX,MIOI
	I $D(@MIOROOT@(MIOSUB,":")) D  Q
	. S MIOX=$G(@MIOROOT@(MIOSUB,":")) D:$L(MIOX) CONCAT
	. S MIOI=0 F  S MIOI=$O(@MIOROOT@(MIOSUB,":",MIOI)) Q:'MIOI  S MIOX=@MIOROOT@(MIOSUB,":",MIOI) D CONCAT
	S MIOX=$G(@MIOROOT@(MIOSUB))
	I '$D(@MIOROOT@(MIOSUB,"\s")),$$NUMERIC(MIOX) D CONCAT QUIT
	I (MIOX="true")!(MIOX="false")!(MIOX="null") D CONCAT QUIT
	S MIOX=""""_$$ESC(MIOX)
	D CONCAT
	I $D(@MIOROOT@(MIOSUB,"\")) D
	. S MIOI=0 F  S MIOI=$O(@MIOROOT@(MIOSUB,"\",MIOI)) Q:'MIOI   D
	. . S MIOX=$$ESC(@MIOROOT@(MIOSUB,"\",MIOI))
	. . D CONCAT
	S MIOX="""" D CONCAT
	Q
CONCAT
	I ($L(MIOX)+$L(@MIOJSON@(MIOLINE)))>MIOMAX S MIOLINE=MIOLINE+1,@MIOJSON@(MIOLINE)=""
	S @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_MIOX
	Q
ISVALUE(MIOROOT,MIOSUB)
	I $D(@MIOROOT@(MIOSUB))#2 Q 1
	N MIOX S MIOX=$O(@MIOROOT@(MIOSUB,""))
	Q:MIOX="\" 1
	Q:MIOX=":" 1
	Q 0
NUMERIC(X) 
	;I $E(X,1,2)="-." Q 0
	I $E(X,1)="." Q 0
	I X=+X Q 1
	Q 0
	;Q $ISVALIDNUM(X)
ESC(X)
	N Y,%DH
	S Y=X
	I X["\"  S Y=$$REPLACE^MIOUTIL(Y,"\","\\")
	I X["""" S Y=$$REPLACE^MIOUTIL(Y,"""","\""")
	I X["/"  S Y=$$REPLACE^MIOUTIL(Y,"/","\/")
	I X[$C(8) S Y=$$REPLACE^MIOUTIL(Y,$C(8),"\"_$C(98))
	I X[$C(12) S Y=$$REPLACE^MIOUTIL(Y,$C(12),"\"_$C(102))
	I X[$C(10) S Y=$$REPLACE^MIOUTIL(Y,$C(10),"\"_$C(110))
	I X[$C(13) S Y=$$REPLACE^MIOUTIL(Y,$C(13),"\"_$C(114))
	I X[$C(9) S Y=$$REPLACE^MIOUTIL(Y,$C(9),"\"_$C(116))
	N I F I=1:1:$L(X) D
	. I $A($E(X,I))=8   Q 
	. I $A($E(X,I))=12  Q 
	. I $A($E(X,I))=10  Q 
	. I $A($E(X,I))=13  Q 
	. I $A($E(X,I))=9   Q 
	. I $A($E(X,I))>=32 Q
	. S %DH=$A($E(X,I))
	. D ^%DH
	. S Y=$$REPLACE^MIOUTIL(Y,$E(X,I),"\u"_$E(%DH,$L(%DH)-3,$L(%DH)))
	Q Y 
ERRX(ID,VAL)
	b
	N ERRMSG
	I ID="STL{" S ERRMSG="Stack too large for new object." G XERRX
	I ID="SUF}" S ERRMSG="Stack Underflow - extra } found" G XERRX
	I ID="STL[" S ERRMSG="Stack too large for new array." G XERRX
	I ID="SUF]" S ERRMSG="Stack Underflow - extra ] found." G XERRX
	I ID="OBM" S ERRMSG="Array MIOsmatch - expected ] got }." G XERRX
	I ID="ARM" S ERRMSG="Object MIOsmatch - expected } got ]." G XERRX
	I ID="MPN" S ERRMSG="MIOssing property name." G XERRX
	I ID="EXT" S ERRMSG="Expected true, got "_VAL G XERRX
	I ID="EXF" S ERRMSG="Expected false, got "_VAL G XERRX
	I ID="EXN" S ERRMSG="Expected null, got "_VAL G XERRX
	I ID="TKN" S ERRMSG="Unable to identify type of token, value was "_VAL G XERRX
	I ID="SCT" S ERRMSG="Stack MIOsmatch - exit stack level was  "_VAL G XERRX
	I ID="EIQ" S ERRMSG="Close quote not found before end of input." G XERRX
	I ID="EIU" S ERRMSG="Unexpected end of input while unescaping." G XERRX
	I ID="RSB" S ERRMSG="Reverse search for \ past beginning of input." G XERRX
	I ID="ORN" S ERRMSG="Overrun while scanning name." G XERRX
	I ID="OR#" S ERRMSG="Overrun while scanning number." G XERRX
	I ID="ORB" S ERRMSG="Overrun while scanning boolean." G XERRX
	I ID="ESC" S ERRMSG="Escaped character not recognized"_VAL G XERRX
	I ID="SOB" S ERRMSG="Unable to serialize node as object, value was "_VAL G XERRX
	I ID="SAR" S ERRMSG="Unable to serialize node as array, value was "_VAL G XERRX
	S ERRMSG="Unspecified error "_ID_" "_$G(VAL)
XERRX
	I $G(MIOERR)]"" D	
	. S @MIOERR@(0)=$G(@MIOERR@(0))+1
	. S @MIOERR@(@MIOERR@(0))=ERRMSG
	. S MIOERRORS=MIOERRORS+1
	Q
DECODE(MIOJSON,MIOROOT,MIOERR)
	S MIOERR=$G(MIOERR)
DIRECT
	S $ET="G MIOJSONET^MIOJSON2"
	N MIOMAX S MIOMAX=1048000
	I $D(@MIOJSON)=1 N MIOINPUT S MIOINPUT(1)=@MIOJSON,MIOJSON="MIOINPUT"
	S MIOROOT=$NA(@MIOROOT@("Z")),MIOROOT=$E(MIOROOT,1,$L(MIOROOT)-4) ; make open array ref
	N MIOLINE,MIOIDX,MIOSTACK,MIOPROP,MIOTYPE,MIOERRORS
	S MIOLINE=$O(@MIOJSON@("")),MIOIDX=1,MIOSTACK=0,MIOPROP=0,MIOERRORS=0
	F  S MIOTYPE=$$NXTKN() Q:MIOTYPE=""  D  I MIOERRORS Q
	. I MIOTYPE="{" S MIOSTACK=MIOSTACK+1,MIOSTACK(MIOSTACK)="",MIOPROP=1 D:MIOSTACK>64 ERRX("STL{") Q
	. I MIOTYPE="}" D:$$NUMERIC(MIOSTACK(MIOSTACK)) ERRX("OBM") S MIOSTACK=MIOSTACK-1 D:MIOSTACK<0 ERRX("SUF}") Q
	. I MIOTYPE="[" S MIOSTACK=MIOSTACK+1,MIOSTACK(MIOSTACK)=1 D:MIOSTACK>64 ERRX("STL[") Q
	. I MIOTYPE="]" D:'$$NUMERIC(MIOSTACK(MIOSTACK)) ERRX("ARM") S MIOSTACK=MIOSTACK-1 D:MIOSTACK<0 ERRX("SUF]") Q
	. I MIOTYPE="," D  Q
	. . I MIOSTACK(MIOSTACK) S MIOSTACK(MIOSTACK)=MIOSTACK(MIOSTACK)+1 
	. . E  S MIOPROP=1                                  
	. I MIOTYPE=":" S MIOPROP=0 D:'$L($G(MIOSTACK(MIOSTACK))) ERRX("MPN") Q
	. I MIOTYPE="""" D  Q
	. . I MIOPROP S MIOSTACK(MIOSTACK)=$$NAMPARS() I 1
	. . E  D ADDSTR
	. S MIOTYPE=$TR(MIOTYPE,"TFN","tfn")
	. I MIOTYPE="t"  D  Q
	. . I $L(@MIOJSON@(MIOLINE))<=MIOIDX+2,$D(@MIOJSON@(MIOLINE+1)) D
	. . . S @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_$E(@MIOJSON@(MIOLINE+1),1,2),@MIOJSON@(MIOLINE+1)=$E(@MIOJSON@(MIOLINE+1),3,$L(@MIOJSON@(MIOLINE+1)))
	. . I $TR($E(@MIOJSON@(MIOLINE),MIOIDX,MIOIDX+2),"RUE","rue")="rue" D SETBOOL("true") I 1
	. . E  B  D ERRX("EXT",MIOTYPE)
	. I MIOTYPE="f" D  Q
	. . I $L(@MIOJSON@(MIOLINE))<=MIOIDX+3,$D(@MIOJSON@(MIOLINE+1)) D
	. . . S @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_$E(@MIOJSON@(MIOLINE+1),1,3),@MIOJSON@(MIOLINE+1)=$E(@MIOJSON@(MIOLINE+1),4,$L(@MIOJSON@(MIOLINE+1)))
	. . I $TR($E(@MIOJSON@(MIOLINE),MIOIDX,MIOIDX+3),"ALSE","alse")="alse" D SETBOOL("false") I 1
	. . E  D ERRX("EXF",MIOTYPE)
	. I MIOTYPE="n" D  Q
	. . I $L(@MIOJSON@(MIOLINE))<=MIOIDX+2,$D(@MIOJSON@(MIOLINE+1)) D
	. . . S @MIOJSON@(MIOLINE)=@MIOJSON@(MIOLINE)_$E(@MIOJSON@(MIOLINE+1),1,2),@MIOJSON@(MIOLINE+1)=$E(@MIOJSON@(MIOLINE+1),3,$L(@MIOJSON@(MIOLINE+1)))
	. . I $TR($E(@MIOJSON@(MIOLINE),MIOIDX,MIOIDX+2),"ULL","ull")="ull" D SETBOOL("null") I 1
	. . E  D ERRX("EXN",MIOTYPE)
	. I "0123456789+-.eE"[MIOTYPE S @$$CURNODE()=$$NUMPARS(MIOTYPE) Q
	. D ERRX("TKN",MIOTYPE_"["_$E(@MIOJSON@(MIOLINE),MIOIDX,MIOIDX+2)_"] ")
	I MIOSTACK'=0 D ERRX("SCT",MIOSTACK)
	Q
NXTKN()
	N MIODONE,MIOEOF,MIOTOKEN
	S MIODONE=0,MIOEOF=0 F  D  Q:MIODONE!MIOEOF
	. I MIOIDX>$L(@MIOJSON@(MIOLINE)) S MIOLINE=$O(@MIOJSON@(MIOLINE)),MIOIDX=1 I 'MIOLINE S MIOEOF=1 Q
	. I $A(@MIOJSON@(MIOLINE),MIOIDX)>32 S MIODONE=1 Q
	. S MIOIDX=MIOIDX+1
	Q:MIOEOF ""
	S MIOTOKEN=$E(@MIOJSON@(MIOLINE),MIOIDX),MIOIDX=MIOIDX+1
	Q MIOTOKEN
ADDSTR
	N MIOEND,MIOX
	S MIOEND=$F(@MIOJSON@(MIOLINE),"""",MIOIDX)
	I MIOEND,($E(@MIOJSON@(MIOLINE),MIOEND-2)'="\") D SETSTR  QUIT  ;normal
	I MIOEND,$$ISCLOSEQ(MIOLINE) D SETSTR QUIT
	N MIODONE,MIOTLINE
	S MIODONE=0,MIOTLINE=MIOLINE
	F  D  Q:MIODONE  Q:MIOERRORS
	. I 'MIOEND S MIOTLINE=MIOTLINE+1,MIOEND=1 I '$D(@MIOJSON@(MIOTLINE)) D ERRX("EIQ") Q
	. S MIOEND=$F(@MIOJSON@(MIOTLINE),"""",MIOEND)
	. I MIOEND,$E(@MIOJSON@(MIOTLINE),MIOEND-2)'="\" S MIODONE=1 Q
	. S MIODONE=$$ISCLOSEQ(MIOTLINE)
	Q:MIOERRORS
	D UESEXT
	S MIOLINE=MIOTLINE,MIOIDX=MIOEND
	Q
SETSTR
	N MIOX
	S MIOX=$E(@MIOJSON@(MIOLINE),MIOIDX,MIOEND-2),MIOIDX=MIOEND
	S @$$CURNODE()=$$UES(MIOX)
	I MIOIDX>$L(@MIOJSON@(MIOLINE)) S MIOLINE=MIOLINE+1,MIOIDX=1
	Q
UESEXT
	N MIOI,MIOY,MIOSTART,MIOSTOP,MIODONE,MIOBUF,MIONODE,MIOMORE,MIOTO
	S MIONODE=$$CURNODE(),MIOBUF="",MIOMORE=0,MIOSTOP=MIOEND-2
	S MIOI=MIOIDX,MIOY=MIOLINE,MIODONE=0
	F  D  Q:MIODONE  Q:MIOERRORS
	. S MIOSTART=MIOI,MIOI=$F(@MIOJSON@(MIOY),"\",MIOI)
	. I (MIOY=MIOTLINE) S MIOTO=$S('MIOI:MIOSTOP,MIOI>MIOSTOP:MIOSTOP,1:MIOI-2) I 1
	. E  S MIOTO=$S('MIOI:99999,1:MIOI-2)
	. D ADDBUF($E(@MIOJSON@(MIOY),MIOSTART,MIOTO))
	. I (MIOY'<MIOTLINE),(('MIOI)!(MIOI>MIOSTOP)) S MIODONE=1 QUIT
	. I 'MIOI S MIOY=MIOY+1,MIOI=1 QUIT 
	. I MIOI>$L(@MIOJSON@(MIOY)) S MIOY=MIOY+1,MIOI=1 I '$D(@MIOJSON@(MIOY)) D ERRX("EIU")
	. D ADDBUF($$REALCHAR($E(@MIOJSON@(MIOY),MIOI),@MIOJSON@(MIOY),.MIOI))
	. S MIOI=MIOI+1
	. I (MIOY'<MIOTLINE),(MIOI>MIOSTOP) S MIODONE=1
	Q:MIOERRORS
	D SAVEBUF
	Q
ADDBUF(MIOX)
	I $L(MIOX)+$L(MIOBUF)>MIOMAX D SAVEBUF
	S MIOBUF=MIOBUF_MIOX
	Q
SAVEBUF
	I 'MIOMORE S @MIONODE=MIOBUF S:+MIOBUF=MIOBUF @MIONODE@("\s")="" I 1
	E  S @MIONODE@("\",MIOMORE)=MIOBUF
	S MIOMORE=MIOMORE+1,MIOBUF=""
	Q
ISCLOSEQ(MIOBLINE)
	N MIOBACK,MIOBIDX
	S MIOBACK=0,MIOBIDX=MIOEND-2
	F  D  Q:$E(@MIOJSON@(MIOBLINE),MIOBIDX)'="\"  Q:MIOERRORS
	. S MIOBACK=MIOBACK+1,MIOBIDX=MIOBIDX-1
	. I (MIOBLINE=MIOLINE),(MIOBIDX=MIOIDX) Q
	. Q:MIOBIDX
	. S MIOBLINE=MIOBLINE-1 I MIOBLINE<MIOLINE D ERRX("RSB") Q
	. S MIOBIDX=$L(@MIOJSON@(MIOBLINE))
	Q MIOBACK#2=0
NAMPARS()
	N MIOEND,MIODONE,MIONAME
	S MIODONE=0,MIONAME=""
	F  D  Q:MIODONE  Q:MIOERRORS
	. S MIOEND=$F(@MIOJSON@(MIOLINE),"""",MIOIDX)
	. I MIOEND S MIONAME=MIONAME_$E(@MIOJSON@(MIOLINE),MIOIDX,MIOEND-2),MIOIDX=MIOEND,MIODONE=1
	. I 'MIOEND S MIONAME=MIONAME_$E(@MIOJSON@(MIOLINE),MIOIDX,$L(@MIOJSON@(MIOLINE)))
	. I 'MIOEND!(MIOEND>$L(@MIOJSON@(MIOLINE))) S MIOLINE=MIOLINE+1,MIOIDX=1 I '$D(@MIOJSON@(MIOLINE)) D ERRX("ORN")
	Q MIONAME
NUMPARS(MIODIGIT)
	N MIODONE,MIONUM
	S MIODONE=0,MIONUM=MIODIGIT
	F  D  Q:MIODONE  Q:MIOERRORS
	. I '("0123456789+-.eE"[$E(@MIOJSON@(MIOLINE),MIOIDX)) S MIODONE=1 Q
	. S MIONUM=MIONUM_$E(@MIOJSON@(MIOLINE),MIOIDX)
	. S MIOIDX=MIOIDX+1 I MIOIDX>$L(@MIOJSON@(MIOLINE)) S MIOLINE=MIOLINE+1,MIOIDX=1 I '$D(@MIOJSON@(MIOLINE)) D ERRX("OR#")
	Q MIONUM
SETBOOL(MIOX)
	S @$$CURNODE()=MIOX
	S MIOIDX=MIOIDX+$L(MIOX)-1
	N MIODIFF S MIODIFF=MIOIDX-$L(@MIOJSON@(MIOLINE))
	I MIODIFF>0 S MIOLINE=MIOLINE+1,MIOIDX=MIODIFF I '$D(@MIOJSON@(MIOLINE)) D ERRX("ORB")
	Q
CURNODE()
	N MIOI,MIOSUBS
	S MIOSUBS=""
	F MIOI=1:1:MIOSTACK S:MIOI>1 MIOSUBS=MIOSUBS_"," D
	. I $$NUMERIC(MIOSTACK(MIOI))  S MIOSUBS=MIOSUBS_MIOSTACK(MIOI)
	. E  S MIOSUBS=MIOSUBS_""""_MIOSTACK(MIOI)_""""
	Q MIOROOT_MIOSUBS_")"
UES(X)
	N POS,Y,START
	S POS=0,Y=""
	F  S START=POS+1 D  Q:START>$L(X)
	. S POS=$F(X,"\",POS+1)
	. I 'POS S Y=Y_$E(X,START,$L(X)),POS=$L(X) I 1
	. E  S Y=Y_$E(X,START,POS-2)_$$REALCHAR($E(X,POS),X,.POS)
	Q Y
REALCHAR(C,X,POS)
	N OPOS
	I C="""" Q """"
	I C="/" Q "/"
	I C="\" Q "\"
	I C="b" Q $C(8)
	I C="f" Q $C(12)
	I C="n" Q $C(10)
	I C="r" Q $C(13)
	I C="t" Q $C(9)
	I C="u" S OPOS=POS S POS=POS+4 Q $C($$FUNC^%HD($E(X,OPOS+1,OPOS+4)))
	Q C
	;
	;